-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_gourdo_healing_seed",
  anim_events={
    trap_gourdo_seed={
      heal={ events={ { frame=11, name="vfx-heal",},},},
      idle={ events={ { frame=0, name="vfx-idle",},},},
      open={ events={ { frame=1, name="vfx-open",},},},
    },
  },
  prefab={ { prefab="gourdo_healing_seed",},},
}
