-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_mothball",
  anim_events={
    mothball_bank={
      behavior1={
        events={
          { frame=7, name="sfx-ears",},
          { frame=14, name="sfx-ears",},
          { frame=22, name="sfx-ears",},
          { frame=32, name="sfx-ears",},
          { frame=40, name="sfx-ears",},
          { frame=48, name="sfx-ears",},
          { frame=58, name="sfx-footstep",},
          { frame=62, name="sfx-ears",},
          { frame=4, name="sfx-chatter",},
          { frame=8, name="sfx-chatter",},
          { frame=12, name="sfx-chatter",},
          { frame=16, name="sfx-chatter",},
          { frame=20, name="sfx-chatter",},
          { frame=24, name="sfx-chatter",},
          { frame=32, name="sfx-chatter",},
          { frame=41, name="sfx-chatter",},
        },
      },
      behavior2={
        events={
          { frame=9, name="sfx-chatter",},
          { frame=33, name="sfx-chatter",},
          { frame=5, name="sfx-ears",},
          { frame=13, name="sfx-ears",},
          { frame=21, name="sfx-ears",},
          { frame=29, name="sfx-ears",},
        },
      },
      claw={ events={ { frame=9, name="sfx-claw",},},},
      claw_loop={ events={ { frame=0, name="sfx-claw_loop",},},},
      elite_bite={ events={ { frame=6, name="sfx-bite",},},},
      elite_bite_pre={ events={ { frame=1, name="sfx-claw_loop",},},},
      flinch_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_back_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_pst={ events={ { frame=0, name="sfx-hit",},},},
      knockdown_hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      knockdown_pre={
        events={
          { frame=12, name="sfx-spawn",},
          { frame=1, name="sfx-hit",},
          { frame=14, name="sfx-knockdown",},
        },
      },
      pierce={ events={ { frame=6, name="sfx-pierce",},},},
      pierce_pre_hold={ events={ { frame=0, name="sfx-pierce_pre_hold",},},},
      spawn={
        events={
          { frame=18, name="sfx-spawn",},
          { frame=4, name="sfx-whoosh",},
          { frame=8, name="sfx-whoosh",},
          { frame=12, name="sfx-whoosh",},
          { frame=16, name="sfx-whoosh",},
        },
      },
      taunt={ events={ { frame=7, name="sfx-taunt",},},},
      walk_loop={
        events={
          { frame=1, name="sfx-footstep",},
          { frame=9, name="sfx-footstep",},
          { frame=3, name="sfx-footstep",},
        },
      },
    },
  },
  prefab={ { prefab="mothball",},},
}
