-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="traveling_potion_cauldron",
  anim_events={
    traveling_potion_cauldron={
      finish={
        events={
          { frame=9, name="vfx-finish", postfix="_1",},
          { frame=1, name="vfx-stop_idle_particle", postfix="_1",},
        },
      },
    },
  },
  prefab={ { baseanim="1", prefab="traveling_potion_cauldron",},},
}
