-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="bomb_explosion_shock_ring",
  anim="shock_ring",
  bank="fx_trap_explosion",
  bloom=50.0,
  build="fx_trap_explosion",
  finaloffset=7,
  glowcolor="00CDFFFF",
  group="bombs_traps",
  hue=-42.0,
  scalex=0.80000001192093,
  scaley=0.80000001192093,
}
