-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_slowpoke_elite_grnd",
  anim="death_ground_splash",
  bank="fx_monster_death_untex",
  brightness=29.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-153.0,
  layer="bg",
  lightoverride=100.0,
  onground=true,
  randomflip=true,
  saturation=-80.0,
  sortorder=2,
}
