-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_boss_grnd",
  anim="boss_death_grnd2",
  bank="fx_monster_death_untex",
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-100.0,
  layer="bg",
  lightoverride=100.0,
  onground=true,
  randomflip=true,
  saturation=-50.0,
  sortorder=2,
}
