-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_tag1",
  anim="ground_tag_1",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  layer="bg",
  multcolor="FFFFFFE6",
  onground=true,
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
  sortorder=2,
  target_tint="FF640000",
}
