-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_charged_tier3_sml",
  anim="electric_charged_tier3",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  layer="bg",
  looping=true,
  multcolor="FFFFFFE6",
  onground=true,
  randomflip=true,
  sortorder=2,
  target_tint="FF640000",
}
