-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_charge_start_med",
  anim="electric_charge_start_3",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  clip_at_worldedge=true,
  group="electricity",
  layer="bg",
  noflip=true,
  onground=true,
  scalex=1.5,
  scaley=2.0,
  sortorder=2,
  target_tint="FF640000",
}
