-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_charged_tier1_gnt",
  anim="electric_charged_tier2",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  layer="bg",
  looping=true,
  multcolor="FFFFFFE6",
  onground=true,
  scalex=1.3999999761581,
  scaley=1.5,
  sortorder=2,
  target_tint="FF640000",
}
