-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bomb_spore_confuse",
  anim="confuse_spin",
  bank="trap_bomb_spore",
  build="trap_bomb_spore",
  looping=true,
  randomstartframe=true,
}
