-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bandicoot_groundring_test",
  anim="test",
  bank="fx_bandicoot_groundring",
  bloom=100.0,
  build="fx_bandicoot_groundring",
  looping=true,
  onground=true,
  scalex=0.60000002384186,
  scaley=0.60000002384186,
  sortorder=-3,
}
