-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bandicoot_swipe2",
  anim="swipe2",
  bank="fx_bandicoot",
  bloom=100.0,
  build="fx_bandicoot",
  finaloffset=1,
  group="fx_bandicoot",
  multcolor="A8D9FFFF",
  scalex=1.0,
  scaley=1.0,
}
