-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_dust_ground_ring_stalactite",
  anim="ground2",
  bank="fx_dust",
  brightness=-25.0,
  build="fx_dust",
  group="fx_dust",
  multcolor="75FFED80",
  noflip=true,
  onground=true,
  scalex=1.2000000476837,
  scaley=1.6000000238419,
  sortorder=-1,
}
