-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_fade_atk_front_fancy",
  anim="fade_atk_front",
  bank="player_fx_hammer",
  bloom=100.0,
  build="fx_player_bank_hammer_swipe",
  finaloffset=1,
  group="fx_hammer",
  lightoverride=100,
}
