-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hit_spikes",
  addcolor="64006400",
  anim="hit_",
  bank="fx_hits_spike_trap",
  bloom=100.0,
  build="fx_hits_spike_trap",
  glowcolor="FF86FCFF",
  variations=3,
}
