-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_heal_burst_potion",
  anim="small",
  bank="fx_heal_burst",
  bloom=82.0,
  build="fx_heal_burst",
  group="healing",
  scalex=0.69999998807907,
  scaley=0.69999998807907,
}
