-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_atk1_fancy",
  anim="atk1",
  bank="player_fx_hammer",
  bloom=100,
  build="fx_player_bank_hammer_swipe",
  finaloffset=1,
  group="fx_hammer_fancy",
  lightoverride=100,
}
