-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_atk1_red_blackedge",
  anim="atk1",
  bank="player_fx_hammer",
  bloom=100.0,
  brightness=-100.0,
  build="fx_player_bank_hammer_swipe",
  finaloffset=1,
  glowcolor="B3213FFF",
  group="fx_hammer_concepts",
  lightoverride=100,
  saturation=-100.0,
}
