-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_spin_air_flash",
  anim="spin_air",
  bank="fx_player_bank_hammer_swipe_basic",
  bloom=100.0,
  build="fx_player_bank_hammer_swipe_basic",
  finaloffset=1,
  group="fx_hammer_flash",
  hue=-70.0,
  multcolor="BF9999FF",
  saturation=100.0,
}
