-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_obelisk_powerup_frnt",
  anim="powerup_yes_pst_front",
  bank="fx_powerup",
  bloom=100.0,
  build="fx_powerup",
  glowcolor="8400FFFF",
  group="obelisk",
  multcolor="FFFFFFE6",
  scalex=2.25,
  scaley=2.0,
  sortorder=1,
  soundevent="power_acquire",
}
