-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_obelisk_powerup_back",
  anim="powerup_yes_pst_back",
  bank="fx_powerup",
  bloom=100.0,
  build="fx_powerup",
  finaloffset=-1,
  glowcolor="8400FFFF",
  group="obelisk",
  layer="bg",
  multcolor="FFFFFFE6",
  scalex=2.25,
  scaley=2.0,
  sortorder=2,
}
