-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_portal_jump_sml",
  anim="electric_chain_arc_small_",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  glowcolor="0F70F0FF",
  group="portals",
  hue=103.0,
  noflip=true,
  scalex=2.0,
  scaley=2.0,
  soundevent="Power_Teleport_Travel",
  target_tint="FF640000",
  variations=2,
}
