-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_atk3_basic",
  anim="atk3",
  bank="fx_player_bank_polearm_basic",
  bloom=100.0,
  build="fx_player_bank_polearm_basic",
  finaloffset=1,
  group="fx_polearm_basic",
  multcolor="B39999FF",
}
