-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_powerup_back",
  anim="powerup_yes_pst_back",
  bank="fx_powerup",
  bloom=100.0,
  build="fx_powerup",
  finaloffset=-1,
  glowcolor="C500FFFF",
  group="fx_player_powerups",
  layer="bg",
  scalex=1.0,
  scaley=1.0,
  sortorder=2,
}
