-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_radius_test",
  anim="150",
  bank="fx_radius_test",
  build="fx_radius_test",
  clip_at_worldedge=true,
  group="fx_warning",
  isminimal=true,
  layer="bg",
  looping=true,
  networked=1,
  onground=true,
  randomstartframe=true,
  sortorder=2,
}
