-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_shotput_roll_fade_h_atk_basic",
  anim="shotput_roll_fade_H_atk",
  bank="fx_player_bank_shotput_basic",
  bloom=100.0,
  build="fx_player_bank_shotput_basic",
  finaloffset=1,
  glowcolor="FCA900FF",
  group="fx_shotput_basic",
  multcolor="CCCCCCFF",
  scalex=1.0,
  scaley=1.0,
}
