-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_shotput_h_atk3_electric",
  anim="shotput_H_atk3",
  bank="fx_player_bank_shotput_electric",
  bloom=100.0,
  build="fx_player_bank_shotput_electric",
  finaloffset=1,
  glowcolor="FCA900FF",
  group="fx_shotput_electric",
  multcolor="CCCCCCFF",
  scalex=1.0,
  scaley=1.0,
}
