-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hit_groundring_still",
  anim="groundring_still",
  bank="fx_hits_groundring",
  bloom=50.0,
  build="fx_hits_groundring",
  clip_at_worldedge=true,
  glowcolor="8E8F43FF",
  group="hits_fx",
  layer="bg",
  onground=true,
  randomflip=true,
  sortorder=2,
}
