-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_block",
  anim="defend",
  bank="fx_hits_block",
  bloom=100.0,
  build="fx_hits_block",
  glowcolor="2BDBE6FF",
  group="hits_fx",
  soundevent="Hit_blocked",
}
