-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_pierce_focus",
  anim="pierce_",
  bank="fx_hits_focus",
  bloom=100.0,
  build="fx_hits_focus",
  glowcolor="03F2FFFF",
  group="hits_fx",
  multcolor="FFFFFFCC",
  sound_max_count=1.0,
  soundevent="Focus_hit_pierce",
  target_tint="04FBFF00",
  variations=5,
}
