-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_jamball",
  anim="hit_1",
  bank="fx_hits_jamball",
  bloom=100.0,
  build="fx_hits_jamball",
  glowcolor="FF8E00FF",
  group="hits_fx",
  noflip=true,
  scalex=1.0,
  scaley=1.0,
  sound_max_count=2.0,
  soundevent="Hit_shotput",
  target_tint="FF640000",
}
