-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_tackle",
  anim="defend_partial",
  bank="fx_hits_block",
  bloom=100.0,
  build="fx_hits_block",
  glowcolor="FFB203FF",
  group="hits_fx",
  scalex=1.0,
  scaley=1.0,
  sound_max_count=1.0,
  target_tint="FF640000",
}
