-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_cannon_shot",
  anim="shot_",
  bank="fx_hits_cannon",
  bloom=100.0,
  build="fx_hits_cannon",
  glowcolor="FF6A00FF",
  group="hits_fx",
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
  sound_max_count=2.0,
  soundevent="Hit_cannon",
  variations=3,
}
