-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="item_pickup_uncommon",
  addcolor="677C2B00",
  anim="loop",
  bank="fx_item_drop",
  bloom=100.0,
  build="fx_item_pickup_untex",
  finaloffset=-1,
  glowcolor="FF9A00FF",
  group="item_drops",
  looping=true,
  multcolor="4DFF521F",
  scalex=0.75,
  scaley=0.55000001192093,
}
