-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_minion",
  anim="idle2",
  bank="fx_minion_projectile",
  bloom=30.0,
  build="fx_minion_projectile",
  glowcolor="1E00FFFF",
  group="projectiles",
  looping=true,
  randomstartframe=true,
}
