-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_shotput_air_fast",
  anim="air_fast",
  bank="fx_player_projectile_shotput",
  build="fx_player_projectile_shotput",
  glowcolor="FFFFFFFF",
  group="projectile_shotput",
  looping=true,
  randomstartframe=true,
  scalex=1.0,
  scaley=1.0,
}
