-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="trap_spores_warning",
  addcolor="000C7E00",
  anim="blinking",
  bank="fx_trap_explosion",
  bloom=80.0,
  build="fx_trap_explosion",
  clip_at_worldedge=true,
  glowcolor="00C223FF",
  group="bombs_traps",
  hue=75.0,
  looping=true,
  multcolor="78FFFF73",
  onground=true,
  scalex=0.5,
  scaley=0.5,
  sortorder=-1,
}
