-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="upgrade_gas_test",
  anim="idle1",
  bank="fx_upgrade_gas",
  bloom=100.0,
  build="fx_upgrade_gas",
  glowcolor="8917D2FF",
  group="TESTING",
  lightoverride=100.0,
  multcolor="FFFFFFB3",
}
