-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_fg_stalag_bandicoot",
  bank="bandiforest_fg_boulder",
  build="bandiforest_fg_boulder",
  fade={ bottom=-5.75, top=-1.51,},
  group="swamp_props",
  parallax={ { anim="stalagcoot",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  variations=3,
}
