-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_fg_boulder_slime",
  bank="bandiforest_fg_boulder",
  build="bandiforest_fg_boulder",
  color_variants={
    {
      brightness=-16.0,
      hue=15.0,
      likelihood=1.0,
      saturation=4.0,
      zones={ "fg_side", "distant_fg",},
    },
  },
  fade={ bottom=-3.65, top=1.35,},
  group="swamp_props",
  parallax={ { anim="boulderslime",},},
  proptype=1,
  variations=3,
}
