-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_fg_tendril",
  bank="bandiforest_fg_tallmold",
  build="bandiforest_fg_tallmold",
  fade={ bottom=-4.08, top=-1.37,},
  group="swamp_props",
  parallax={ { anim="tendril",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=3,
}
