-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_tendril",
  bank="bandiforest_bg_tallmold",
  build="bandiforest_bg_tallmold",
  fade={ bottom=-3.7, top=0.53,},
  group="swamp_props",
  hue=-17.0,
  layer="auto",
  parallax={
    { anim="tendril", dist=-0.5,},
    { anim="tendrilmid",},
    { anim="tendrilback", dist=0.60000002384186,},
  },
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  saturation=-13.0,
  variations=5,
}
