-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_fg_cave",
  fade={ bottom=-6.65, top=3.0,},
  group="swamp_props",
  parallax={ { anim="cave",},},
  proptype=1,
  variations=3,
}
