-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_pillar_bandicoot",
  bank="bandiforest_bg_pillar",
  bloom=14.0,
  bloomtargets={ { name="bloom_me", type="Layer",},},
  build="bandiforest_bg_pillar",
  fade={ bottom=-3.88, top=1.24,},
  glowcolor="484ACAFF",
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="frontcoot_above", autosortlayer="above", dist=-1.2999999523163,},
    { anim="backcoot_above", autosortlayer="above",},
    {
      anim="frontcoot_below",
      autosortlayer="below",
      dist=-1.2999000549316,
      underground=true,
    },
    {
      anim="backcoot_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
  },
  proptype=1,
  variations=3,
}
