-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="destructible_twig_tall",
  gridsize={ { h=2, w=2,},},
  group="swamp_props",
  parallax={
    { anim="1", dist=-0.69999998807907, shadow=true,},
    { anim="2", dist=-0.30000001192093, shadow=true,},
    { anim="3", dist=-0.10000000149012, shadow=true,},
    { anim="4", shadow=true,},
    { anim="5", dist=0.69999998807907, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  procedural_placement_params={ role="destructible",},
  script="prop_destructible",
}
