-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lamp_forest_2",
  bloom=89.0,
  bloomtargets={ { name="candle", type="Symbol",},},
  glowcolor="ED6929FF",
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  looping=true,
  parallax={
    { anim="moss", dist=-0.3, shadow=true,},
    { anim="lantern", dist=-0.2, shadow=true,},
    { anim="flame",},
    { anim="back", dist=0.1,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
  randomstartframe=true,
}
