-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lightspot_leafy",
  bank="fx_lightspot_mouseover",
  build="fx_lightspot_mouseover",
  group="light_group",
  proptype=2.0,
  script="lightspot",
  script_args={
    animate=true,
    max_rotation=4.4109997749329,
    max_translation=0.070000000298023,
    rot_speed=0.29899999499321,
    shimmer=true,
    shimmer_speed=0.69499999284744,
    shimmer_strength=0.10199999809265,
    trans_speed=0.61000001430511,
  },
  variations=4,
}
