-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lightray_west",
  bank="fx_lightrays",
  bankfile="fx_lightrays",
  bloom=100.0,
  build="fx_lightrays",
  glowcolor="FF9004FF",
  group="lightrays_group",
  lightoverride=100.0,
  looping=true,
  multcolor="FFFFFFB3",
  parallax={ { anim="west",}, { anim="grnd_west", dist=0.001, onground=true,},},
  randomstartframe=true,
}
