-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="plushies_mid",
  bank="plushies",
  build="plushies",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={
    { anim="mid_front", dist=-0.2, shadow=true,},
    { anim="mid_mid", dist=-0.1, shadow=true,},
    { anim="mid_leg", shadow=true,},
    { anim="mid_back", dist=0.1, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
  variations=8,
}
