-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="potion_refill_single",
  bank="drop_anims",
  bankfile="drop_anims",
  bloom=55.0,
  bloomtargets={
    { name="border_front", type="Symbol",},
    { name="icon", type="Symbol",},
    { name="border_back", type="Symbol",},
    { name="glow_untex", type="Symbol",},
  },
  build="drop_anims",
  clickable=true,
  group="shop_items",
  hostspawn=true,
  looping=true,
  networked=1,
  nonpersist=true,
  parallax={
    { anim="shop", shadow=true,},
    { anim="ground", dist=0.0010000000474975, onground=true,},
  },
  script="shopitem_config",
  script_args={ item_type="potion_refill_single",},
}
