-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="shield_refill_single",
  bank="basket",
  build="basket",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="shop_items",
  hostspawn=true,
  networked=1,
  parallax={
    { anim="front", dist=-0.20000000298023, shadow=true,},
    { anim="mid",},
    { anim="back", dist=0.20000000298023,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
  script="shopitem_config",
  script_args={ item_type="shield_refill_single",},
  variations=3,
}
