-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_bg_ice",
  bank="snowmtn_ice",
  build="snowmtn_ice",
  group="snowmtn_props",
  layer="backdrop",
  parallax={ { anim="ice",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  variations=5,
}
