-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="specialevent_host",
  bank="forest_floor_grass",
  build="forest_floor_grass",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  multcolor="FFFFFF00",
  parallax={ { anim="grass",},},
  parallax_use_baseanim_for_idle=true,
  randomflip=true,
  randomize=true,
  script="buildings",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
  sound=true,
  variations=3,
}
