-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tundra_bg_tree",
  fade={ bottom=-2.05, top=1.85,},
  group="tundra_props",
  layer="auto",
  parallax={ { anim="tree",},},
  proptype=1.0,
  variations=3,
}
