-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="weapon_rack",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={
    { anim="front", dist=-0.4, shadow=true,},
    { anim="weapons", dist=-0.15, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.05, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.3,
  physicstype="smdec",
  placer=true,
  variations=2,
}
