local loc = require "questral.util.loc"

--[[

	HOW TO:
	Any time a character/enemy/item/concept name is used in a player facing string, use these strings with the name loc macro to programmatically insert the name into the string.
	This'll keep the formatting of names consistent across the game, and allow items and objects to be renamed across the entire project easily by changing the name in this file.
	For each entry added to the STRINGS.NAMES section, a matching entry will have to be added to STRING_METADATA.NAMES_PLURAL if its possible for that term to be pluralized.
	(Plurals aren't autogenerated bc they may grammatically vary in spelling)

	For a singular name, type {name.example}
		eg {name.yammo} = Yammo

	For a plural name, type {name_multiple.example}
		eg {name_multiple.yammo} = Yammos

	For a capitalized singular name, type {NAME.example}
		eg {NAME.yammo} = YAMMO

	For a capitalized plural name, type {NAME_MULTIPLE.example}
		eg {NAME_MULTIPLE.yammo} = YAMMOS

	When used in a game string, it'll look something like this
		"The orange rind of a <#RED>{name.yammo}</>."

	Note that the loc macro doesn't apply colour formatting, so <#RED> and <#BLUE> will still need to be added to the string where the macro is used if the name needs to be coloured.

--]]
STRINGS.NAMES =
{
	--Expedition Name
	foxtails = "Foxtail",

	--Hunters
	hunter = "Hunter",
	species_canine = "Mammimal",
	species_mer = "Amphibee",
	species_ogre =  "Ogre",

	--Town NPCs (no plural form)
	npc_scout = "Flitt", --they/them
	npc_dojo_master = "Toot", --he/him
	npc_apothecary = "Kuma", --she/her
	npc_refiner = "Lottie", --she/her
	npc_blacksmith = "Hamish", --he/him
	npc_armorsmith = "Berna", --she/her
	npc_cook = "Glorabelle",  --she/her
	npc_lunn = "Lunn", --he/him, glorabelle's tool

	dojo = "TEMP NAME",
	dojo_cough = "<#KONJUR><i><z 0.8>(cough cough)</z></i></>",

	--Dungeon NPCs (no plural form)
	npc_konjurist = "Alki", --they/them
	npc_potionmaker_dungeon = "Doc Hoggins", --he/him
	npc_doc_firstname = "Doc",
	npc_doc_lastname = "Hoggins",

	npc_market_merchant = "Alphonse", --he/him

	shop_potion = "Doc Hoggins", --he/him
	shop_powerupgrade = "Alki", --they/them
	shop_armorsmith = "Alphonse", --he/him
	shop_magpie = "Nimble", --cute/bird (he/him tho)

	--Reynard, Godric, Cato, Oswald, Filbert
	npc_grandad = "Hubert", --flitt's grandpa (might change)
	flitt_lastname = "Mulligan",

	--NPC Jobs
	job_scout = "Scout",
	job_blacksmith = "Blacksmith",
	job_armorsmith = "Armourer",
	job_apothecary = "Apothecary",
	job_refiner = "Researcher",
	job_cook = "Cook",
	job_dojo = "Battlemaster",
	job_konjurist = "Teffrite",

	research = "Research", --primarily used on the mosnter research page

	--Job Stations
	station_scout = "Scout's Cartography Desk",
	station_blacksmith = "Blacksmith's Forge",
	station_gems = "Gemcutter's Table", --future note for me, the gemcutter refers to themselves as a "Lapidarist" and is offended when called a "Gemcutter"
	station_armorsmith = "Armourer's Workshop",
	station_apothecary = "Apothecary's Cauldron",
	station_refiner = "Researcher's Equipment",
	station_cook = "Cook's Kitchen",
	station_dojo = "Battlemaster's Pit", --meet me in the PIT
	station_marketroom_shop = "Market Cart", -- WRITER

	elite_prefix = "Imbued",
	miniboss_prefix = "Greater",

	--General Monster Name
	rot = "Rot",
	rot_miniboss = "Miniboss Rot",
	rot_boss = "Boss Rot",

	--Biomes (used to refer to the groupings of dungeons, primarily for the exploration screen, no plural)
	forest = "Forest",
	tundra = "Tundra",
	swamp = "Bog",

	--Dungeons/Individual Locations (no plural)
	brundle = "Camp",
	treemon_forest = "Great Rotwood Forest",
	owlitzer_forest = "Nocturne Grove",
	kanft_swamp = "Blisterbane Bog",
	thatcher_swamp = "The Molded Grave",
	sedament_tundra = "???", --KRIS

	--Bosses
	arak = "Arak",
	bandicoot = "Enigmox",
	bonejaw = "Ossep",
	magmadillo = "Magmadillo",
	owlitzer = "Owlitzer",
	quetz = "Quetzalcoatl",
	rotwood = "Rotwood",
	thatcher = "Thatcher",
	megatreemon = "Mother Treek",

	--Small monsters
	battoad = "Ribbat",
	battoad_elite = "{name.elite_prefix} Ribbat",
	blarmadillo = "Rillo",
	blarmadillo_elite = "{name.elite_prefix} Rillo",
	bulbug = "Tectormite",
	bulbug_elite = "{name.elite_prefix} Tectormite",
	beets = "Beets",
	beets_elite = "{name.elite_prefix} Beets",
	cabbageroll = "Bulbin",
	cabbageroll_elite = "{name.elite_prefix} Bulbin",
	gnarlic = "Gnarlic",
	gnarlic_elite = "{name.elite_prefix} Gnarlic",

	eyev = "Iriss",
	eyev_elite = "{name.elite_prefix} Iriss",
	mothball = "Mothball",
	mothball_elite = "{name.elite_prefix} Mothball",
	mothball_teen = "Greater Mothball",
	mothball_teen_elite = "{name.elite_prefix} Greater Mothball",
	mossquito = "Mossquito",
	mossquito_elite = "{name.elite_prefix} Mossquito",
	slowpoke = "Snortoise",
	slowpoke_elite = "{name.elite_prefix} Snortoise",

	-- Big monsters
	yammo = "Yammo",
	yammo_elite = "{name.miniboss_prefix} Yammo",
	zucco = "Zucco",
	zucco_elite = "{name.miniboss_prefix} Zucco",
	gourdo = "Gourdo",
	gourdo_elite = "{name.miniboss_prefix} Gourdo",

	floracrane = "Floracrane",
	floracrane_elite = "{name.miniboss_prefix} Floracrane",
	groak = "Groak",
	groak_elite = "{name.miniboss_prefix} Groak",
	seeker = "Seeker",
	seeker_elite = "{name.miniboss_prefix} Seeker",

	-- Stationary
	treemon = "Treek",
	treemon_elite = "{name.elite_prefix} Treek",
	trap_weed_spikes = "Spike Plant",
	trap_bomb_pinecone = "Paincone",
	trap_zucco = "Zucco Trap",

	sporemon = "Peashooter",
	sporemon_elite = "{name.elite_prefix} Peashooter",

	windmon = "Gustree",
	windmon_elite = "{name.elite_prefix} Gustree",

	npc_specialeventhost = "????",
	-- See also strings.strings_npc

	-- Key Props
	damselfly = "Damselfly",
	town_grid_cryst = "Wellspring",

	--Currency
	konjur = "Teffra",
	glitz = "Glitz",

	-- Resources
	potion = "Potion",
	tonic = "{name.konjur} Pearl",
	material = "Material",
	konjur_soul_lesser = "Corestone",
	konjur_soul_greater = "Metastone",
	konjur_heart = "Heartstone",
	boss_heart = "{name.konjur} Hearts",
	gem = "Gem", --is excitement, oo-oo-oo gem!

	-- Generic names for weapon categories
	weapon_hammer = "Hammer",
	weapon_polearm = "Spear",
	weapon_shotput = "Striker",
	weapon_cannon = "Cannon",
	weapon_greatsword = "Cleaver",

	-- Ammunition
	cannon_ammo = "Cannonball",

	--Combat Concepts
	concept_relic = "Power",
	concept_skill = "Skill",
	concept_damage = "Damage",
	concept_attack = "Attack",
	concept_focus_hit = "Focus Hit",
	concept_dodge = "Dodge",
	concept_runspeed = "Runspeed",
	concept_ally = "Ally",
	concept_revive = "Revive",
	concept_shield = "Shield",

	dungeon_room = "Encounter",
	run = "Hunt",

	basic = "Basic", -- starting equipment
}

-- Use these in *quests* with the * plurality markup (see loc.format()):
--   "Go kill {count} {count*{name_plurality.yammo}} for me."
-- Or in item descriptions and other strings where the count is constant:
--   "He loved {name_multiple.arak}."
--
-- You don't *have* to specify a plural version for everything in
-- STRINGS.NAMES. Only need the ones we use with {name_multiple.blah} or
-- {name_plurality.blah}. However, all entries here must have a matching
-- entry in STRINGS.NAMES.
--
-- !!! STRING_METADATA table is only for loc and does not exist at runtime !!!
STRING_METADATA.NAMES_PLURAL =
{
	--Expedition Name
	foxtails = "Foxtails",

	--General Monster Name
	rot = "Rots",
	rot_miniboss = "Miniboss Rots",
	rot_boss = "Boss Rots",

	--Hunters
	hunter = "Hunters",
	species_canine = "Mammimals",
	species_mer = "Amphibees",
	species_ogre =  "Ogres",

	-- Bosses
	arak = "Araks",
	bandicoot = "Enigmoxes",
	bonejaw = "Ossepi",
	magmadillo = "Magmadillos",
	owlitzer = "Owlitzers",
	quetz = "Quetzalcoatl",
	rotwood = "Rotwoods",
	thatcher = "Thatchers",
	megatreemon = "Mother Treeks",

	--Small monsters
	battoad = "Ribbats",
	battoad_elite = "{name.elite_prefix} Ribbats",
	blarmadillo = "Rillos",
	blarmadillo_elite = "{name.elite_prefix} Rillos",
	bulbug = "Tectormites",
	bulbug_elite = "{name.elite_prefix} Tectormites",
	beets = "Beetses",
	beets_elite = "{name.elite_prefix} Beetses",
	cabbageroll = "Bulbins",
	cabbageroll_elite = "{name.elite_prefix} Bulbins",
	gnarlic = "Gnarlics",
	gnarlic_elite = "{name.elite_prefix} Gnarlics",

	eyev = "Irisses",
	eyev_elite = "{name.elite_prefix} Irisses",
	mothball = "Mothballs",
	mothball_elite = "{name.elite_prefix} Mothballs",
	mothball_teen = "Greater Mothballs",
	mothball_teen_elite = "{name.elite_prefix} Greater Mothballs",
	mossquito = "Mossquitoes",
	mossquito_elite = "{name.elite_prefix} Mossquitoes",
	slowpoke = "Snortoises",
	slowpoke_elite = "{name.elite_prefix} Snortoise",

	-- Big monsters
	yammo = "Yammos",
	yammo_elite = "{name.miniboss_prefix} Yammos",
	zucco = "Zuccos",
	zucco_elite = "{name.miniboss_prefix} Zuccos",
	gourdo = "Gourdos",
	gourdo_elite = "{name.miniboss_prefix} Gourdos",

	floracrane = "Floracranes",
	floracrane_elite = "{name.miniboss_prefix} Floracranes",
	groak = "Groaks",
	groak_elite = "{name.miniboss_prefix} Groaks",
	seeker = "Seekers",
	seeker_elite = "{name.miniboss_prefix} Seekers",

	-- Stationary
	treemon = "Treeks",
	treemon_elite = "{name.elite_prefix} Treeks",
	trap_weed_spikes = "Spike Plants",
	trap_bomb_pinecone = "Paincones",
	trap_zucco = "Zucco Traps",

	sporemon = "Peashooters",
	sporemon_elite = "{name.elite_prefix} Peashooters",

	windmon = "Gustrees",
	windmon_elite = "{name.elite_prefix} Gustrees",

	--Currency
	konjur = "Teffra",
	glitz = "Glitz",

	--Resources and Consumables
	potion = "Potions",
	tonic = "{name.konjur} Pearls",
	gem = "Gems",
	material = "Materials",
	konjur_soul_lesser = "Corestones",
	konjur_soul_greater = "Metastones",
	konjur_heart = "Heartstones",
	boss_heart = "{name.konjur} Hearts",


	-- Generic names for weapon categories
	weapon_hammer = "Hammers",
	weapon_polearm = "Spears",
	weapon_shotput = "Strikers",
	weapon_cannon = "Cannons",
	weapon_greatsword = "Cleavers",

	-- Ammunition
	cannon_ammo = "Cannonballs",

	--Combat Concepts (note that if the context requires punctuation these can't be used and have to be hardcoded, ie Focus Hit's)
	concept_relic = "Powers",
	concept_skill = "Skills",
	concept_damage = "Damages",
	concept_attack = "Attacks",
	concept_focus_hit = "Focus Hits",
	concept_dodge = "Dodges",
	concept_ally = "Allies",
	concept_revive = "Revives",
	concept_shield = "Shields",

	dungeon_room = "Encounters",
	run = "Expeditions",

	-- Key Props
	town_grid_cryst = "Wellsprings",
}

local function Validate()
	for key,val in pairs(STRINGS.NAMES) do
		dbassert(key:find(loc.name_replacement_pattern), "Table keys must be lowercase letters, numbers, or underscore (same should go for prefab names).")
	end
	return true
end
dbassert(Validate())


STRINGS.TITLE_CARDS = {
	-- These must be short because they're only displayed for a short time and in a small space.
	-- Include TITLE to override the name from STRINGS.NAMES.
	megatreemon = {
		LOWERTHIRD = "Rotten Heart of the Forest",
	},
	yammo = {
		-- Remove if we stop using yammo for miniboss.
		LOWERTHIRD = "Big, yellow, and doesn't mean well in the least",
	},
	yammo_elite = {
		LOWERTHIRD = "Menace of the Woods",
	},
	floracrane_elite = {
		LOWERTHIRD = "Highest in the pecking order"
	},
	gourdo_elite = {
		LOWERTHIRD = "Gourd big or go home"
	},
	groak_elite = {
		LOWERTHIRD = "Big mouth. Bigger temper"
	},
	bandicoot = {
		LOWERTHIRD = "The Illusory Vixen"
	},
	owlitzer = {
		LOWERTHIRD = "Mother of Darkness"
	},
	npc_armorsmith = {
		LOWERTHIRD = "{name.npc_armorsmith} joined your camp!"
	},
	npc_blacksmith = {
		LOWERTHIRD = "{name.npc_blacksmith} joined your camp!"
	},
	npc_cook = {
		LOWERTHIRD = "{name.npc_cook} joined your camp!"
	},
	npc_apothecary = {
		LOWERTHIRD = "{name.npc_apothecary} joined your camp!"
	},
	npc_refiner = {
		LOWERTHIRD = "{name.npc_refiner} joined your camp!"
	},
	npc_dojo_master = {
		LOWERTHIRD = "{name.npc_dojo_master} joined your camp!"
	},
}

