-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_megatreemon_growth_root",
  isfinal=true,
  prefab={ "megatreemon_growth_root",},
  stategraphs={
    sg_megatreemon_growth_root={
      sg_events={
        {
          eventtype="spawnparticles",
          name="vfx-root_attack2_hold_particle",
          param={ duration=30.0, particlefxname="treemon_root_warning",},
        },
        {
          eventtype="spawnparticles",
          name="vfx-root_attack3_hold_particle",
          param={ duration=30.0, particlefxname="treemon_root_warning",},
        },
        {
          eventtype="spawnparticles",
          name="vfx-root_attack4_hold_particle",
          param={ duration=30.0, particlefxname="treemon_root_warning",},
        },
      },
    },
  },
}
