-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_splash_container",
  isfinal=true,
  prefab={ "fx_splash",},
  stategraphs={
    fx_splash={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              duration=45.0,
              followsymbol="fx_attach",
              ischild=true,
              particlefxname="volatile_weapon_trail",
            },
          },
        },
      },
    },
  },
}
