-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_zucco_elite",
  group="Testing",
  isfinal=true,
  prefab={ "zucco_elite",},
  stategraphs={
    sg_zucco={
      sg_events={
        {
          eventtype="spawnparticles",
          name="vfx-dirt_spray",
          param={
            duration=60.0,
            ischild=true,
            offx=1.3600000143051,
            offy=0.0,
            offz=0.0,
            particlefxname="dirt_spray_bounce_right2",
            use_entity_facing=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-swipe3",
          param={ fxname="fx_zucco_swipe3", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-swipe",
          param={ fxname="fx_zucco_swipe", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-swipe2",
          param={ fxname="fx_zucco_swipe2", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-ground_impact",
          param={ impact_size=1, impact_type=1, inheritrotation=true, offx=2.0, offz=0.0,},
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-ground_impact",
          param={ impact_size=1, impact_type=1, inheritrotation=true, offx=-2.0, offz=0.0,},
        },
      },
      state_events={
        idle={  },
        swipe={  },
        swipe2={  },
        swipe3={  },
        swipe4={
          {
            eventtype="spawneffect",
            name="vfx-swipe",
            param={
              fxname="fx_zucco_swipe4",
              inheritrotation=true,
              ischild=true,
              stopatexitstate=true,
            },
          },
        },
        swipe4_pst={
          {
            eventtype="spawneffect",
            name="vfx-swipe",
            param={ fxname="fx_zucco_swipe4_pst", inheritrotation=true, ischild=true,},
          },
        },
        windmill={
          {
            eventtype="spawneffect",
            name="vfx-windmill_loop",
            param={
              fxname="fx_zucco_windmill",
              inheritrotation=true,
              ischild=true,
              stopatexitstate=true,
            },
          },
        },
      },
    },
  },
}
