-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_swamp_stalactite_peekaboom",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "swamp_stalactite_peekaboom",},
  stategraphs={
    sg_swamp_stalactite={
      events={
        fall={
          {
            eventtype="playsound",
            frame=1,
            param={ sound_max_count=1.0, soundevent="Destructible_Stalactite_Fall",},
          },
        },
        fall_pre={  },
        land={
          {
            eventtype="playsound",
            frame=1,
            param={ sound_max_count=1.0, soundevent="Destructible_Stalactite_Drop_Impact",},
          },
          { eventtype="stopsound", frame=1, param={ name="rumble",},},
        },
        peekaboom_impact={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Destructible_Stalactite_Drop_Impact_large",},
          },
          { eventtype="stopsound", frame=1, param={ name="rumble",},},
          {
            eventtype="playsound",
            frame=1,
            param={
              autostop=true,
              soundevent="Destructible_Stalactite_low_rumble_LP",
              stopatexitstate=true,
            },
          },
        },
        peekaboom_shockwave={  },
      },
    },
  },
}
