-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_thatcher",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "thatcher",},
  stategraphs={
    sg_thatcher={
      events={
        acid_splash={
          { eventtype="playsound", frame=83, param={ soundevent="thatcher_catch",},},
          {
            eventtype="playsound",
            frame=21,
            param={
              autostop=true,
              name="thatcher_twirl",
              soundevent="thatcher_twirl_LP",
              stopatexitstate=true,
            },
          },
          { eventtype="stopsound", frame=85, param={ name="thatcher_twirl",},},
          {
            eventtype="setsoundparameter",
            frame=22,
            param={
              param_name="twirl_LP_speed",
              param_value=0.98000001907349,
              sound_name="thatcher_twirl",
            },
          },
          {
            eventtype="setsoundparameter",
            frame=28,
            param={
              param_name="twirl_LP_speed",
              param_value=0.56499999761581,
              sound_name="thatcher_twirl",
            },
          },
          {
            eventtype="setsoundparameter",
            frame=77,
            param={
              param_name="twirl_LP_speed",
              param_value=0.050000000745058,
              sound_name="thatcher_twirl",
            },
          },
          {
            eventtype="setsoundparameter",
            frame=68,
            param={
              param_name="twirl_LP_speed",
              param_value=0.85000002384186,
              sound_name="thatcher_twirl",
            },
          },
        },
        dormant_getup_pst={
          {
            eventtype="playsound",
            frame=1,
            param={
              autostop=true,
              name="twirl",
              soundevent="thatcher_twirl_LP",
              stopatexitstate=true,
            },
          },
          { eventtype="stopsound", frame=10, param={ name="twirl",},},
        },
        hook={
          {
            eventtype="playsound",
            frame=12,
            param={
              autostop=true,
              name="twirl_LP",
              soundevent="thatcher_twirl_LP",
              stopatexitstate=true,
            },
          },
          {
            eventtype="setsoundparameter",
            frame=15,
            param={
              param_name="twirl_LP_speed",
              param_value=0.53500002622604,
              sound_name="twirl_LP",
            },
          },
          { eventtype="playsound", frame=23, param={ soundevent="thatcher_catch",},},
          { eventtype="stopsound", frame=24, param={ name="twirl_LP",},},
          { eventtype="playsound", frame=29, param={ soundevent="thatcher_whoosh",},},
          { eventtype="playsound", frame=30, param={ soundevent="thatcher_swipe",},},
        },
        idle={  },
        swing_smash_pre={
          {
            eventtype="playsound",
            frame=6,
            param={
              autostop=true,
              name="thatcher_twirl",
              soundevent="thatcher_twirl_LP",
              stopatexitstate=true,
            },
          },
          { eventtype="playsound", frame=15, param={ soundevent="thatcher_catch",},},
          { eventtype="stopsound", frame=15, param={ name="thatcher_twirl",},},
          {
            eventtype="setsoundparameter",
            frame=7,
            param={
              param_name="twirl_LP_speed",
              param_value=0.62999999523163,
              sound_name="thatcher_twirl",
            },
          },
          { eventtype="playsound", frame=17, param={ soundevent="thatcher_grunt",},},
        },
      },
      sg_events={
        { eventtype="playfoleysound", name="sfx-footstep", param={ soundtag="Footstep",},},
        { eventtype="playfoleysound", name="sfx-bodyfall", param={ soundtag="Bodyfall",},},
        {
          eventtype="playsound",
          name="sfx-wings_q",
          param={ soundevent="thatcher_wings", volume=18.0,},
        },
        { eventtype="playsound", name="sfx-wings", param={ soundevent="thatcher_wings",},},
        {
          eventtype="playfoleysound",
          name="sfx-footstep_slide",
          param={ soundtag="Footstep Stop",},
        },
        {
          eventtype="playsound",
          name="sfx-be1",
          param={ soundevent="thatcher_behaviour_1",},
        },
        { eventtype="playsound", name="sfx-spit", param={ soundevent="thatcher_spit",},},
        { eventtype="playsound", name="sfx-swipe", param={ soundevent="thatcher_swipe",},},
        {
          eventtype="playsound",
          name="sfx-whoosh",
          param={ soundevent="thatcher_whoosh",},
        },
        {
          eventtype="playsound",
          name="sfx-full_hold",
          param={ soundevent="thatcher_swing_hold",},
        },
        {
          eventtype="playsound",
          name="sfx-hold",
          param={
            autostop=true,
            name="thatcher_hold",
            soundevent="thatcher_hold",
            stopatexitstate=true,
          },
        },
        { eventtype="playsound", name="sfx-vo2", param={ soundevent="thatcher_vo_2",},},
        {
          eventtype="playsound",
          name="sfx-whoosh2",
          param={ soundevent="thatcher_whoosh2",},
        },
        {
          eventtype="playsound",
          name="sfx-swipe2",
          param={ soundevent="thatcher_swipe_2",},
        },
        { eventtype="playsound", name="sfx-whip", param={ soundevent="thatcher_whip",},},
        { eventtype="playsound", name="sfx-vo1", param={ soundevent="thatcher_vo_1",},},
        { eventtype="playsound", name="sfx-grunt", param={ soundevent="thatcher_grunt",},},
        {
          eventtype="playsound",
          name="sfx-puke",
          param={ soundevent="thatcher_puke", stopatexitstate=true,},
        },
        { eventtype="playsound", name="sfx-catch", param={ soundevent="thatcher_catch",},},
      },
    },
  },
}
