-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_trap_banana_peel",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "banana_peel",},
  stategraphs={
    sg_trap_bananapeel={
      events={
        slip={
          { eventtype="playsound", frame=1, param={ soundevent="Skill_BananaPeel_Slip",},},
        },
      },
    },
  },
}
