-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_powerup_common",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "player_side",},
  sg_wildcard=true,
  stategraphs={
    ["*"]={
      sg_events={
        {
          eventtype="playsound",
          name="powerup",
          param={ soundevent="Player_power_up", stopatexitstate=true,},
        },
        {
          eventtype="playsound",
          name="sfx-buff_whoosh",
          param={ autostop=true, soundevent="Skill_BuffNextAttack_Whoosh",},
        },
        {
          eventtype="playsound",
          name="sfx-buff_pound",
          param={ autostop=true, soundevent="Skill_BuffNextAttack_Pound",},
        },
      },
    },
  },
}
