-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_cabbagerolls_elite_alt",
  group="sound_creature",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "cabbagerolls_elite",},
  stategraphs={
    sg_cabbagerolls={
      sg_events={
        {
          eventtype="playsound",
          name="sfx-hold",
          param={ soundevent="cabbagerolls2_hold",},
        },
        {
          eventtype="playsound",
          name="sfx-whoosh",
          param={ soundevent="cabbageroll_whoosh",},
        },
        {
          eventtype="playsound",
          name="sfx-bodyfall",
          param={ soundevent="cabbageroll_bodyfall",},
        },
        {
          eventtype="playsound",
          name="sfx-slap",
          param={ soundevent="cabbagerolls_slap",},
        },
        {
          eventtype="playsound",
          name="sfx-throw",
          param={ soundevent="cabbagerolls2_throw",},
        },
        {
          eventtype="playfoleysound",
          name="sfx-footstep",
          param={ soundtag="Footstep", volume=26,},
        },
        {
          eventtype="playsound",
          name="sfx-groundslam",
          param={ soundevent="cabbageroll_Elite_ground_hit",},
        },
        {
          eventtype="playsound",
          name="sfx-groundslam_quiet",
          param={ soundevent="cabbageroll_Elite_ground_hit", volume=29,},
        },
        {
          eventtype="playsound",
          name="sfx-knock",
          param={ soundevent="cabbageroll_Elite_knockdown",},
        },
        {
          eventtype="playsound",
          name="sfx-behavior1",
          param={
            sound_max_count=5.0,
            soundevent="cabbageroll_Elite_behaviour_2_3",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="sfx-vo",
          param={ sound_max_count=10.0, soundevent="cabbageroll_Elite_VO", stopatexitstate=true,},
        },
        {
          eventtype="playsound",
          name="sfx-vo_pitched",
          param={
            sound_max_count=10.0,
            soundevent="cabbageroll_VO_pitched",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="sfx-hit",
          param={ sound_max_count=5.0, soundevent="cabbageroll_Elite_hit",},
        },
      },
    },
  },
}
