-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_slowpoke",
  anim_events={
    slowpoke_bank={
      body_slam={
        events={
          { frame=23, name="vfx-body_slam_groundust",},
          { frame=24, name="vfx-body_slam_impact",},
          { frame=25, name="vfx-body_slam_groundring",},
          { frame=21, name="vfx-body_slam_dust",},
        },
      },
      elite_body_slam_loop={ events={ { frame=24, name="vfx-elite_body_slam_loop",},},},
      spawn_land={ events={ { frame=1, name="vfx-spawn_land",},},},
      spawn_pst={ events={ { frame=0, name="vfx-spawn_pst",},},},
      spit_bomb={ events={ { frame=10, name="vfx-spit_bomb",},},},
    },
  },
  prefab={ { prefab="slowpoke",},},
}
