-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="cabbageroll_dye_3",
  cosmetic_data={
    armour_set="cabbageroll",
    build_override="armor_cabbageroll_dye_3",
    dye_number=3,
    title_key="BOOMER",
  },
  group="EQUIPMENT_DYE",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
