-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_poofy_hair_1",
  cosmetic_data={
    bodypart_group="HAIR",
    bodypart_species="canine",
    build="player_hair_canine_poofy",
    colorgroup="SKIN_TONE",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
