-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_nose_color_5",
  cosmetic_data={
    color={ 0.54901963472366, 0.33333334326744, 0.839215695858,},
    color_species="canine",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
