-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_mauve_hair_color_1",
  cosmetic_data={
    color={ 0.98611111111111, 0.49, 0.48,},
    color_species="canine",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
