-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="drillsergeant",
  cosmetic_data={ title_key="DRILLSERGEANT",},
  group="PLAYER_TITLE",
  hidden=false,
  locked=false,
  mastery="POLEARM_MASTERY",
  purchased=false,
  rarity="EPIC",
  
}
