-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_nod_cheerful",
  cosmetic_data={
    anim="emote_nod_cheerful",
    emote_species="none",
    icon_path="images/icons_ftf/emote_nod_cheerful.tex",
    name_key="nod_cheerful",
  },
  group="PLAYER_EMOTE",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
