-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_waves_ornament_1",
  cosmetic_data={
    bodypart_group="ORNAMENT",
    bodypart_species="mer",
    build="player_ornament_mer_waves",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
