-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_7",
  cosmetic_data={
    color={ 0.75289577245712, 0.44401544332504, 0.50579154491425,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
