-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_double_ears",
  cosmetic_data={
    bodypart_group="EARS",
    bodypart_species="ogre",
    build="player_ears_ogre_double",
    colorgroup="EAR_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
