-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="stinky",
  cosmetic_data={ title_key="STINKY",},
  group="PLAYER_TITLE",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
