-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_bg_fern",
  fade={ bottom=-3.24, top=1.32,},
  group="forest_props",
  layer="auto",
  parallax={
    { anim="fernfront_above", autosortlayer="above",},
    {
      anim="fernfront_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    { anim="fernback_above", autosortlayer="above", dist=0.3,},
    {
      anim="fernback_below",
      autosortlayer="below",
      dist=0.30009999871254,
      underground=true,
    },
  },
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=6,
}
