-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_bossrock",
  bank="forest_fg_rock",
  build="forest_fg_rock",
  fade={ bottom=-3.38, top=-0.36,},
  group="forest_props",
  parallax={ { anim="bossrock",},},
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=4,
}
