-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_berryshrub",
  brightness=-10.0,
  gridsize={ { h=2, w=2,},},
  group="forest_props",
  looping=true,
  parallax={ { anim="1", dist=-0.6,}, { anim="2", dist=-0.4,}, { anim="3", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  placer=true,
  randomstartframe=true,
  saturation=-10.0,
}
