-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_prop",
  bank="snowmtn_ruin",
  build="snowmtn_ruin",
  group="snowmtn_props",
  parallax={ { anim="prop",},},
  parallax_use_baseanim_for_idle=true,
  variations=13,
}
