-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_bg_volcano",
  bloom=90.0,
  bloomtargets={ { name="bloom_me", type="Symbol",},},
  glowcolor="55067AFF",
  group="town_bg_props",
  layer="backdrop",
  parallax={ { anim="idle_volcano",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
}
