-- Generated by AnimTester and loaded by animtest_autogen.lua
return {
  __displayName="test",
  animdata={
    { anim="knockdown_getup", bank="bandicoot", flip=false,},
    { anim="bite", bank="bandicoot", flip=false,},
    { anim="bite", bank="bandicoot", flip=false,},
  },
  build="bandicoot",
  loopanim=true,
}
