-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_gourdo_hat",
  build="drops_gourdo",
  droptype="soft",
  group="drops_gourdo",
  loot_id="gourdo_hat",
  symbol="gourdo_hat",
}
