-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_groak_chin",
  build="drops_groak",
  droptype="jiggle",
  group="drops_groak",
  loot_id="groak_chin",
  symbol="groak_chin",
}
