-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_thatcher_fur",
  build="drops_thatcher",
  droptype="soft",
  group="drops_thatcher",
  loot_id="thatcher_fur",
  motionfacing=true,
  symbol="thatcher_fur",
}
