-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="bomb_explosion_warning_clear",
  anim="blinking_clear",
  bank="fx_trap_explosion",
  bloom=100.0,
  build="fx_trap_explosion",
  clip_at_worldedge=true,
  finaloffset=7,
  glowcolor="FF00E6FF",
  group="bombs_traps",
  multcolor="FFFFFFBF",
  onground=true,
  sortorder=-1,
}
