-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_mothball_spawner_frnt",
  anim="death_splat_wide",
  bank="fx_monster_death_untex",
  brightness=60.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-50.0,
  randomflip=true,
  saturation=-85.0,
  shadow=true,
  sound_max_count=3.0,
  soundevent="mothball_death",
}
