-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_gourdo_seed_frnt",
  anim="death_splat_sml",
  bank="fx_monster_death_untex",
  brightness=100.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=55.0,
  randomflip=true,
  saturation=-80.0,
  scalex=0.80000001192093,
  scaley=0.80000001192093,
  shadow=true,
  sound_max_count=3.0,
}
