-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_floracrane_frnt",
  anim="death_air_sml",
  bank="fx_monster_death_untex",
  brightness=50.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=94.0,
  randomflip=true,
  saturation=-85.0,
  scalex=1.25,
  scaley=1.5,
  shadow=true,
}
