-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_minion2_grnd",
  anim="death_ground_splash",
  bank="fx_monster_death_untex",
  brightness=8.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-99.0,
  layer="bg",
  multcolor="FFFFFFCC",
  noflip=true,
  onground=true,
  saturation=-66.0,
  scalex=0.75,
  scaley=0.75,
  sortorder=2,
}
