-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_mossquito_elite_frnt",
  anim="death_air_sml",
  autostop=true,
  bank="fx_monster_death_untex",
  brightness=-30.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-63.0,
  randomflip=true,
  saturation=-84.0,
  scalex=1.0,
  scaley=1.0,
  shadow=true,
  soundevent="mossquito_death",
}
