-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_chain_start_gnt",
  anim="electric_chain_start_large",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  randomflip=true,
  scalex=1.5,
  scaley=1.5,
  soundevent="Power_Electric_Bolt",
  target_tint="FF640000",
}
