-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bandicoot_groundring_solid",
  anim="solid",
  bank="fx_bandicoot_groundring",
  bloom=48.0,
  build="fx_bandicoot_groundring",
  glowcolor="D100FFFF",
  onground=true,
  scalex=0.60000002384186,
  scaley=0.60000002384186,
  sortorder=-3,
  soundevent="Destructible_Stalactite_low_rumble",
}
