-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_groak_swallow_pst",
  anim="swallow_yes",
  bank="fx_groak",
  bloom=100.0,
  build="fx_groak",
  group="fx_groak",
  multcolor="FFFFFF4D",
  scalex=1.0,
  scaley=1.0,
}
