-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_charge_glint",
  anim="fx_hammer_atk4_pre",
  bank="fx_hammer_charge_glint",
  build="fx_hammer_charge_glint",
  group="hammer_charge",
  soundevent="Glint_Hammer_Overhead",
}
