-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_cannon_h_atk_ammo4_basic",
  anim="blast_ammo3",
  bank="fx_player_bank_cannon",
  bloom=100.0,
  build="fx_player_bank_cannon",
  finaloffset=1,
  group="fx_cannon",
  multcolor="CCCCCCFF",
  scalex=1.0,
  scaley=1.0,
}
