-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_portal_pulse_in2",
  anim="charge_lines",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  hue=85.0,
  multcolor="FFFFFFE6",
  randomflip=true,
  scalex=2.0,
  scaley=2.0,
  sortorder=3,
  target_tint="FF640000",
}
