-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_relics_retaliation_target",
  anim="1",
  bank="fx_hit_fire",
  bloom=100.0,
  build="fx_hit_fire",
  glowcolor="B900FFFF",
  group="relics",
  sound_max_count=3.0,
  soundevent="Power_Retaliation_Target",
  target_tint="FF000000",
}
