-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_spores_juggernaut_all",
  anim="ground2",
  bank="fx_dust",
  bloom=100.0,
  build="fx_dust",
  group="fx_spores",
  multcolor="FFA894B3",
  onground=true,
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
  soundevent="spore_cloud_juggernaut",
}
