-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_shotput_indicator",
  addcolor="B0412B00",
  anim="loop",
  bank="fx_item_drop",
  bloom=100.0,
  build="fx_item_pickup_untex",
  finaloffset=-1,
  glowcolor="FF9A00FF",
  group="item_drops",
  looping=true,
  multcolor="FFFFFF1F",
  scalex=1.6000000238419,
  scaley=1.5,
}
