-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="test_particle_double_helix",
  anim="idle",
  bank="rotation_particle_test",
  build="rotation_particle_test",
  group="TESTING",
  lightoverride=100.0,
  looping=true,
  onground=true,
  randomstartframe=true,
}
