-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_slime3",
  bank="bandiforest_grid_slime",
  build="bandiforest_grid_slime",
  group="swamp_props",
  parallax={ { anim="front1", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
}
