-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_mossyrock2",
  bank="bandiforest_grid_mossyrock",
  build="bandiforest_grid_mossyrock",
  gridsize={ { h=2, w=2,},},
  group="swamp_props",
  parallax={
    { anim="front2", dist=-0.30000001192093, shadow=true,},
    { anim="back2", shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.2,
  physicstype="dec",
}
