-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bloom_test",
  bloom=100.0,
  bloomtargets={ { name="bloom_me", type="Layer",},},
  group="forest_props",
  parallax={ { anim="idle",},},
  parallax_use_baseanim_for_idle=true,
}
