-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bread_oven",
  clickable=true,
  gridsize={ { h=3, w=3,},},
  group="town_decor",
  parallax={
    { anim="shovel", dist=-0.15,},
    { anim="front", dist=-0.1, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.3, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=2,
  physicstype="dec",
  placer=true,
  variations=1,
}
