-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="canopy_shadow_branches",
  script="canopy",
  script_args={
    canopy_animate=true,
    canopy_maxrotation=4.7870001792908,
    canopy_maxtranslation=0.21299999952316,
    canopy_rotation=71.80899810791,
    canopy_rotspeed=0.45199999213219,
    canopy_scale=6.3619999885559,
    canopy_strength=0.34000000357628,
    canopy_transspeed=0.55900001525879,
    texture="shadows_tree_branches.tex",
  },
}
