-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_pickup_single",
  bank="soul_drop_konjur_soul_lesser",
  bloom=30.0,
  bloomtargets={ { name="konjur", type="Layer",}, { name="charge", type="Layer",},},
  build="soul_drop_konjur_soul_lesser",
  clickable=true,
  glowcolor="3700FFFF",
  group="shop_items",
  hostspawn=true,
  looping=true,
  networked=1,
  nonpersist=true,
  parallax={
    { anim="shadow1", dist=-0.1, shadow=true,},
    { anim="1",},
    { anim="ground", dist=0.001, onground=true,},
  },
  script="shopitem_config",
  script_args={
    item_type="corestone_pickup_single",
    power_category="ALL",
    power_family="PLAYER",
    power_type="SKILL",
    soul_type="konjur_soul_lesser",
  },
}
