-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="fence_stone",
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={
    { anim="front", dist=-0.1, shadow=true,},
    { anim="back", dist=0.1, shadow=true,},
    { anim="mid", shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smobs",
}
