-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_owlbranch",
  gridsize={ { h=2, w=6,},},
  group="forest_props",
  parallax={
    { anim="onefront", dist=-0.69999998807907, shadow=true,},
    { anim="onemid", shadow=true,},
    { anim="oneback", dist=1.0, shadow=true,},
  },
  physicssize=3,
  physicstype="obs",
  randomize=true,
}
