-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_bg_tree_split",
  fade={ bottom=-1, top=3,},
  layer="auto",
  parallax={ { anim="tree_below", underground=true,}, { anim="tree_above", dist=0.001,},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  silhouette=true,
  variations=3,
}
