-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_skull",
  gridsize={ { h=3, w=3,},},
  group="forest_props",
  parallax={
    { anim="front", dist=-0.5, shadow=true,},
    { anim="mid", dist=-0.2, shadow=true,},
    { anim="back", shadow=true,},
    { anim="horn", dist=0.3, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=2.0,
  physicstype="dec",
  variations=3,
}
