-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_deadtree",
  fade={ bottom=-2.66, top=0.93,},
  group="forest_props",
  parallax={ { anim="front",}, { anim="back", dist=0.7,},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=3,
}
