-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_owlbranch3",
  bank="forest_grid_owlbranch",
  build="forest_grid_owlbranch",
  gridsize={ { h=2, w=6,},},
  group="forest_props",
  parallax={
    { anim="threefront", dist=-0.69999998807907, shadow=true,},
    { anim="threemid", shadow=true,},
    { anim="threeback", dist=0.80000001192093, shadow=true,},
  },
  physicssize=3,
  physicstype="obs",
  randomize=true,
}
