-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_deadtree",
  bloom=40.0,
  bloomtargets={ { name="crystals", type="Symbol",},},
  brightness=-10.0,
  gridsize={ { h=2, w=2,},},
  group="forest_props",
  looping=true,
  parallax={
    { anim="branches", dist=-0.3, shadow=true,},
    { anim="trunk", shadow=true,},
    { anim="back", dist=0.3,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="smdec",
  randomstartframe=true,
  saturation=-10.0,
}
