-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_rottree",
  bank="forest_fg_tree",
  build="forest_fg_tree",
  fade={ bottom=-1, top=3,},
  group="forest_props",
  parallax={ { anim="rottree",},},
  proptype=1,
  variations=4,
}
