-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_floor_megaroot",
  gridsize={ { h=14, level=-1, w=14,},},
  group="forest_props",
  layer="bg",
  onground=true,
  parallax={ { anim="idle",},},
  parallax_use_baseanim_for_idle=true,
  sortorder=2,
}
