-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_bg_deadtree_mega",
  bank="forest_bg_deadtree",
  bloom=50.0,
  bloomtargets={ { name="crystals", type="Symbol",},},
  build="forest_bg_deadtree",
  fade={ bottom=-1.44, top=2.4,},
  group="forest_props",
  layer="auto",
  parallax={
    { anim="megafront_above", autosortlayer="above",},
    { anim="megaback_above", autosortlayer="above", dist=0.5,},
    {
      anim="megafront_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    {
      anim="megaback_below",
      autosortlayer="below",
      dist=0.50010001659393,
      underground=true,
    },
  },
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=3,
}
