-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_up_canopy",
  group="forest_props",
  layer="auto",
  parallax={ { anim="canopy",},},
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=4,
}
