-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_deadcanopy",
  bank="forest_up_canopy",
  bankfile="forest_up_canopy",
  build="forest_up_canopy",
  fade={ bottom=16.65, top=11.86,},
  group="forest_props",
  parallax={ { anim="redfg",},},
  proptype=1,
  variations=4,
}
