-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="kitchen_chair",
  gridsize={ { h=2, w=2,},},
  group="shop_props",
  parallax={
    { anim="1", dist=-0.55, shadow=true,},
    { anim="2", dist=-0.4, shadow=true,},
    { anim="3", shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="dec",
  placer=true,
}
