-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lightspot_angular",
  bank="fx_lightspot_mouseover",
  build="fx_lightspot_mouseover",
  group="light_group",
  proptype=2.0,
  script="lightspot",
  variations=4,
}
