-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="marketroom_rug_long",
  bank="marketroom_rug",
  brightness=0,
  build="marketroom_rug",
  gridsize={ { h=3, level=-1, w=3,},},
  group="shop_props",
  hue=0,
  layer="bg",
  onground=true,
  parallax={ { anim="3",},},
  parallax_use_baseanim_for_idle=true,
  saturation=0,
  sortorder=2,
}
