-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="plot_apothecary_rubble",
  bank="plot_chemist",
  build="plot_chemist",
  group="town_bg_props",
  parallax={ { anim="rubble", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  variations=6,
}
