-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="plot_cook_decor",
  bank="plot_kitchen",
  build="plot_kitchen",
  group="town_plots",
  parallax={
    { anim="1", dist=-0.80000001192093, shadow=true,},
    { anim="2", shadow=true,},
    { anim="3", dist=0.20000000298023, shadow=true,},
    { anim="4", dist=0.40000000596046, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=4,
  physicstype="smobs",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
}
