-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="power_drop_generic_1p",
  bank="power_drop_generic",
  bankfile="power_drop_generic",
  bloom=20.0,
  bloomtargets={ { name="konjur", type="Layer",}, { name="charge", type="Layer",},},
  build="power_drop_generic",
  clickable=true,
  glowcolor="3700FFFF",
  group="power_drops",
  looping=true,
  nonpersist=true,
  parallax={
    { anim="shadow1", dist=-0.1, shadow=true,},
    { anim="1",},
    { anim="ground", dist=0.001, onground=true,},
  },
  script="powerdrops",
  script_args={ power_category="ALL", power_family="PLAYER", power_type="RELIC",},
}
