-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="rottingforest_grid_tree",
  brightness=-5.0,
  gridsize={ { h=2, w=2,},},
  group="rottingforest_props",
  looping=true,
  parallax={
    { anim="front", dist=-0.2, shadow=true,},
    { anim="2", shadow=true,},
    { anim="mid", dist=0.3, shadow=true,},
    { anim="back", dist=0.5, shadow=true,},
    { anim="3", dist=0.6, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  randomstartframe=true,
  saturation=-8.0,
}
