-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="rottingforest_bg_pile",
  fade={ bottom=-3.06, top=0.29,},
  group="rottingforest_props",
  layer="backdrop",
  looping=true,
  parallax={ { anim="pile",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  randomstartframe=true,
  variations=4,
}
