-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="rottingforest_bg_root",
  fade={ bottom=-2.34, top=0.77,},
  group="rottingforest_props",
  layer="backdrop",
  looping=true,
  parallax={ { anim="root",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  randomstartframe=true,
  variations=6,
}
