-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="rottingforest_grid_neon",
  bloom=60.0,
  bloomtargets={ { name="neon_light", type="Symbol",},},
  gridsize={ { h=2, w=2,},},
  group="rottingforest_props",
  parallax={ { anim="neon", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  variations=2,
}
