-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_rubble",
  bank="snowmtn_ruin",
  build="snowmtn_ruin",
  group="snowmtn_props",
  parallax={ { anim="rubble",},},
  parallax_use_baseanim_for_idle=true,
  variations=6,
}
