-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_brick",
  bank="snowmtn_rock",
  build="snowmtn_rock",
  group="snowmtn_props",
  parallax={ { anim="brick",},},
  parallax_use_baseanim_for_idle=true,
  variations=4,
}
