-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_wallb",
  backdist=1.0,
  bank="snowmtn_border",
  build="snowmtn_border",
  group="snowmtn_props",
  parallax={ { anim="wallb",},},
  parallax_use_baseanim_for_idle=true,
  variations=4,
}
