-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="snowmtn_roof",
  bank="snowmtn_border",
  build="snowmtn_border",
  group="snowmtn_props",
  parallax={ { anim="roof",},},
  parallax_use_baseanim_for_idle=true,
  variations=7,
}
