-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_wall_long",
  bank="town_grid_wall_long",
  brightness=-8.0,
  build="town_grid_wall_long",
  group="town_bg_props",
  hue=-7.0,
  parallax={
    { anim="rubble", dist=-0.10000000149012, shadow=true,},
    { anim="wall", shadow=true,},
    { anim="back", dist=0.40000000596046,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=7.8,
  physicstype="obs",
  saturation=9.0,
}
