-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_rubble",
  bank="town_grid_rubble",
  build="town_grid_rubble",
  gridsize={ { h=2, w=2,},},
  group="town_bg_props",
  parallax={
    { anim="front", dist=-0.10000000149012, shadow=true,},
    { anim="back", shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  variations=5,
}
