-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_bg_ruinsside",
  bank="town_bg_ruins",
  build="town_bg_ruins",
  fade={ bottom=-2.9, top=1.67,},
  group="town_bg_props",
  layer="auto",
  parallax={ { anim="side",},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  variations=2,
}
