-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="trap_spores_damage",
  bank="groak_lure",
  bloom=36.0,
  bloomtargets={ { name="spore", type="Layer",},},
  build="groak_lure",
  glowcolor="FF2D2DFF",
  group="trap_props",
  parallax={ { anim="damage", shadow=true,},},
  script="trap",
  script_args={ spore_type="damage", tier=1, trap_type="trap_spores",},
}
