-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="traveling_potion_box",
  clickable=true,
  gridsize={ { h=1, w=2,},},
  group="shop_props",
  parallax={
    { anim="1", dist=-0.12999999523163, shadow=true,},
    { anim="2", shadow=true,},
    { anim="3", dist=0.025000000372529, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.4,
  physicstype="smdec",
  placer=true,
}
