-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="traveling_potion_carpet",
  gridsize={ { h=4, level=-1, w=6,},},
  group="shop_props",
  layer="bg",
  onground=true,
  parallax={ { anim="1",},},
  parallax_use_baseanim_for_idle=true,
  sortorder=2,
}
