-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tree_upgrader",
  bank="tree",
  build="tree",
  clickable=true,
  gridsize={ { h=2, w=2,}, { h=4, level=1, w=4,},},
  group="shop_props",
  looping=true,
  parallax={
    { anim="front_leaves", dist=-1.05, shadow=true,},
    { anim="side_leaves", dist=-0.7, shadow=true,},
    { anim="branches", dist=-0.3, shadow=true,},
    { anim="trunk", shadow=true,},
    { anim="maple", dist=-0.3001, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="dec",
  randomstartframe=true,
  script="tree",
  silhouette=true,
}
