-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tundra_destructible_tree_tall",
  bloom=40.0,
  bloomtargets={ { name="megatreemon_parts_untex", type="Symbol",},},
  gridsize={ { h=2, w=2,},},
  group="tundra_props",
  parallax={
    { anim="1", dist=-0.2, shadow=true,},
    { anim="2", shadow=true,},
    { anim="3", dist=0.15000000596046, shadow=true,},
    { anim="4", dist=0.25,},
  },
  parallax_use_baseanim_for_idle=true,
  script="prop_destructible",
}
