-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tundra_grid_lichen",
  group="tundra_props",
  parallax={ { anim="lichen",},},
  randomflip=true,
  randomize=true,
  variations=3,
}
