-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="wooden_cart",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={
    { anim="front", dist=-0.4, shadow=true,},
    { anim="mid", dist=-0.3, shadow=true,},
    { anim="good", shadow=true,},
    { anim="back", dist=0.1, shadow=true,},
    { anim="back_wheel", dist=0.3, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.8,
  physicstype="smdec",
  placer=true,
  variations=3,
}
