-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_death_battoad",
  isfinal=true,
  prefab={ "fx_death_temp",},
  stategraphs={
    fx_death_temp={
      events={
        idle={ { eventtype="spawneffect", frame=1, param={ fxname="fx_death_temp_grnd",},},},
      },
    },
  },
}
