-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_floracrane",
  isfinal=true,
  prefab={ "floracrane",},
  stategraphs={
    sg_floracrane={
      sg_events={
        {
          eventtype="spawneffect",
          name="vfx-kick",
          param={ fxname="fx_floracrane_kick", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-spear",
          param={ fxname="fx_floracrane_spear", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-flurry",
          param={ fxname="fx_floracrane_flurry", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-spinning_bird_kick_loop",
          param={
            fxname="fx_floracrane_spinning_bird_kick_loop",
            inheritrotation=true,
            ischild=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-spinning_bird_kick_pst",
          param={
            fxname="fx_floracrane_spinning_bird_kick_pst",
            inheritrotation=true,
            ischild=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-dive",
          param={
            fxname="groak_slam_groundring",
            offx=2.2000000476837,
            offy=0.0,
            offz=0.0,
            scalex=1.2999999523163,
            scalez=1.25,
          },
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-dive",
          param={ impact_size=3, impact_type=1, offx=2.2200000286102, offz=0.0,},
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-beakpull",
          param={
            impact_size=1,
            impact_type=1,
            inheritrotation=true,
            offx=2.2000000476837,
            offz=0.0,
          },
        },
      },
    },
  },
}
