-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_heal_burst_lrg",
  isfinal=true,
  prefab={ "fx_heal_burst_lrg",},
  stategraphs={
    fx_heal_burst={
      events={
        idle={
          { eventtype="spawneffect", frame=1, param={ fxname="fx_heal_ribbon_front",},},
          { eventtype="spawneffect", frame=1, param={ fxname="fx_heal_ribbon_back",},},
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=80.0, particlefxname="heal_liquid_burst", stopatexitstate=true,},
          },
        },
      },
    },
    fx_heal_burst_lrg={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=80.0, particlefxname="heal_liquid_burst", stopatexitstate=true,},
          },
        },
      },
    },
    fx_heal_burst_med={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=80.0, particlefxname="heal_liquid_burst", stopatexitstate=true,},
          },
        },
      },
    },
    fx_heal_burst_sml={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=80.0, particlefxname="heal_liquid_burst", stopatexitstate=true,},
          },
        },
      },
    },
  },
}
