-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_hit_spikes",
  isfinal=true,
  prefab={ "fx_hit_spikes",},
  stategraphs={
    fx_hit_spikes={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=30.0, particlefxname="hit_spikes",},
          },
        },
      },
    },
  },
}
