-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_player_power",
  group="fx_player",
  isfinal=true,
  prefab="player_side",
  stategraphs={
    sg_player_hammer={
      events={ idle={  }, potion_refill={  },},
      sg_events={
        {
          eventtype="stopparticles",
          name="power_ready_off",
          param={ name="power_ready_on",},
        },
        {
          eventtype="spawnparticles",
          name="power_ready_on",
          param={
            followsymbol="weapon_back01",
            ischild=true,
            name="power_ready_on",
            particlefxname="fire_follow_v1",
          },
        },
      },
      state_events={ potion_refill={  },},
    },
    sg_player_polearm={
      sg_events={
        {
          eventtype="spawnparticles",
          name="power_ready_on",
          param={
            followsymbol="weapon_back01",
            ischild=true,
            name="power_ready_on",
            particlefxname="fire_follow_v1",
          },
        },
        {
          eventtype="stopparticles",
          name="power_ready_off",
          param={ name="power_ready_on",},
        },
      },
    },
  },
}
