-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_sporemon_projectile_juggernaut",
  isfinal=true,
  prefab={ "sporemon_projectile_juggernaut",},
  stategraphs={
    sg_sporemon_projectile={
      events={
        land_confuse={  },
        land_dmg={  },
        land_juggernaut={
          {
            eventtype="spawnimpactfx",
            frame=1,
            param={ impact_size=1, impact_type=1, offx=0, offz=0,},
          },
          {
            eventtype="spawneffect",
            frame=1,
            param={ fxname="hit_groundring_sporebomb_juggernaught",},
          },
        },
        thrown_confuse={  },
        thrown_dmg={  },
        thrown_juggernaut={
          {
            eventtype="spawnparticles",
            frame=0,
            param={
              duration=90.0,
              ischild=true,
              particlefxname="sporemon_sporebomb_trail_juggernaut",
            },
          },
        },
      },
    },
  },
}
