-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_swamp_gate_e",
  isfinal=true,
  prefab={ "bandiforest_gate_e",},
  sg_wildcard=true,
  stategraphs={
    ["*"]={
      events={
        idle={  },
        open={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              offx=1.5,
              offy=0.0,
              offz=0.0,
              particlefxname="forest_gate_fog_e",
              stopatexitstate=true,
            },
          },
        },
      },
      sg_events={  },
    },
  },
}
