-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_spores_shield",
  isfinal=true,
  prefab={ "fx_spores_shield_all",},
  stategraphs={
    fx_spores_shield_all={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=1,
            param={ fxname="fx_spores_shield_front", ischild=true,},
          },
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=90.0, particlefxname="spores_burst_shield", render_in_front=true,},
          },
        },
      },
    },
  },
}
