-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_treemon_projectile",
  isfinal=true,
  prefab={ "treemon_projectile",},
  stategraphs={
    sg_treemon_projectile={
      events={
        land={
          {
            eventtype="spawnimpactfx",
            frame=1,
            param={ impact_size=1, impact_type=1, offx=0, offz=0,},
          },
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=20.0, particlefxname="treemon_pinecone_burst",},
          },
        },
        thrown={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              duration=90.0,
              ischild=true,
              particlefxname="treemon_pinecone_trail",
              stopatexitstate=true,
            },
          },
        },
      },
    },
  },
}
