-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="power_drop_konjur",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "power_drop_konjur",},
  stategraphs={
    sg_konjur_reward_drop={
      sg_events={
        { eventtype="playsound", name="sfx-pop", param={ soundevent="konjur_blob_pop",},},
        {
          eventtype="playsound",
          name="sfx-burble",
          param={ soundevent="konjur_blob_appear_burble",},
        },
        {
          eventtype="playsound",
          name="sfx-spawn",
          param={ soundevent="konjur_blob_appear_energy",},
        },
      },
    },
  },
}
