-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_player_common",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "player_side",},
  sg_wildcard=true,
  stategraphs={
    ["*"]={
      events={
        cheer={  },
        death={
          { eventtype="playfoleysound", frame=13, param={ soundtag="Bodyfall",},},
          { eventtype="playfoleysound", frame=22, param={ soundtag="Hand",},},
          { eventtype="playfoleysound", frame=25, param={ soundtag="Hand",},},
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Player_whoosh", volume=41.0,},
          },
        },
        death_flop={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Player_death_flop_bounce",},
          },
          {
            eventtype="playsound",
            frame=7,
            param={ soundevent="Player_death_flop_bounce_bodyfall",},
          },
        },
        death_wave={
          { eventtype="playsound", frame=1, param={ soundevent="Player_swish_light",},},
          {
            eventtype="playsound",
            frame=3,
            param={ soundevent="Player_swish_light", volume=72.0,},
          },
          {
            eventtype="playsound",
            frame=5,
            param={ soundevent="Player_swish_light", volume=42.0,},
          },
          {
            eventtype="playsound",
            frame=7,
            param={ soundevent="Player_swish_light", volume=27.0,},
          },
        },
        eat={ { eventtype="playsound", frame=10, param={ soundevent="Player_eat",},},},
        heavy_attack={
          { eventtype="playsound", frame=10, param={ soundevent="Polearm_jump_atk",},},
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Player_whoosh", volume=51.0,},
          },
        },
        idle={  },
        knockdown={ { eventtype="playfoleysound", frame=12, param={ soundtag="Bodyfall",},},},
        knockdown_getup={ { eventtype="playfoleysound", frame=3, param={ soundtag="Hand",},},},
        knockdown_getup_pst={
          { eventtype="playfoleysound", frame=3, param={ soundtag="Footstep",},},
          { eventtype="playfoleysound", frame=5, param={ soundtag="Footstep",},},
        },
        knockdown_high_pst={ { eventtype="playfoleysound", frame=22, param={ soundtag="Bodyfall",},},},
        knockdown_pst={ { eventtype="playfoleysound", frame=12, param={ soundtag="Bodyfall",},},},
        konjur_accept={  },
        pickup={ { eventtype="playsound", frame=1, param={ soundevent="Player_grab",},},},
        potion={
          { eventtype="playsound", frame=45, param={ soundevent="Player_glass_break",},},
          {
            eventtype="playsound",
            frame=5,
            param={ name="player_potion", soundevent="Player_potion_drink", stopatexitstate=true,},
          },
        },
        potion_pre={ { eventtype="playsound", frame=3, param={ soundevent="Player_rummage",},},},
        potion_pre_cancel={ { eventtype="stopsound", frame=1, param={ name="player_potion",},},},
        potion_refill_pre={
          { eventtype="playsound", frame=13, param={ soundevent="Player_whoosh",},},
          { eventtype="playsound", frame=18, param={ soundevent="Player_potion_refill",},},
        },
        potion_refill_pst={ { eventtype="playsound", frame=12, param={ soundevent="Player_rummage",},},},
        powerup_upgrade={  },
        revivable_hit={ { eventtype="playfoleysound", frame=13, param={ soundtag="Bodyfall",},},},
        revivable_idle={
          { eventtype="playfoleysound", frame=1, param={ soundtag="Hand", volume=62.0,},},
        },
        revive_interact={
          {
            eventtype="playsound",
            frame=1,
            param={
              autostop=true,
              name="fx_heal_revive_LP",
              soundevent="fx_heal_revive_LP",
              stopatexitstate=true,
            },
          },
        },
        revived={
          { eventtype="playfoleysound", frame=4, param={ soundtag="Hand",},},
          { eventtype="playfoleysound", frame=30, param={ soundtag="Footstep",},},
          { eventtype="playfoleysound", frame=28, param={ soundtag="Hand",},},
        },
        roll_heavy={ { eventtype="playsound", frame=1, param={ soundevent="Player_hop",},},},
        roll_light={ { eventtype="playsound", frame=1, param={ soundevent="Player_slide",},},},
        roll_loop={ { eventtype="playsound", frame=1, param={ soundevent="Player_roll",},},},
        roll_pre={  },
        run_loop={
          { eventtype="playfoleysound", frame=21, param={ soundtag="Footstep",},},
          { eventtype="playfoleysound", frame=9, param={ soundtag="Footstep",},},
        },
        run_pre={ { eventtype="playfoleysound", frame=1, param={ soundtag="Footstep",},},},
        run_pst={ { eventtype="playsound", frame=1, param={ soundevent="Dirt_run_stop",},},},
        skill_bananapeel_eat={  },
        skill_buffnextattack={ { eventtype="playsound", frame=7, param={ soundevent="AAAA_default_event",},},},
        skill_cannon_butt={  },
        skill_parry={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Player_swish", volume=43.0,},
          },
        },
        skill_throwstone={  },
        spectating={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, soundevent="flying_machine_Ratchet_LP", stopatexitstate=true,},
          },
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="flying_machine", stopatexitstate=true,},
          },
          {
            eventtype="playsound",
            frame=33,
            param={ soundevent="flying_machine_claw_open",},
          },
          { eventtype="playfoleysound", frame=37, param={ soundtag="Bodyfall",},},
          {
            eventtype="playsound",
            frame=42,
            param={ soundevent="flying_machine_claw_closed",},
          },
        },
        spectating_pst={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="flying_machine", stopatexitstate=true,},
          },
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, soundevent="flying_machine_Ratchet_LP", stopatexitstate=true,},
          },
          {
            eventtype="playsound",
            frame=29,
            param={ soundevent="flying_machine_claw_open",},
          },
          { eventtype="playfoleysound", frame=38, param={ soundtag="Land",},},
          {
            eventtype="playsound",
            frame=35,
            param={ soundevent="flying_machine_claw_closed",},
          },
        },
        turn_pre={ { eventtype="playfoleysound", frame=2, param={ soundtag="Footstep",},},},
        turn_pre_run_pre={ { eventtype="playfoleysound", frame=2, param={ soundtag="Footstep",},},},
        turn_pst={ { eventtype="playfoleysound", frame=2, param={ soundtag="Footstep",},},},
      },
      sg_events={  },
    },
  },
}
