-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_skill_megatreemon_player",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "megatreemon_growth_root_player",},
  stategraphs={
    sg_megatreemon_growth_root_player={
      events={
        guard_loop={
          {
            eventtype="playsound",
            frame=1,
            param={ sound_max_count=3.0, soundevent="Skill_Megatreek_Defend_Whoosh",},
          },
          {
            eventtype="playsound",
            frame=10,
            param={ sound_max_count=3.0, soundevent="Skill_Megatreek_Defend_Whoosh",},
          },
        },
        guard_pre={
          {
            eventtype="playsound",
            frame=1,
            param={
              name="Defend_Warn",
              sound_max_count=1.0,
              soundevent="Skill_Megatreek_Defend_Warn",
              stopatexitstate=true,
            },
          },
          {
            eventtype="playsound",
            frame=24,
            param={ sound_max_count=1.0, soundevent="Skill_Megatreek_Defend_Spawn",},
          },
          { eventtype="stopsound", frame=24, param={ name="Defend_Warn",},},
        },
        poke={
          {
            eventtype="playsound",
            frame=2,
            param={ sound_max_count=1.0, soundevent="Skill_Megatreek_Spike",},
          },
          {
            eventtype="playsound",
            frame=1,
            param={
              name="Skill_Megatreek_Whoosh",
              sound_max_count=1.0,
              soundevent="Skill_Megatreek_Whoosh",
            },
          },
          { eventtype="stopsound", frame=4, param={ name="Skill_Megatreek_Whoosh",},},
        },
        poke_pre={
          {
            eventtype="playsound",
            frame=1,
            param={
              name="Skill_Megatreek_Warn",
              sound_max_count=10.0,
              soundevent="Skill_Megatreek_Warn",
            },
          },
        },
      },
    },
  },
}
