-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_npc_dojomaster",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "npc_dojo_master",},
  stategraphs={
    sg_npc={
      sg_events={
        {
          eventtype="playsound",
          name="sfx-foley_leather",
          param={ soundevent="Foley_leather",},
        },
      },
    },
  },
}
