-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_cabbageroll_norm_alt",
  group="sound_creature",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "cabbageroll",},
  stategraphs={
    sg_cabbageroll={
      events={
        angry={
          { eventtype="playsound", frame=6, param={ soundevent="cabbageroll_VO_pitched",},},
        },
        bite={  },
        bite_pre={
          {
            eventtype="playsound",
            frame=12,
            param={ sound_max_count=10.0, soundevent="cabbageroll_VO_pitched",},
          },
        },
        elite_roll={  },
        elite_roll_hold={  },
        elite_roll_pre={  },
        hit={  },
        idle={  },
        knockdown={  },
        knockdown_btm={  },
        knockdown_getup={  },
        knockdown_hit={  },
        knockdown_pre={  },
        roll={  },
        roll_pre={  },
        roll_pst={  },
        spawn_battlefield={  },
        taunt={  },
        walk_loop={  },
        whistle={  },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-whoosh_q",
          param={ soundevent="cabbageroll_whoosh", volume=35,},
        },
        {
          eventtype="playsound",
          name="sfx-whoosh",
          param={ soundevent="cabbageroll_whoosh",},
        },
        {
          eventtype="playsound",
          name="sfx-bodyfall",
          param={ soundevent="cabbageroll_bodyfall",},
        },
        {
          eventtype="playsound",
          name="sfx-twirl",
          param={ soundevent="cabbageroll_twirl",},
        },
        {
          eventtype="playsound",
          name="sfx-ground_hit",
          param={ soundevent="cabbageroll_ground_hit",},
        },
        {
          eventtype="playsound",
          name="sfx-slap",
          param={ soundevent="cabbagerolls_slap",},
        },
        {
          eventtype="playsound",
          name="sfx-gather",
          param={ soundevent="cabbageroll_gather",},
        },
        {
          eventtype="playsound",
          name="sfx-twirl_LP",
          param={ soundevent="cabbageroll_twirl_LP", stopatexitstate=true,},
        },
        {
          eventtype="playsound",
          name="sfx-whistle",
          param={
            name="cabbageroll_vo_hoot",
            sound_max_count=10.0,
            soundevent="cabbageroll_behaviour_3",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="sfx-bite",
          param={ sound_max_count=5.0, soundevent="cabbageroll_bite",},
        },
        {
          eventtype="playsound",
          name="sfx-behaviour2",
          param={
            autostop=true,
            name="cabbageroll_vo_tongueWaggle",
            param={ sound_max_count=10.0, soundevent="cabbageroll_behaviour_2",},
            sound_max_count=10.0,
            soundevent="cabbageroll_behaviour_2",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playfoleysound",
          name="sfx-foleysound",
          param={ soundtag="Footstep", volume=17.0,},
        },
        {
          eventtype="playsound",
          name="x-sfx-knock",
          param={ sound_max_count=10.0, soundevent="cabbageroll_knockdown",},
        },
        {
          eventtype="playsound",
          name="x-sfx-hit",
          param={ sound_max_count=10.0, soundevent="cabbageroll_hit",},
        },
      },
    },
  },
}
