-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="WIP_fx_death_gourdo",
  isfinal=true,
  prefab={ "death_gourdo_frnt",},
  stategraphs={
    death_gourdo_frnt={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=1,
            param={ fxname="death_gourdo_grnd", scalex=1.0, scalez=1.0,},
          },
        },
      },
    },
  },
}
