-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_up_stalactite",
  fade={ bottom=20.0, top=11.89,},
  group="swamp_props",
  parallax={ { anim="stalac",},},
  proptype=1.0,
  randomize=true,
  variations=4,
}
