-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_tree",
  fade={ bottom=-3.88, top=1.24,},
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="front", dist=-0.25,},
    { anim="mid_above", autosortlayer="above",},
    { anim="back_above", autosortlayer="above", dist=1.0,},
    {
      anim="back_below",
      autosortlayer="below",
      dist=1.0001000165939,
      underground=true,
    },
    {
      anim="mid_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
  },
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=4,
}
