-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_ul_fartree",
  fade={ bottom=-3.56, top=-0.25,},
  group="swamp_props",
  layer="auto",
  parallax={ { anim="tree",},},
  proptype=1,
  randomize=true,
  variations=4,
}
