-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bed_swamp_1",
  clickable=true,
  gridsize={ { h=3, w=3,},},
  group="town_decor",
  looping=true,
  parallax={
    { anim="leg_front", dist=-0.4, shadow=true,},
    { anim="frame_front", dist=-0.2, shadow=true,},
    { anim="frame_back", shadow=true,},
    { anim="leg_back", dist=0.3, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=2,
  physicstype="smdec",
  placer=true,
  randomstartframe=true,
}
