-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bulletin_board",
  clickable=true,
  gridsize={ { h=1, w=4,},},
  group="town_decor",
  parallax={
    { anim="front", dist=-0.2, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.2, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.8,
  physicstype="smdec",
  placer=true,
  variations=1,
}
