-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="destructible_wood_tall",
  gridsize={ { h=2, w=2,},},
  group="forest_props",
  parallax={
    { anim="1", dist=-0.2, shadow=true,},
    { anim="2", shadow=true,},
    { anim="3", dist=0.25, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  script="prop_destructible",
}
