-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_grid_megastump",
  bloom=40.0,
  bloomtargets={ { name="crystals", type="Symbol",},},
  gridsize={ { h=2, w=2,},},
  group="forest_props",
  parallax={
    { anim="front", dist=-0.3, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.4, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="smdec",
  variations=3,
}
