-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_owlshrub",
  fade={ bottom=-2.35, top=-0.59,},
  group="forest_props",
  parallax={ { anim="owlshrub",},},
  proptype=1,
  randomflip=true,
  randomize=true,
  variations=3,
}
