-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lamp_basic",
  bloom=60.0,
  bloomtargets={ { name="bloom", type="Symbol",}, { name="lamp", type="Layer",},},
  children={  },
  glowcolor="FFC900FF",
  gridsize={ { h=1, w=1,},},
  group="town_decor",
  looping=true,
  parallax={ { anim="1", dist=-0.0099999997764826, shadow=true,}, { anim="2", shadow=true,},},
  physicssize=0.3,
  physicstype="smdec",
  placer=true,
  randomstartframe=true,
}
