-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="legacy_gas_vent",
  bank="fx_upgrade_gas",
  bankfile="fx_upgrade_gas",
  bloom=30.0,
  build="fx_upgrade_gas",
  glowcolor="00FF1CFF",
  group="legacy_reference",
  hidemouseover=true,
  parallax={ { anim="1",}, { anim="2", dist=-0.001, onground=true,},},
}
