-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="plot_armorsmith",
  bank="plot",
  build="plot",
  gridsize={ { h=8, w=8,},},
  group="town_plots",
  parallax={
    { anim="one", dist=-3.2000000476837,},
    { anim="two", dist=-1.7000000476837,},
    { anim="three",},
    { anim="four", dist=2.0999999046326,},
    { anim="five", dist=3.0,},
  },
  parallax_use_baseanim_for_idle=true,
  script="plots",
  script_args={
    building_prefab="armorer_1",
    owner_prefab="npc_armorsmith",
    skins={ groups={  }, sets={  }, symbols={  },},
    spawn_flag="wf_town_has_armorsmith",
    upgrades={  },
  },
  variations=2,
}
