-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="shrub",
  brightness=-10.0,
  gridsize={ { h=2, w=2,},},
  group="forest_props",
  looping=true,
  parallax={ { anim="1", dist=-0.6,}, { anim="2", dist=-0.4,}, { anim="3", shadow=true,},},
  placer=true,
  randomstartframe=true,
  saturation=-10.0,
}
