-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_wall_new",
  brightness=-8.0,
  fade={ bottom=-2.94, top=1.42,},
  group="town_bg_props",
  hue=-7.0,
  layer="auto",
  parallax={
    { anim="rubble", dist=-0.10000000149012, shadow=true,},
    { anim="wall", shadow=true,},
    { anim="back", dist=0.40000000596046,},
  },
  parallax_use_baseanim_for_idle=true,
  proptype=1.0,
  saturation=9.0,
  variations=4,
}
