-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_fg_column",
  bloom=50.0,
  bloomtargets={ { name="cryst", type="Symbol",},},
  fade={ bottom=-4.62, top=5.0,},
  glowcolor="A81FFFFF",
  group="town_bg_props",
  looping=true,
  parallax={ { anim="column",},},
  proptype=1.0,
  randomstartframe=true,
  variations=2,
}
