-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="trap_spores_heal",
  bank="groak_lure",
  bloom=20.0,
  bloomtargets={ { name="spore", type="Layer",},},
  build="groak_lure",
  glowcolor="4CFF5BFF",
  group="trap_props",
  parallax={ { anim="healing", shadow=true,},},
  script="trap",
  script_args={ spore_type="heal", tier=1, trap_type="trap_spores",},
}
