-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tundra_spawner_plant2",
  bank="tundra_spawner_plant2",
  brightness=0,
  build="tundra_spawner_plant2",
  gridsize={ { h=2, w=2,},},
  group="tundra_props",
  hostspawn=true,
  hue=0,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="leaf1", dist=-0.20000000298023, shadow=true,},
    { anim="leaf2", shadow=true,},
    { anim="leaf3", dist=0.20000000298023, shadow=true,},
    { anim="leaf4", dist=0.34999999403954, shadow=true,},
  },
  randomstartframe=true,
  saturation=0,
  script="creaturespawner",
  script_args={ spawner_type="spawner_battlefield",},
}
