-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tundra_grid_rock_small",
  bank="tundra_grid_rock",
  build="tundra_grid_rock",
  group="tundra_props",
  parallax={ { anim="smallrock", shadow=true,},},
  physicssize=1.2,
  physicstype="obs",
  randomflip=true,
  variations=2,
}
