-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_trap_weed_spikes",
  group="sound_traps",
  isfinal=true,
  needSoundEmitter=true,
  prefab="trap_weed_spikes",
  stategraphs={
    sg_trap_spike={
      events={
        idle={  },
        idle_to_dormant={
          {
            eventtype="spawnparticles",
            frame=0,
            param={
              particlefxname="dust_spike_trap_dormant",
              render_in_front=true,
              stopatexitstate=true,
            },
          },
          { eventtype="playsound", frame=1, param={ soundevent="Trap_Weed_Spikes_disarm",},},
        },
      },
    },
  },
}
