-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_cabbagerolls2_elite_alt",
  group="sound_creature",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "cabbagerolls2_elite",},
  stategraphs={
    sg_cabbagerolls2={
      events={
        slam={ { eventtype="playsound", frame=1, param={ soundevent="cabbagerolls2_slam",},},},
        throw={ { eventtype="playsound", frame=1, param={ soundevent="cabbagerolls2_throw",},},},
      },
      sg_events={
        {
          eventtype="playsound",
          name="bodyfall",
          param={ soundevent="cabbageroll_bodyfall",},
        },
        {
          eventtype="playsound",
          name="sfx-hold",
          param={ soundevent="cabbagerolls2_hold", stopatexitstate=true,},
        },
        {
          eventtype="playfoleysound",
          name="footstep",
          param={ soundtag="Footstep", volume=21,},
        },
        {
          eventtype="playsound",
          name="sfx-ground_hit",
          param={ soundevent="cabbageroll_Elite_ground_hit",},
        },
        {
          eventtype="playsound",
          name="knockdown",
          param={ soundevent="cabbageroll_Elite_knockdown",},
        },
        {
          eventtype="playsound",
          name="vo_pitched",
          param={
            sound_max_count=10.0,
            soundevent="cabbageroll_VO_pitched",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="hit",
          param={ sound_max_count=5.0, soundevent="cabbageroll_Elite_hit",},
        },
        {
          eventtype="playsound",
          name="vo",
          param={ sound_max_count=10.0, soundevent="cabbageroll_Elite_VO", stopatexitstate=true,},
        },
      },
    },
  },
}
