-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_skilldrop",
  isfinal=true,
  needSoundEmitter=true,
  prefab={
    "skill_drop_generic_1p",
    "skill_drop_generic_2p",
    "skill_drop_generic_3p",
    "skill_drop_generic_4p",
  },
  stategraphs={
    sg_rotating_drop={
      events={
        idle={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="powerCrystal_idle_LP", stopatexitstate=true,},
          },
        },
        spawn={  },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-energy",
          param={
            sound_max_count=1.0,
            soundevent="powerCrystal_spawn_energy",
            stopatstateexit=true,
          },
        },
        {
          eventtype="playsound",
          name="sfx-materialize",
          param={ sound_max_count=1.0, soundevent="powerCrystal_spawn_impact",},
        },
        {
          eventtype="playsound",
          name="sfx-rumble",
          param={ sound_max_count=1.0, soundevent="powerCrystal_rumble",},
        },
        {
          eventtype="playsound",
          name="sfx-shatter",
          param={ sound_max_count=1.0, soundevent="powerCrystal_shatter_crystal",},
        },
        {
          eventtype="playsound",
          name="sfx-shatter_tail",
          param={ sound_max_count=1.0, soundevent="powerCrystal_shatter_tail",},
        },
        {
          eventtype="playsound",
          name="sfx-warp",
          param={ sound_max_count=1.0, soundevent="powerCrystal_spawn_crystallize",},
        },
      },
    },
  },
}
