-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_beets_elite",
  isfinal=true,
  prefab={ "beets_elite",},
  stategraphs={
    sg_beets={
      sg_events={
        {
          eventtype="spawneffect",
          name="vfx-headslam",
          param={ fxname="beets_headslam", inheritrotation=true,},
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-headslam_elite_impact1",
          param={ impact_size=1, impact_type=1, offx=1.0199999809265, offz=0.0,},
        },
        {
          eventtype="spawneffect",
          name="vfx-headslam_elite",
          param={
            fxname="beets_headslam_elite",
            inheritrotation=true,
            ischild=true,
            offx=0.0,
            offy=0.0,
            offz=0.0,
          },
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-headslam_elite_impact2",
          param={ impact_size=3, impact_type=1, offx=1.0, offz=0.0,},
        },
      },
    },
  },
}
