-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_slowpoke",
  isfinal=true,
  prefab={ "slowpoke",},
  stategraphs={
    sg_slowpoke={
      events={ body_slam={  },},
      sg_events={
        {
          eventtype="spawnimpactfx",
          name="vfx-body_slam_impact",
          param={ impact_size=3, impact_type=1, offx=0.0, offz=-0.20000000298023,},
        },
        {
          eventtype="spawneffect",
          name="vfx-body_slam_groundring",
          param={
            fxname="slowpoke_slam_groundring",
            offx=0.25,
            offy=0.0,
            offz=0.0,
            scalex=2.5,
            scalez=2.4000000953674,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-spawn_pst",
          param={
            fxname="slowpoke_slam_groundring",
            offx=0.0,
            offy=0.0,
            offz=0.0,
            scalex=2.5999999046326,
            scalez=2.5,
          },
        },
        {
          eventtype="spawnimpactfx",
          name="vfx-spawn_pst",
          param={ impact_size=3, impact_type=1, offx=0.0, offz=-0.20000000298023,},
        },
        {
          eventtype="spawnparticles",
          name="vfx-spawn_pst",
          param={ duration=90.0, particlefxname="impact_swamp_thatcher_rings",},
        },
        {
          eventtype="spawnparticles",
          name="vfx-body_slam_groundring",
          param={ duration=90.0, particlefxname="impact_swamp_thatcher_rings",},
        },
      },
    },
  },
}
