-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_konjur_heart",
  isfinal=true,
  needSoundEmitter=true,
  prefab={
    "soul_drop_boss_megatreemon",
    "soul_drop_boss_bandicoot",
    "soul_drop_boss_owlitzer",
    "soul_drop_boss_thatcher",
  },
  stategraphs={
    sg_rotating_drop={
      events={
        idle={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="powerCrystal_idle_LP", stopatexitstate=true,},
          },
        },
        spawn={  },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-crystallize",
          param={ sound_max_count=1.0, soundevent="powerCrystal_spawn_crystallize",},
        },
        {
          eventtype="playsound",
          name="sfx-energy",
          param={ sound_max_count=1.0, soundevent="powerCrystal_spawn_energy",},
        },
        {
          eventtype="playsound",
          name="sfx-ping",
          param={ sound_max_count=1.0, soundevent="powerCrystal_spawn_impact",},
        },
        {
          eventtype="playsound",
          name="sfx-rattle",
          param={ sound_max_count=2.0, soundevent="powerCrystal_rattle",},
        },
        {
          eventtype="playsound",
          name="sfx-rumble",
          param={ sound_max_count=1.0, soundevent="powerCrystal_rumble",},
        },
        {
          eventtype="playsound",
          name="sfx-shatter_crystal",
          param={ sound_max_count=1.0, soundevent="powerCrystal_shatter_crystal",},
        },
        {
          eventtype="playsound",
          name="sfx-shatter_tail",
          param={ sound_max_count=1.0, soundevent="powerCrystal_shatter_tail",},
        },
        {
          eventtype="playsound",
          name="sfx-absorb",
          param={ soundevent="konjurHeart_absorb",},
        },
      },
    },
  },
}
