-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_ear_color_7",
  cosmetic_data={
    color={ 0.10810811072588, 0.0, 0.26254826784134,},
    colorgroup="EAR_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
