-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_tan_skin_tone_1",
  cosmetic_data={
    color={ 0.072222222222222, 0.6, 0.6,},
    colorgroup="SKIN_TONE",
    color_species="canine",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
