-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_masu1_hair_color_1",
  cosmetic_data={
    color={ 0.091666666666667, 0.58, 0.81,},
    colorgroup="HAIR_COLOR",
    color_species="canine",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
