-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="flat_none_shirt_mer_1",
  cosmetic_data={
    bodypart_group="SHIRT",
    bodypart_species="mer",
    colorgroup="NONE",
    multi_species=true,
    symboltags={  },
    uitags={ "blank",},
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
