-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_teal_hair_color_1",
  cosmetic_data={
    color={ 0.21111111111111, 0.2, 1.28,},
    colorgroup="HAIR_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
