-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_petal_eyes_1",
  cosmetic_data={
    bodypart_group="EYES",
    bodypart_species="mer",
    build="player_eyes_mer_petal",
    colorgroup="EYE_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
