-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_sage_skin_tone_1",
  cosmetic_data={
    color={ 0.25277777777778, 0.38, 0.6,},
    colorgroup="SKIN_TONE",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
