-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_undies_color_2",
  cosmetic_data={
    color={ 0.69444444444444, 0.35, 0.6,},
    colorgroup="UNDIES_COLOR",
    color_species="mer",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
