-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_scarlet_hair_color_1",
  cosmetic_data={
    color={ 0.98611111111111, 0.79, 0.64,},
    colorgroup="HAIR_COLOR",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
