-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_green_skin_tone_1",
  cosmetic_data={
    color={ 0.38333333333333, 0.43, 0.66,},
    colorgroup="SKIN_TONE",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
