-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_2",
  cosmetic_data={
    color={ 0.02316602319479, 0.38996139168739, 0.69884169101715,},
    colorgroup="EAR_COLOR",
    color_species="ogre",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
