-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_brown_hair_color_1",
  cosmetic_data={
    color={ 0.030555555555556, 0.37, 0.7,},
    colorgroup="HAIR_COLOR",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
