-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="smear_skin_color_1",
  cosmetic_data={ color={ 0.5, 0.4, 0.65,}, colorgroup="SMEAR_SKIN_COLOR", color_species="mer",},
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
