-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="torso_canine_torso_1",
  cosmetic_data={
    bodypart_group="TORSO",
    bodypart_species="canine",
    build="player_torso_solid",
    colorgroup="SKIN_TONE",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
