-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_flat_triangle_nose_1",
  cosmetic_data={
    bodypart_group="NOSE",
    bodypart_species="canine",
    build="player_nose_canine_triangle",
    colorgroup="NOSE_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
