-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_think",
  cosmetic_data={
    anim="emote_think",
    emote_species="none",
    icon_path="images/icons_ftf/item_temp.tex",
    name_key="emote_think",
  },
  group="PLAYER_EMOTE",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
