-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="eyev_dye_2",
  cosmetic_data={
    armour_set="eyev",
    build_override="armor_eyev_dye_2",
    dye_number=2,
    title_key="BOOMER",
  },
  group="EQUIPMENT_DYE",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
