-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_shirt_color_1",
  cosmetic_data={
    color={ 0.083333333333333, 0.03, 0.96,},
    colorgroup="SHIRT_COLOR",
    color_species="mer",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
