-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_orange_skin_tone_1",
  cosmetic_data={
    color={ 0.055555555555556, 0.67, 0.78,},
    color_species="mer",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
