-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_pointed_quiff_hair_1",
  cosmetic_data={
    bodypart_group="HAIR",
    bodypart_species="ogre",
    build="player_hair_ogre_pointed_quiff",
    colorgroup="HAIR_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
