-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_apathetic_mouth_1",
  cosmetic_data={
    bodypart_group="MOUTH",
    bodypart_species="ogre",
    build="player_mouth_ogre_apathetic",
    colorgroup="MOUTH_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
