-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_9",
  cosmetic_data={
    color={ 0.39768341183662, 0.4285714328289, 0.30888032913208,},
    color_species="ogre",
    colorgroup="EAR_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
