-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_acorn_eyes",
  cosmetic_data={
    bodypart_group="EYES",
    bodypart_species="ogre",
    build="player_eyes_ogre_acorn",
    colorgroup="EYE_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
