-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="solid_arms_ogre_1",
  cosmetic_data={
    bodypart_group="ARMS",
    bodypart_species="ogre",
    build="player_arms_solid",
    colorgroup="SKIN_TONE",
    multi_species=true,
    symboltags={  },
    uitags={ "blank",},
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
