-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="thin_brow_canine_1",
  cosmetic_data={
    bodypart_group="BROW",
    bodypart_species="canine",
    build="player_brow_thin",
    colorgroup="HAIR_COLOR",
    multi_species=true,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
