return {
  room_loot={ { x=8.5, z=-0.5,}, { x=1.5, z=1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-14.94, z=8.65,},
    { script_args={ creature_spawner_type="perimeter",}, x=7.84, z=17.08,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.43, z=-10.57,},
    { script_args={ creature_spawner_type="perimeter",}, x=-24.25, z=-8.09,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0, z=-14.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.0, z=-13.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.0, z=10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.0, z=4.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=-14.0,},
  },
  spawner_propdestructible={
    { x=-16.0, z=-9.0,},
    { x=6.0, z=9.0,},
    { x=10.0, z=-13.0,},
    { x=18.0, z=-13.0,},
    { x=11.0, z=-2.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=18.0, z=-9.0,},
    { script_args={  }, z=9.0,},
    { script_args={  }, x=15.0, z=2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_acid",},}, x=-4.5, z=1.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=-9.5, z=-5.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=-9.5, z=-0.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=5.5, z=1.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=0.5, z=0.5,},
  },
}