return {
  room_loot={ { x=5.5, z=0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=16.57, z=14.83,},
    { script_args={ creature_spawner_type="perimeter",}, x=24.14, z=-11.37,},
    { script_args={ creature_spawner_type="perimeter",}, x=-15.86, z=17.39,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.16, z=8.43,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=-6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=16.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=13.0,},
  },
  spawner_propdestructible={
    { x=-10.0, z=9.0,},
    { x=19.0, z=-5.0,},
    { x=-1.0, z=13.0,},
    { x=-5.0, z=-12.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=12.0, z=9.0,},
    { script_args={  }, x=1.0, z=9.0,},
    { script_args={  }, x=-1.0, z=-9.0,},
    { script_args={  }, x=19.0, z=2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_acid",},}, x=-5.5, z=-0.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=9.5, z=-0.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=4.5, z=2.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=4.5, z=-2.5,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=-0.5, z=-0.5,},
  },
}