return {
  canopy_shadow={
    { x=-32.02, z=2.12,},
    { x=-30.15, z=-5.74,},
    { x=29.14, z=6.05,},
    { x=-8.89, z=-27.76,},
    { x=4.35, z=-22.99,},
    { x=-4.0, z=24.26,},
    { x=3.21, z=25.35,},
  },
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.67, z=-1.69,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-10.65, z=-4.72,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=3.17, z=-8.23,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=10.95, z=0.37,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-5.61, z=5.6,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=5.5, z=-6.61,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=9.96, z=0.27,},
  },
  room_loot={ { x=4.5, z=1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=9.89, z=14.6,},
    { script_args={ creature_spawner_type="perimeter",}, x=-10.19, z=14.61,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.46, z=6.12,},
    { script_args={ creature_spawner_type="perimeter",}, x=27.4, z=7.33,},
    { script_args={ creature_spawner_type="miniboss",}, x=-0.12, z=-1.55,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.05, z=-9.56,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.0, z=-11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=7.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=4.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.35, z=-8.13,},
    { script_args={ creature_spawner_type="miniboss",}, x=6.61, z=-1.42,},
  },
  spawner_propdestructible={
    { x=-9.0, z=5.0,},
    { x=13.0, z=5.0,},
    { x=-17.0, z=8.0,},
    { x=-5.0, z=10.0,},
    { x=-1.0, z=3.0,},
    { x=16.0, z=-5.0,},
    { x=5.0, z=-9.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "left",},}, x=13.0, z=-9.0,},
    {
      script_args={ spawn_areas={ "perimeter", "right", "battlefield",},},
      x=10.0,
      z=8.0,
    },
    {
      script_args={ spawn_areas={ "perimeter", "right", "battlefield",},},
      x=12.0,
      z=-5.0,
    },
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=-8.0, z=-9.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=17.0, z=7.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-5.0, z=-10.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=9.0, z=-5.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=3.0, z=-2.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=13.0, z=9.0,},
  },
}