return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.06, z=-7.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=13.22, z=-1.74,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=5.45, z=5.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.28, z=-2.18,},
  },
  room_loot={ { x=-0.5, z=-0.5,}, { x=5.5, z=5.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=8.68, z=19.23,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.29, z=18.87,},
    { script_args={ creature_spawner_type="perimeter",}, x=22.52, z=6.68,},
    { script_args={ creature_spawner_type="perimeter",}, x=-23.15, z=7.59,},
    { script_args={ creature_spawner_type="battlefield",}, x=-15.0, z=-8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=-11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.0, z=-5.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0,},
  },
  spawner_propdestructible={
    { x=-6.0, z=5.0,},
    { x=-9.0, z=-7.0,},
    { x=2.0, z=-6.0,},
    { x=12.0, z=-10.0,},
    { x=6.0, z=-15.0,},
    { x=5.0, z=8.0,},
    { x=-12.0, z=8.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=1.0, z=-1.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=9.0, z=-1.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=12.0, z=-3.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=-1.0, z=-8.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=9.0, z=-8.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=4.0, z=4.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=9.0, z=8.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=-1.0, z=8.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=6.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-5.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, z=4.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-2.0, z=-5.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-15.0, z=-12.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=13.0, z=9.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-16.0, z=6.0,},
    {
      script_args={ trap_types={ "trap_exploding", "trap_spike",},},
      x=-11.0,
      z=-11.0,
    },
  },
}