return {
  room_loot={ { x=3.5, z=0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=16.57, z=14.83,},
    { script_args={ creature_spawner_type="perimeter",}, x=24.14, z=-11.37,},
    { script_args={ creature_spawner_type="perimeter",}, x=-15.86, z=17.39,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.16, z=8.43,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=-6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=16.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.0, z=11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=13.0,},
  },
  spawner_propdestructible={ { x=-10.0, z=9.0,}, { x=9.0, z=-7.0,}, { x=6.0, z=1.0,}, { x=-5.0, z=-12.0,},},
  spawner_stationaryenemy={
    { script_args={  }, x=3.0, z=-4.0,},
    { script_args={  }, x=1.0, z=9.0,},
    { script_args={  }, x=-3.0, z=-8.0,},
    { script_args={  }, x=15.0, z=2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-9.0, z=-8.0,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=21.0, z=1.0,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=11.0, z=8.0,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=19.0, z=-5.0,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=1.0,},
  },
}