return {
  room_loot={ { x=-4.5, z=0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=12.04, z=6.46,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.46, z=7.53,},
    { script_args={ creature_spawner_type="perimeter",}, x=-15.63, z=14.94,},
    { script_args={ creature_spawner_type="perimeter",}, x=-28.08, z=8.97,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.81, z=5.05,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.83, z=-12.95,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.81, z=-10.9,},
    { script_args={ creature_spawner_type="battlefield",}, x=-16.94, z=-9.25,},
    { script_args={ creature_spawner_type="battlefield",}, x=-16.86, z=4.42,},
    { script_args={ creature_spawner_type="battlefield",}, x=-19.09, z=-7.44,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.0, z=2.36,},
    { script_args={ creature_spawner_type="battlefield",}, x=3.31, z=4.77,},
  },
  spawner_propdestructible={
    { x=-12.0, z=7.0,},
    { x=-15.0, z=-5.0,},
    { z=-7.0,},
    { x=11.0,},
    { x=18.0, z=-9.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=2.0, z=-2.0,},
    { script_args={  }, x=-2.0, z=7.0,},
    { script_args={  }, x=-7.0, z=-4.0,},
    { script_args={  }, x=15.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-6.5, z=5.5,},
    { script_args={ trap_types={ "trap_spores",},}, x=-10.5, z=-4.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-1.5, z=1.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=4.5, z=-10.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=6.5, z=-1.5,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=3.5, z=-4.5,},
  },
}