return {
  room_loot={ { x=0.5, z=-1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.54, z=-2.49,},
    { script_args={ creature_spawner_type="perimeter",}, x=19.65, z=14.18,},
    { script_args={ creature_spawner_type="perimeter",}, x=-23.48, z=14.93,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.83, z=14.13,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.11, z=7.68,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.0, z=4.7,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.11, z=-6.67,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.24, z=-5.16,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.05, z=-7.05,},
    { script_args={ creature_spawner_type="battlefield",}, x=-10.99, z=5.4,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.08, z=7.12,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.14, z=-8.98,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.21, z=5.93,},
  },
  spawner_propdestructible={
    { x=-16.0, z=-1.0,},
    { x=-18.0, z=9.0,},
    { x=-6.0, z=-10.0,},
    { x=6.0, z=-10.0,},
    { x=12.0, z=9.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=1.0, z=2.0,},
    { script_args={  }, x=12.0, z=-3.0,},
    { script_args={  }, x=-5.0, z=-7.0,},
    { script_args={  }, x=15.0, z=6.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-7.5, z=7.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=0.5, z=-7.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=4.5, z=-1.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=17.5, z=0.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=4.5, z=10.5,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=-0.5, z=-1.5,},
  },
}