-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="battlemaster",
  cosmetic_data={ title_key="BATTLEMASTER",},
  group="PLAYER_TITLE",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=false,
  rarity="LEGENDARY",
  
}
