-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="bust_tank_shirt_ogre_1",
  cosmetic_data={
    bodypart_group="SHIRT",
    bodypart_species="ogre",
    build="player_shirt_bust_tank",
    colorgroup="SHIRT_COLOR",
    multi_species=true,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
