-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_blue_eye_color_1",
  cosmetic_data={
    color={ 0.50555555555556, 0.45, 0.9,},
    colorgroup="EYE_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
