-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_flax_hair_color_1",
  cosmetic_data={
    color={ 0.13055555555556, 0.37, 1.1,},
    colorgroup="HAIR_COLOR",
    color_species="canine",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
