-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_marine_skin_tone_1",
  cosmetic_data={
    color={ 0.54166666666667, 0.41, 0.5,},
    color_species="canine",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
