-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_mouse_ears",
  cosmetic_data={
    bodypart_group="EARS",
    bodypart_species="canine",
    build="player_ears_canine_mouse",
    colorgroup="EAR_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
