-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_paleyellow_eye_color_1",
  cosmetic_data={
    color={ 0.13888888888889, 0.15, 1.1,},
    colorgroup="EYE_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
