-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_cannon_twirl",
  cosmetic_data={
    anim="emote_cannon_twirl",
    emote_species="none",
    icon_path="images/icons_ftf/FTF_UI_emote_icon_cannon_1.tex",
    name_key="emote_cannon_twirl",
  },
  group="PLAYER_EMOTE",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
