-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_amphibee_bubble_kiss",
  cosmetic_data={
    anim="emote_amphibee_bubble_kiss",
    emote_species="mer",
    icon_path="images/icons_ftf/emote_amphibee_bubble_kiss.tex",
    name_key="emote_amphibee_bubble_kiss",
  },
  group="PLAYER_EMOTE",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
