-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="fashionista",
  cosmetic_data={ title_key="FASHIONISTA",},
  group="PLAYER_TITLE",
  hidden=false,
  locked=false,
  mastery="none",
  purchased=false,
  rarity="COMMON",
  
}
