-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_none_ornament_1",
  cosmetic_data={
    bodypart_group="ORNAMENT",
    bodypart_species="mer",
    multi_species=false,
    symboltags={  },
    uitags={ "blank",},
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
