-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_green_ornament_color_1",
  cosmetic_data={
    color={ 0.38333333333333, 0.27, 0.96,},
    colorgroup="ORNAMENT_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
