-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_antennae_brow_1",
  cosmetic_data={
    bodypart_group="BROW",
    bodypart_species="mer",
    build="player_brow_mer_antennae",
    colorgroup="HAIR_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
