-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_fern_skin_tone_1",
  cosmetic_data={
    color={ 0.39444444444444, 0.33, 0.69,},
    color_species="mer",
    colorgroup="SKIN_TONE",
    is_default_color=true,
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
