-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_olive_skin_tone_1",
  cosmetic_data={
    color={ 0.23611111111111, 0.4, 0.43,},
    colorgroup="SKIN_TONE",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
