-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_blue_ornament_color_1",
  cosmetic_data={
    color={ 0.49444444444444, 0.32, 0.93,},
    colorgroup="ORNAMENT_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
