-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_apple_hair_color_1",
  cosmetic_data={
    color={ 0.25555555555556, 0.27, 1.05,},
    colorgroup="HAIR_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
