-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_strawberryblonde_hair_color_1",
  cosmetic_data={
    color={ 0.088888888888889, 0.52, 0.98,},
    colorgroup="HAIR_COLOR",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
