-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_5",
  cosmetic_data={
    color={ 0.5675675868988, 0.35135135054588, 0.66409265995026,},
    colorgroup="NOSE_COLOR",
    color_species="ogre",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
