-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_13",
  cosmetic_data={
    color={ 0.50193047523499, 0.30501931905746, 0.90347492694855,},
    colorgroup="EAR_COLOR",
    color_species="ogre",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
