-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_blackcherry_hair_color_1",
  cosmetic_data={
    color={ 0.92222222222222, 0.62, 0.2,},
    colorgroup="HAIR_COLOR",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
