-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_manbun_hair_1",
  cosmetic_data={
    bodypart_group="HAIR",
    bodypart_species="ogre",
    build="player_hair_ogre_manbun",
    colorgroup="HAIR_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
