-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_1",
  cosmetic_data={
    color={ 0.91388888888889, 0.39, 0.95,},
    colorgroup="EAR_COLOR",
    color_species="ogre",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
