-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="smear_weapon_color_1",
  cosmetic_data={ color={ 0.5, 0.5, 1.0,}, colorgroup="SMEAR_WEAPON_COLOR",},
  group="PLAYER_COLOR",
  hidden=false,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
  
}
