-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="wrap_undies_ogre_1",
  cosmetic_data={
    bodypart_group="UNDIES",
    bodypart_species="ogre",
    build="player_undies_wrap",
    colorgroup="UNDIES_COLOR",
    multi_species=true,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
