-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_eyev_frnt",
  addcolor="21212100",
  anim="death_air_sml",
  bank="fx_monster_death_untex",
  brightness=47.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=109.0,
  randomflip=true,
  saturation=-82.0,
  scalex=1.2000000476837,
  scaley=1.2000000476837,
  shadow=true,
  soundevent="eyev_death",
}
