-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_chain_arc_sml",
  anim="electric_chain_arc_small_",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  multcolor="FFFFFFE6",
  noflip=true,
  scalex=2.0,
  scaley=2.0,
  soundevent="Power_Electric_Arc",
  target_tint="FF640000",
  variations=2,
}
