-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_dust_ground_center_stalactite",
  anim="center",
  bank="fx_dust",
  brightness=-25.0,
  build="fx_dust",
  group="fx_dust",
  multcolor="75FFED80",
  noflip=true,
  scalex=1.0,
  scaley=1.0,
}
