-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_ground_target_white",
  anim="idle",
  bank="fx_ground_target",
  bloom=50.0,
  brightness=-25.0,
  build="fx_ground_target",
  clip_at_worldedge=true,
  glowcolor="FF0000FF",
  group="fx_warning",
  layer="bg",
  looping=true,
  onground=true,
  randomstartframe=true,
  scalex=1.25,
  scaley=1.5,
  sortorder=2,
}
