-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_fade_atk_front_basic",
  anim="fade_atk_front",
  bank="fx_player_bank_hammer_swipe_basic",
  bloom=100.0,
  build="fx_player_bank_hammer_swipe_basic",
  finaloffset=1,
  group="fx_hammer_basic",
  multcolor="999999FF",
}
