-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_low_health_ring",
  anim="loop_small",
  bloom=82.0,
  looping=true,
  multcolor="FFFFFF66",
  onground=true,
  sortorder=-3,
}
