-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_atk2_basic",
  anim="atk2",
  bank="fx_player_bank_polearm_basic",
  bloom=100.0,
  build="fx_player_bank_polearm_basic",
  finaloffset=1,
  group="fx_polearm_basic",
  multcolor="B39999FF",
}
