-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_swarmy_acid_burst",
  anim="swarmy_acid_burst",
  bank="fx_acid",
  bloom=50.0,
  build="fx_acid",
  glowcolor="D0D641FF",
  group="fx_acid",
  multcolor="BFFFBFFF",
  noflip=true,
  saturation=-13.0,
  scalex=1.0,
  scaley=1.0,
}
