-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_spores_shield_front",
  anim="spore_1",
  bank="fx_dust",
  bloom=100.0,
  build="fx_dust",
  group="fx_spores",
  multcolor="00B3FFA6",
  randomflip=true,
  scalex=3.0,
  scaley=3.0,
}
