-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_block_partial",
  anim="defend_partial_2",
  bank="fx_hits_block",
  bloom=100.0,
  build="fx_hits_block",
  glowcolor="E6BA2BFF",
  group="hits_fx",
  multcolor="FFFF80FF",
}
