-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="player_ground_hit_mud",
  anim="1",
  bank="fx_hit_ground_projected",
  build="fx_hit_ground_projected",
  finaloffset=7,
  glowcolor="8E10B1FF",
  group="player_ground_hits",
  onground=true,
  sortorder=-1,
}
