-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_cannon_shotgun_focus",
  anim="shotgun_focus",
  bank="fx_player_projectile_cannon",
  build="fx_player_projectile_cannon",
  group="projectiles",
  looping=true,
  randomstartframe=true,
  scalex=1.0,
  scaley=1.0,
}
