-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_shotput_idle",
  anim="idle",
  bank="fx_player_projectile_shotput",
  build="fx_player_projectile_shotput",
  glowcolor="FFFFFFFF",
  group="projectile_shotput",
  scalex=1.0,
  scaley=1.0,
}
