-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_teen_mothball_hit",
  anim="break_2",
  bank="fx_minion_projectile",
  bloom=30.0,
  build="fx_minion_projectile",
  glowcolor="1E00FFFF",
  group="projectiles",
  randomflip=true,
  scalex=2.0,
  scaley=1.25,
  soundevent="minion1_land",
}
