-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="test_blank_colour",
  anim="idle",
  bank="test_fx",
  build="colour_test_untex",
  looping=true,
  randomstartframe=true,
  timelines={
    add_blue={  },
    add_green={  },
    add_red={  },
    multiply_alpha={  },
    multiply_blue={  },
    multiply_green={  },
    multiply_red={  },
    shift_brightness={  },
    shift_hue={  },
    shift_saturation={  },
  },
}
