-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="trap_zucco_warning",
  anim="blinking",
  bank="fx_trap_explosion",
  bloom=80.0,
  build="fx_trap_explosion",
  clip_at_worldedge=true,
  glowcolor="00C223FF",
  group="bombs_traps",
  hue=-180.0,
  looping=true,
  multcolor="FFFFFF59",
  onground=true,
  sortorder=-1,
}
