-- Generated by AnimTester and loaded by animtest_autogen.lua
return {
  __displayName="walk",
  animdata={
    { anim="walk_pre", bank="bandicoot", flip=false,},
    { anim="walk_loop", bank="bandicoot", flip=true,},
    { anim="", bank="bandicoot",},
    { anim="walk_to_run", bank="bandicoot", flip=false,},
    { anim="run_loop", bank="bandicoot", flip=true,},
    { anim="walk_pst", bank="bandicoot", flip=true,},
    { anim="run_pst", bank="bandicoot", flip=true,},
    { anim="behavior4", bank="bandicoot", flip=true,},
  },
  bankfile="bandicoot",
  build="bandicoot",
  group="bandicoot",
  loopanim=true,
}
