-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_yammo_stem",
  build="drops_yammo",
  droptype="curve",
  group="drops_yammo",
  loot_id="yammo_stem",
  symbol="yammo_stem",
}
