-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_megatreemon_wood",
  build="drops_megatreemon",
  droptype="solid",
  group="drops_megatreemon",
  loot_id="arak_eye",
  symbol="megatreemon_wood",
}
