-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_bonejaw_skull",
  build="drops_bonejaw",
  droptype="solid",
  group="drops_bonejaw",
  loot_id="bonejaw_skull",
  pos="front",
  symbol="bonejaw_skull",
}
