-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_mossquito",
  anim_events={
    mossquito_bank={
      flinch_pst={ events={ { frame=1, name="sfx-hit",},},},
      hit_back_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      hit_pst={ events={ { frame=1, name="sfx-hit",},},},
      knockdown_pre={
        events={
          { frame=4, name="sfx-hit",},
          { frame=16, name="sfx-footstep",},
          { frame=16, name="sfx-knockdown",},
        },
      },
      pierce={ events={ { frame=5, name="sfx-pierce",},},},
      pierce2_elite={ done=true, events={ { frame=1, name="sfx-pierce_elite_2",},},},
      pierce_elite={ done=true, events={ { frame=1, name="sfx-pierce_elite",},},},
      pierce_hold={ done=true, events={ { frame=1, name="sfx-pierce_hold",},},},
      spawn={ events={ { frame=4, name="sfx-hit",},},},
      spray_hold={ events={ { frame=0, name="sfx-spray_hold",},},},
    },
  },
  prefab={ { prefab="mossquito",}, { prefab="mossquito_elite",},},
}
