-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_spawner",
  gridsize={ { h=2, w=2,},},
  group="swamp_props",
  hostspawn=true,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="a", dist=-1.0, shadow=true,},
    { anim="b", dist=-0.80000001192093, shadow=true,},
    { anim="c", dist=-0.40000000596046, shadow=true,},
    { anim="d", shadow=true,},
    { anim="e", dist=0.40000000596046, shadow=true,},
  },
  randomstartframe=true,
  script="creaturespawner",
  script_args={ spawner_type="spawner_battlefield",},
}
