-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_up_canopyslime",
  bank="bandiforest_up_canopy",
  build="bandiforest_up_canopy",
  group="swamp_props",
  parallax={ { anim="canopyslime",},},
  proptype=1.0,
  variations=4,
}
