-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_slime",
  brightness=0,
  gridsize={ { h=1, w=1,},},
  group="swamp_props",
  hue=0,
  multcolor="FFF7FFFF",
  parallax={
    { anim="front3", dist=-0.60000002384186,},
    { anim="blob3", dist=-0.30000001192093, shadow=true,},
    { anim="mid3", shadow=true,},
    { anim="tendril3", dist=0.40000000596046,},
    { anim="back3", dist=0.60000002384186, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  saturation=-12.0,
}
