-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="dojo_1",
  clickable=true,
  gridsize={ { h=3, w=3,},},
  group="town_buildings",
  looping=true,
  nonpersist=true,
  parallax={
    { anim="awning", dist=-0.5, shadow=true,},
    { anim="base", dist=-0.20000000298023, shadow=true,},
    { anim="target", shadow=true,},
    { anim="roof", dist=0.20000000298023, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="dec",
  randomstartframe=true,
  script="buildings",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
  sound=true,
}
