-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="dye2",
  bank="tanning_rack",
  build="tanning_rack",
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={ { anim="front_dye", dist=-0.5, shadow=true,}, { anim="back_dye", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
}
