-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_bg_reed",
  fade={ bottom=-1, top=3,},
  group="forest_props",
  layer="auto",
  parallax={ { anim="reedfront",}, { anim="reedback", dist=0.3,},},
  parallax_use_baseanim_for_idle=true,
  proptype=1,
  randomize=true,
  variations=4,
}
