-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forest_fg_fern",
  fade={ bottom=-3.09, top=0.32,},
  group="forest_props",
  parallax={ { anim="fernfront",}, { anim="fernback", dist=0.3,},},
  proptype=1,
  variations=5,
}
