-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lightspot_smlbubbly",
  bank="fx_lightspot_mouseover",
  build="fx_lightspot_mouseover",
  group="light_group",
  proptype=2.0,
  script="lightspot",
  script_args={
    animate=true,
    max_rotation=5.6040000915527,
    max_translation=0.11299999803305,
    rot_speed=0.31999999284744,
    rotation=0.86000001430511,
    scale=8.0030002593994,
    shimmer=true,
    shimmer_speed=0.69499999284744,
    shimmer_strength=0.0099999997764826,
    trans_speed=0.52399998903275,
  },
  variations=4,
}
