-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="plot_armorsmith_decor",
  bank="plot_armorer",
  build="plot_armorer",
  group="town_plots",
  parallax={
    { anim="1", dist=-0.89999997615814, shadow=true,},
    { anim="2", shadow=true,},
    { anim="3", dist=0.10000000149012, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=4,
  physicstype="obs",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
}
