-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="powerupgrader_pipe",
  gridsize={ { h=2, w=2,},},
  group="shop_props",
  looping=true,
  parallax={ { anim="1", dist=-0.2,}, { anim="2", shadow=true,}, { anim="3", dist=0.2,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="dec",
}
