-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_ruins",
  bank="town_grid_ruins",
  build="town_grid_ruins",
  group="town_bg_props",
  parallax={ { anim="ruins", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  variations=4,
}
