-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_bg_mount",
  group="town_bg_props",
  layer="backdrop",
  parallax={ { anim="mount",},},
  proptype=1,
  variations=2,
}
