-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_fg_grass",
  fade={ bottom=-4.12, top=-0.42,},
  group="town_bg_props",
  parallax={
    { anim="grassf", autosortlayer="above", dist=-0.60000002384186,},
    { anim="grassb",},
  },
  proptype=1.0,
  variations=3,
}
