-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_statue",
  bank="town_grid_statue",
  bloom=68.0,
  bloomtargets={ { name="light", type="Layer",},},
  build="town_grid_statue",
  glowcolor="8243D0FF",
  gridsize={ { h=2, w=2,},},
  group="town_bg_props",
  parallax={ { anim="statue", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  variations=4,
}
