-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="trap_zucco",
  bloom=24.0,
  bloomtargets={ { name="bomb", type="Symbol",},},
  glowcolor="00D451FF",
  group="trap_props",
  looping=true,
  networked=1,
  parallax={ { anim="trap", shadow=true,},},
  script="trap",
  script_args={ tier=1, trap_type="trap_zucco",},
}
