-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="tree_hangings_diag2",
  bank="tree_hangings",
  bankfile="tree_hangings",
  bloom=62.0,
  bloomtargets={ { name="light_bloom", type="Symbol",},},
  build="tree_hangings",
  glowcolor="FFA844FF",
  gridsize={ { h=1, level=2, w=1,},},
  group="town_decor",
  hue=32.0,
  looping=true,
  parallax={
    { anim="light1", dist=-1.8, xoffset=1.7, yoffset=0.5,},
    { anim="light3", dist=-1.3, xoffset=1.2, yoffset=0.3,},
    { anim="light3", dist=-0.8, xoffset=0.8, yoffset=0.1,},
    { anim="light2", dist=-0.5, xoffset=0.4, yoffset=0.03,},
    { anim="light3",},
    { anim="light2", dist=0.3, xoffset=-0.5, yoffset=0.08,},
    { anim="light3", dist=0.9, xoffset=-0.9, yoffset=0.2,},
  },
  randomstartframe=true,
}
