return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-9.05, z=2.12,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.06, z=-7.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=9.27, z=-3.23,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.18, z=5.13,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-14.69, z=-6.28,},
  },
  room_loot={ { x=-1.5, z=2.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.74, z=6.5,},
    { script_args={ creature_spawner_type="perimeter",}, x=8.52, z=18.15,},
    { script_args={ creature_spawner_type="perimeter",}, x=0.27, z=18.09,},
    { script_args={ creature_spawner_type="perimeter",}, x=16.91, z=14.83,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.45, z=6.83,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.64, z=3.79,},
    { script_args={ creature_spawner_type="battlefield",}, x=2.9, z=7.66,},
    { script_args={ creature_spawner_type="battlefield",}, x=-3.81, z=8.88,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.05, z=3.94,},
    {
      script_args={ creature_spawner_type="battlefield", spawn_areas={ "center",},},
      x=3.8,
      z=2.6,
    },
    { script_args={ creature_spawner_type="battlefield",}, x=5.65, z=-3.56,},
    { script_args={ creature_spawner_type="battlefield",}, x=-4.84, z=2.3,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.89, z=-0.02,},
  },
  spawner_propdestructible={
    { x=-21.0, z=2.0,},
    { x=-17.0,},
    { x=-19.0, z=14.0,},
    { x=12.0, z=14.0,},
    { x=15.0, z=7.0,},
    { x=8.0, z=2.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=5.0, z=7.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=6.0, z=-1.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=-3.0, z=-4.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=10.0, z=10.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=1.0, z=1.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=-11.0, z=-1.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=9.5, z=-3.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-12.5, z=-10.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-6.5, z=8.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-10.5, z=3.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-9.5, z=14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-6.5, z=14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-9.5, z=-10.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=3.5,
      z=18.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-12.5,
      z=18.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 1,}, trap_types={ "trap_windtotem",},},
      x=-6.5,
      z=-15.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=9.5, z=-10.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=12.5, z=-10.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=14.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=16.5,
      z=10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-16.5, z=-6.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-20.5, z=-2.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=16.5, z=-6.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-6.5, z=-3.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-0.5, z=-5.5,},
  },
}