return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-0.79, z=-2.12,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=5.85, z=-5.92,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=7.45, z=0.3,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-1.92, z=2.05,},
  },
  room_loot={ { x=0.5, z=-1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=7.61, z=18.5,},
    { script_args={ creature_spawner_type="perimeter",}, x=-8.85, z=18.72,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.79, z=-9.88,},
    { script_args={ creature_spawner_type="perimeter",}, x=22.41, z=6.56,},
    { script_args={ creature_spawner_type="battlefield",}, x=-10.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=4.54, z=-11.94,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.99, z=-8.34,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=-9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.0, z=-14.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.0, z=6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=3.37, z=7.33,},
    { script_args={ creature_spawner_type="battlefield",}, x=-0.11, z=7.32,},
    { script_args={ creature_spawner_type="battlefield",}, x=2.0, z=6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.0, z=6.0,},
  },
  spawner_propdestructible={
    { x=-14.0, z=-6.0,},
    { x=-9.0, z=-11.0,},
    { x=-2.0, z=-12.0,},
    { x=8.0, z=-11.0,},
    { x=14.0, z=-8.0,},
    { x=6.0, z=6.0,},
    { x=-6.0, z=9.0,},
    { x=-8.0, z=5.0,},
    { x=-9.0, z=-4.0,},
    { x=2.0, z=-4.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=10.0, z=2.0,},
    { script_args={ spawn_areas={ "perimeter", "right",},}, x=15.0, z=3.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=-1.0, z=-9.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=8.0, z=9.0,},
    { script_args={ spawn_areas={ "perimeter", "right",},}, x=14.0, z=-4.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=6.0, z=-6.0,},
    { script_args={ spawn_areas={ "top", "perimeter",},}, x=-4.0, z=4.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=1.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=8.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-6.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, z=4.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-4.0, z=-7.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=13.0, z=9.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-16.0, z=7.0,},
  },
}