return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.95, z=-3.47,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.06, z=-7.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=7.35, z=-5.19,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=4.62, z=2.13,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.82, z=-1.91,},
  },
  room_loot={ { x=-0.5, z=-1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.76, z=0.47,},
    { script_args={ creature_spawner_type="perimeter",}, x=3.5, z=18.86,},
    { script_args={ creature_spawner_type="perimeter",}, x=-9.23, z=18.76,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.81, z=7.43,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.0, z=12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-10.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.0, z=5.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0, z=3.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-8.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.0, z=6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=4.0,},
  },
  spawner_propdestructible={
    { x=-6.0, z=-11.0,},
    { x=-11.0, z=-7.0,},
    { x=-7.0, z=-5.0,},
    { x=1.0, z=-9.0,},
    { x=-5.0, z=4.0,},
    { x=4.0, z=5.0,},
    { x=5.0, z=-5.0,},
    { x=12.0, z=-9.0,},
    { x=16.0, z=-2.0,},
    { x=3.0, z=11.0,},
    { x=-5.0, z=8.0,},
    { x=-16.0, z=3.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "top", "perimeter",},}, x=9.0, z=9.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=13.0, z=1.0,},
    { script_args={ spawn_areas={ "perimeter", "right",},}, x=12.0, z=-5.0,},
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=-2.0, z=-9.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},},},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=6.0, z=2.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=-1.0, z=8.0,},
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=5.0, z=-10.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=6.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-5.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, z=4.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-2.0, z=-5.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=9.0, z=3.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-9.0, z=4.0,},
  },
}