return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.36, z=-11.42,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=4.25, z=-6.82,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.14, z=-1.51,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.21, z=4.64,},
  },
  room_loot={ { x=0.5, z=-0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="battlefield",}, x=11.97, z=-0.61,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=7.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=10.0, z=10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.96, z=-7.29,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.79, z=-8.49,},
    { script_args={ creature_spawner_type="battlefield",}, x=4.06, z=3.23,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.69, z=1.11,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=4.0,},
    { script_args={ creature_spawner_type="battlefield",}, z=-5.0,},
    { script_args={ creature_spawner_type="perimeter",}, x=22.68, z=1.41,},
    { script_args={ creature_spawner_type="perimeter",}, x=8.04, z=18.89,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.95, z=18.89,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.76, z=7.04,},
  },
  spawner_propdestructible={
    { x=-7.0, z=-8.0,},
    { x=-11.0, z=-10.0,},
    { x=-15.0, z=2.0,},
    { x=-9.0, z=-4.0,},
    { x=3.0, z=-6.0,},
    { x=-10.0, z=8.0,},
    { x=7.0, z=9.0,},
    { x=14.0, z=2.0,},
    { x=8.0, z=-9.0,},
    { x=-6.0, z=3.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=-3.0, z=3.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=3.0, z=1.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=8.0, z=2.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=9.0, z=-5.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=12.0, z=6.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=2.0, z=9.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, z=-10.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=1.0, z=-3.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=6.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-5.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, z=4.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-2.0, z=-5.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-15.0, z=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=13.0, z=9.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-16.0, z=7.0,},
  },
}