return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-9.72, z=-4.7,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=19.64, z=3.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=4.25, z=-6.82,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=0.26, z=1.46,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=7.35, z=8.48,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=19.74, z=-8.55,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=8.0939998626709,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=-22.46,
      z=-0.28,
    },
  },
  room_loot={ { x=12.5, z=-1.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="battlefield",}, x=21.42, z=0.11,},
    { script_args={ creature_spawner_type="battlefield",}, x=-15.4, z=-5.61,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=-1.39,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.4, z=0.44,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.85, z=11.87,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.82, z=10.13,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.33, z=-5.52,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.34, z=-3.92,},
    { script_args={ creature_spawner_type="battlefield",}, x=0.4, z=-6.75,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.05, z=-10.99,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.06, z=-5.16,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.38, z=2.25,},
    { script_args={ creature_spawner_type="perimeter",}, x=22.62, z=16.96,},
    { script_args={ creature_spawner_type="perimeter",}, x=-27.3, z=9.12,},
    { script_args={ creature_spawner_type="perimeter",}, x=29.31, z=12.72,},
    { script_args={ creature_spawner_type="perimeter",}, x=36.82, z=-5.37,},
  },
  spawner_propdestructible={
    { x=32.0, z=2.0,},
    { z=4.0,},
    { x=-27.0, z=-8.0,},
    { x=21.0, z=12.0,},
    { x=16.0,},
    { x=23.0, z=-11.0,},
    { x=-25.0, z=4.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=23.0, z=7.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=19.0, z=1.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=11.0, z=-5.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=-9.0, z=3.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=4.0, z=7.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=5.0, z=-11.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=26.0, z=-11.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_thorns",},}, x=-10.5, z=-8.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-9.5,
      z=8.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=1.5,
      z=16.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-17.5, z=-8.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-18.5, z=4.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 1,}, trap_types={ "trap_windtotem",},},
      x=-12.5,
      z=-13.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-15.5,
      z=4.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-20.5, z=-8.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-4.5, z=-1.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=6.5, z=1.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=5.5, z=-5.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=15.5, z=-9.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-17.5, z=-1.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-7.5, z=-8.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-4.5, z=-8.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-0.5, z=-12.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=2.5, z=-12.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=7.5, z=-16.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=24.5, z=-16.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-0.5,
      z=8.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=3.5,
      z=12.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-12.5,
      z=4.5,
    },
  },
}