return {
  canopy_shadow={
    { x=-32.02, z=2.12,},
    { x=-30.15, z=-5.74,},
    { x=29.14, z=6.05,},
    { x=-8.89, z=-27.76,},
    { x=4.35, z=-22.99,},
    { x=-4.0, z=24.26,},
    { x=3.21, z=25.35,},
  },
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-6.73, z=1.15,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-10.65, z=-4.72,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=3.17, z=-8.23,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=10.95, z=0.37,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-4.85, z=9.7,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=5.5, z=-6.61,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=9.96, z=0.27,},
  },
  room_loot={ { x=-1.5, z=3.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=5.93, z=18.39,},
    { script_args={ creature_spawner_type="perimeter",}, x=15.19, z=10.07,},
    { script_args={ creature_spawner_type="battlefield",}, x=-4.7, z=-1.35,},
    { script_args={ creature_spawner_type="perimeter",}, x=18.82, z=10.32,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.65, z=6.32,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.85, z=6.61,},
    { script_args={ creature_spawner_type="battlefield",}, x=2.72, z=6.68,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.36, z=-2.65,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.38, z=-4.46,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.0, z=5.13,},
    { script_args={ creature_spawner_type="battlefield",}, x=3.63, z=8.7,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.62, z=-5.6,},
  },
  spawner_propdestructible={
    { x=-20.0, z=-4.0,},
    { x=-4.0, z=9.0,},
    { x=-16.0, z=11.0,},
    { x=9.0, z=9.0,},
    { x=-5.0, z=-6.0,},
    { x=15.0, z=1.0,},
    { x=-21.0, z=11.0,},
  },
  spawner_stationaryenemy={
    {
      script_args={ spawn_areas={ "perimeter", "right", "battlefield",},},
      x=18.0,
      z=-5.0,
    },
    {
      script_args={ spawn_areas={ "perimeter", "right", "battlefield",},},
      x=13.0,
      z=5.0,
    },
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=-8.0, z=-5.0,},
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=3.0, z=-5.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=-1.0, z=10.0,},
  },
  spawner_trap={
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=1.5,
      z=19.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=-19.5, z=3.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-18.5,
      z=19.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 1,}, trap_types={ "trap_windtotem",},},
      x=-17.5,
      z=-11.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=8.5, z=-15.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-8.5, z=4.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=1.5, z=-0.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 1,}, trap_types={ "trap_windtotem",},},
      x=0.5,
      z=-10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-0.5, z=-6.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-19.5,
      z=15.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-16.5,
      z=15.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=2.5,
      z=15.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-0.5,
      z=15.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-19.5, z=-6.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-16.5, z=-6.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=2.5, z=-6.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=22.5,
      z=6.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=22.5,
      z=-6.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-26.5,
      z=10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-27.5, z=-3.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-3.5, z=4.5,},
  },
}