return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=3.16, z=17.7,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=4.97, z=-6.79,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=10.1, z=-0.06,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.18, z=22.61,},
    {
      script_args={
        animate=false,
        intensity=0.91699999570847,
        light_color="595145FF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=10,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=-3.4,
      z=-35.01,
    },
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=6.8520002365112,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=2.18,
      z=-24.81,
    },
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="595145FF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=6.8520002365112,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=8.5,
      z=-35.59,
    },
  },
  room_loot={ { x=0.5, z=21.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-11.2, z=-23.42,},
    { script_args={ creature_spawner_type="perimeter",}, x=15.18, z=-23.57,},
    { script_args={ creature_spawner_type="perimeter",}, x=11.31, z=-19.44,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.42, z=-19.45,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.3, z=-29.3,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.63, z=-39.87,},
    { script_args={ creature_spawner_type="battlefield",}, x=-2.2, z=-25.39,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.93, z=-37.74,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.03, z=-24.27,},
    { script_args={ creature_spawner_type="battlefield",}, x=-2.78, z=-38.87,},
    { script_args={ creature_spawner_type="battlefield",}, x=10.52, z=-38.77,},
  },
  spawner_propdestructible={
    { x=-8.0, z=-40.0,},
    { x=5.0, z=17.0,},
    { z=-30.0,},
    { x=-1.0, z=-20.0,},
    { x=7.0, z=-40.0,},
    { x=8.0, z=-25.0,},
    { x=-8.0, z=26.0,},
    { x=-2.0, z=10.0,},
    { x=8.0, z=25.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=4.0, z=23.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=-5.0, z=-24.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=2.0, z=-12.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=3.0, z=-40.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=4.0, z=10.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=-6.0, z=19.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=12.0, z=-28.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=5.0, z=-25.0,},
  },
  spawner_trap={
    {
      place_anywhere=true,
      script_args={ trap_directions={ 2,}, trap_types={ "trap_windtotem",},},
      x=11.5,
      z=-3.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 0,}, trap_types={ "trap_windtotem",},},
      x=-7.5,
      z=2.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-10.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-7.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_directions={ 0,}, trap_types={ "trap_windtotem",},},
      x=-7.5,
      z=-10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-7.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-4.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-1.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-4.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-1.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=-1.5, z=-33.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=6.5, z=-33.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-5.0, z=-29.0,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-13.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-13.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=1.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=1.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=4.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=4.5,
    },
  },
}