return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-10.72, z=-4.19,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-1.37, z=-12.25,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=6.7839999198914,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=2,
      x=2.97,
      z=-4.97,
    },
    { script_args={ light_color="4D453FFF",}, variation=1, x=12.32, z=-6.38,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=17.22, z=-12.02,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=4.22, z=-31.26,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-0.4, z=-37.11,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-8.35, z=11.19,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=5.1970000267029,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=-3.17,
      z=16.2,
    },
    { script_args={ light_color="4D453FFF",}, variation=2, x=16.93, z=14.11,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=11.94, z=9.38,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=3.05, z=14.68,},
  },
  room_loot={ { x=3.5, z=10.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-7.06, z=24.64,},
    { script_args={ creature_spawner_type="perimeter",}, x=20.78, z=24.63,},
    { script_args={ creature_spawner_type="perimeter",}, x=13.42, z=24.8,},
    { script_args={ creature_spawner_type="perimeter",}, x=-15.5, z=24.61,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.0, z=7.72,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.89, z=9.53,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.73, z=14.12,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.79, z=15.82,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.58, z=16.28,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.87, z=8.45,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.07, z=6.98,},
  },
  spawner_propdestructible={
    { x=13.0, z=17.0,},
    { x=2.0, z=-37.0,},
    { x=-8.0, z=5.0,},
    { x=7.0, z=-31.0,},
    { x=-17.0, z=16.0,},
    { x=4.0, z=-15.0,},
    { x=21.0, z=18.0,},
    { x=17.0, z=10.0,},
    { x=-5.0, z=-27.0,},
    { x=4.0, z=2.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=17.0, z=16.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=-13.0, z=17.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, z=-4.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=6.0, z=-36.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=5.0, z=-27.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=-2.0, z=15.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=4.0, z=-4.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=-1.0, z=-25.0,},
  },
  spawner_trap={
    {
      place_anywhere=true,
      script_args={ trap_directions={ 2,}, trap_types={ "trap_windtotem",},},
      x=11.5,
      z=-5.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=4.5, z=-40.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=7.5, z=-40.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=1.5, z=-40.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 0,}, trap_types={ "trap_windtotem",},},
      x=-7.5,
      z=-15.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=-3.5, z=-33.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=0.5, z=8.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-13.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=8.5, z=10.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=0.5, z=-29.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-4.5, z=-40.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=0.5, z=-12.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-16.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-10.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-4.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-3.5,
      z=-7.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-3.5,
      z=-4.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-10.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-13.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-1.5,
      z=-40.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-3.5,
      z=-16.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=7.5,
      z=-7.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-21.5, z=-17.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-24.5, z=-17.5,},
  },
}