return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.29, z=-4.71,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.06, z=-7.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=7.35, z=-5.19,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=4.62, z=2.13,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.82, z=-1.91,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=22.85, z=-1.27,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=6.9190001487732,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=10.31,
      z=2.53,
    },
  },
  room_loot={ { x=-0.5, z=0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=19.5, z=10.44,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.34, z=10.45,},
    { script_args={ creature_spawner_type="perimeter",}, x=-2.02, z=14.05,},
    { script_args={ creature_spawner_type="perimeter",}, x=6.23, z=13.88,},
    { script_args={ creature_spawner_type="battlefield",}, x=-3.01, z=-1.47,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.13, z=-9.47,},
    { script_args={ creature_spawner_type="battlefield",}, x=-3.42, z=8.05,},
    { script_args={ creature_spawner_type="battlefield",}, x=2.67, z=2.23,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.01, z=-7.83,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.2, z=5.05,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.86, z=-5.82,},
    { script_args={ creature_spawner_type="battlefield",}, x=-2.73, z=9.07,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.92, z=4.9,},
  },
  spawner_propdestructible={
    { x=-13.0, z=-4.0,},
    { x=25.0, z=2.0,},
    { x=1.0, z=9.0,},
    { x=13.0, z=-5.0,},
    { x=21.0, z=-2.0,},
    { x=9.0, z=9.0,},
    { x=-12.0, z=10.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "top", "perimeter",},}, x=12.0, z=5.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=17.0, z=1.0,},
    { script_args={ spawn_areas={ "perimeter", "right",},}, x=8.0, z=-8.0,},
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=-3.0, z=4.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=2.0, z=-2.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=4.0, z=10.0,},
    { script_args={ spawn_areas={ "battlefield", "bottom",},}, x=22.0, z=-5.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_thorns",},}, x=-7.5, z=-14.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-8.5,
      z=14.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, z=-8.0,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=11.5,
      z=14.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=7.5, z=-0.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-10.5, z=-14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=12.5, z=-14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=15.5, z=-14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=18.5, z=-14.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-7.5, z=2.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=9.5, z=-14.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=26.5, z=-10.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=23.5, z=-10.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-14.5, z=-10.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=14.5,
      z=10.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=26.5,
      z=6.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-4.5, z=-14.5,},
  },
}