return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-4.2, z=-3.81,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=4.97, z=-6.79,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=10.1, z=-0.06,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.21, z=4.64,},
  },
  room_loot={ { x=-0.5, z=-0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-12.38, z=18.79,},
    { script_args={ creature_spawner_type="perimeter",}, x=9.98, z=18.52,},
    { script_args={ creature_spawner_type="perimeter",}, x=22.92, z=3.18,},
    { script_args={ creature_spawner_type="perimeter",}, x=-23.23, z=-11.67,},
    { script_args={ creature_spawner_type="battlefield",}, x=4.0, z=-14.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.0, z=10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.35, z=-11.88,},
    { script_args={ creature_spawner_type="battlefield",}, x=1.0, z=-2.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=3.0, z=-4.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=1.0, z=-6.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-5.0,},
  },
  spawner_propdestructible={
    { x=-6.0, z=-7.0,},
    { x=-14.0, z=-5.0,},
    { x=-12.0, z=6.0,},
    { x=3.0, z=-9.0,},
    { x=14.0, z=-9.0,},
    { x=14.0,},
    { x=12.0, z=5.0,},
    { x=9.0, z=9.0,},
    { x=-8.0, z=9.0,},
    { x=-4.0, z=3.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=3.0, z=-1.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=3.0, z=-6.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=11.0, z=-1.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=8.0, z=-8.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=9.0, z=5.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=-4.0, z=9.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=2.0, z=7.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=5.0, z=3.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=6.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-5.0, z=-1.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-1.0, z=7.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-2.0, z=-5.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-11.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-10.0, z=-8.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=5.0, z=7.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-8.0, z=5.0,},
  },
}