return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-11.38, z=-1.25,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.06, z=-7.49,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=7.35, z=-5.19,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=10.95, z=0.37,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-2.21, z=4.64,},
  },
  room_loot={ { x=2.5, z=0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.74, z=6.5,},
    { script_args={ creature_spawner_type="perimeter",}, x=5.27, z=19.19,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.61, z=18.81,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.62, z=-11.35,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=-13.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=7.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.0, z=-5.0,},
    {
      script_args={ creature_spawner_type="battlefield", spawn_areas={ "center",},},
      x=-1.0,
    },
    { script_args={ creature_spawner_type="battlefield",}, x=7.0, z=-4.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=10.0, z=-15.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.0, z=-8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-8.79, z=-14.87,},
  },
  spawner_propdestructible={
    { x=-4.0, z=3.0,},
    { x=-10.0, z=-11.0,},
    { x=-15.0, z=-7.0,},
    { x=-10.0, z=11.0,},
    { x=-3.0, z=10.0,},
    { x=8.0, z=10.0,},
    { x=13.0, z=4.0,},
    { x=11.0, z=-11.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=1.0, z=-2.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=5.0, z=-3.0,},
    { script_args={ spawn_areas={ "battlefield", "center",},}, x=3.0, z=3.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=8.0, z=-8.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=5.0, z=9.0,},
    { script_args={ spawn_areas={ "battlefield", "right",},}, x=13.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=-2.0, z=-9.0,},
    { script_args={ spawn_areas={ "perimeter", "top",},}, x=-1.0, z=14.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spike",},}, x=6.0, z=3.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, x=-6.0, z=-4.0,},
    { script_args={ trap_types={ "trap_exploding", "trap_spike",},}, z=4.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=1.0, z=-8.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=-10.0, z=2.0,},
    { script_args={ trap_types={ "trap_exploding",},}, x=12.0, z=9.0,},
    { script_ags={ trap_types={ "trap_exploding",},}, x=-16.0, z=7.0,},
  },
}