return {
  room_loot={ { x=0.5, z=-0.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=12.88, z=15.15,},
    { script_args={ creature_spawner_type="perimeter",}, x=23.39, z=-5.48,},
    { script_args={ creature_spawner_type="perimeter",}, x=-15.78, z=15.96,},
    { script_args={ creature_spawner_type="perimeter",}, x=-28.08, z=8.97,},
    { script_args={ creature_spawner_type="battlefield",}, x=-10.25, z=9.51,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-13.55, z=-10.14,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.38, z=8.18,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=6.0, z=9.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=11.0,},
    { script_args={ creature_spawner_type="miniboss",}, x=1.9, z=4.12,},
  },
  spawner_propdestructible={
    { x=-18.0, z=9.0,},
    { x=5.0, z=-9.0,},
    { x=10.0, z=-10.0,},
    { x=-9.0, z=-13.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=14.0, z=-8.0,},
    { script_args={  }, z=11.0,},
    { script_args={  }, z=-11.0,},
    { script_args={  }, x=14.0, z=6.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores",},}, x=-7.5, z=4.5,},
    { script_args={ trap_types={ "trap_spores",},}, x=-8.5, z=-7.5,},
    { script_args={ trap_types={ "trap_spores",},}, x=11.5, z=-2.5,},
    { script_args={ trap_types={ "trap_spores",},}, x=7.5, z=8.5,},
    { script_args={ trap_types={ "trap_spores",},}, x=4.5, z=-1.5,},
  },
}