return {
  room_loot={ { x=0.5, z=-2.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-14.26, z=11.79,},
    { script_args={ creature_spawner_type="perimeter",}, x=15.1, z=12.37,},
    { script_args={ creature_spawner_type="perimeter",}, x=19.01, z=-6.97,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.0, z=-15.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.0, z=-11.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=15.0, z=-8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.0, z=-15.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=10.0, z=8.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.0, z=-15.0,},
  },
  spawner_propdestructible={
    { x=-12.0, z=4.0,},
    { x=-14.0, z=-10.0,},
    { x=-1.0, z=-14.0,},
    { x=13.0, z=5.0,},
    { z=3.0,},
    { x=-5.0, z=-2.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=-9.0, z=-14.0,},
    { script_args={  }, x=-5.0, z=4.0,},
    { script_args={  }, x=10.0, z=-14.0,},
    { script_args={  }, x=15.0, z=2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores",},}, x=1.0, z=-9.0,},
    { script_args={ trap_types={ "trap_spores",},}, x=-10.0, z=-8.0,},
    { script_args={ trap_types={ "trap_spores",},}, x=3.0, z=8.0,},
    { script_args={ trap_types={ "trap_spores",},}, x=12.0, z=-4.0,},
    { script_args={ trap_types={ "trap_spores",},}, x=7.0, z=3.0,},
    { script_args={ trap_types={ "trap_stalactite",},}, z=-1.0,},
  },
}