-- Generated by tools/imgui_upgrader/build_enums.lua

local ImGuiSortDirection_None       = 0
local ImGuiSortDirection_Ascending  = 1
local ImGuiSortDirection_Descending = 2

imgui.SortDirection = {
	None       = ImGuiSortDirection_None,
	Ascending  = ImGuiSortDirection_Ascending,  -- Ascending = 0->9, A->Z etc.
	Descending = ImGuiSortDirection_Descending, -- Descending = 9->0, Z->A etc.
}
