-- Generated by tools/imgui_upgrader/build_enums.lua

local ImGuiMouseButton_Left   = 0
local ImGuiMouseButton_Right  = 1
local ImGuiMouseButton_Middle = 2
local ImGuiMouseButton_COUNT  = 5

imgui.MouseButton = {
	Left   = ImGuiMouseButton_Left,
	Right  = ImGuiMouseButton_Right,
	Middle = ImGuiMouseButton_Middle,
	COUNT  = ImGuiMouseButton_COUNT,
}
