-- Generated by tools/imgui_upgrader/build_enums.lua

local ImGuiCond_None         = 0
local ImGuiCond_Always       = 1 -- 1 << 0
local ImGuiCond_Once         = 2 -- 1 << 1
local ImGuiCond_FirstUseEver = 4 -- 1 << 2
local ImGuiCond_Appearing    = 8 -- 1 << 3

imgui.Cond = {
	None         = ImGuiCond_None,         -- No condition (always set the variable), same as _Always
	Always       = ImGuiCond_Always,       -- No condition (always set the variable), same as _None
	Once         = ImGuiCond_Once,         -- Set the variable once per runtime session (only the first call will succeed)
	FirstUseEver = ImGuiCond_FirstUseEver, -- Set the variable if the object/window has no persistently saved data (no entry in .ini file)
	Appearing    = ImGuiCond_Appearing,    -- Set the variable if the object/window is appearing after being hidden/inactive (or the first time)
}
