-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_bandicoot",
  anim_events={
    bandicoot_bank={
      bite={ events={ { frame=14, name="vfx-bite",},},},
      clone={
        events={ { frame=29, name="vfx-clone",}, { frame=86, name="vfx-clone_burst",},},
      },
      death={ events={ { frame=140, name="vfx-impact",},},},
      peek_a_boo={ events={ { frame=26, name="vfx-peek_a_boo",},},},
      peek_a_boo_pre={ events={ { frame=0, name="vfx-peek_a_boo_pre",},},},
      peek_a_boo_pst={ events={ { frame=0, name="vfx-peek_a_boo_pst",},},},
      rage_bite={ events={ { frame=1, name="vfx-rage_bite",},},},
      rage_bite_pre={ events={ { frame=0, name="vfx-rage_bite_pre",},},},
      rage_transition={
        events={
          { frame=29, name="vfx-rage_transition_swipe2",},
          { frame=13, name="vfx-rage_transition_swipe1",},
        },
      },
      swipe={ events={ { frame=3, name="vfx-swipe",},},},
      swipe2={ events={ { frame=7, name="vfx-swipe2",},},},
      swipe_to_tail_sweep={ events={ { frame=5, name="vfx-swipe_to_tail_sweep",},},},
      tailspin={ events={ { frame=12, name="vfx-tailspin",},},},
      tailwhip={ events={ { frame=4, name="vfx-tailwhip",},},},
    },
  },
  prefab={ { prefab="bandicoot",},},
}
