-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_cleaver",
  anim_events={
    player_bank_cleaver={ cleaver_atk1={ events={ { frame=0, name="cleaver_atk1",},},},},
  },
  prefab={ {  },},
}
