-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_gourdo",
  anim_events={
    gourdo_bank={
      butt_slam={ events={ { frame=30, name="vfx-butt_slam",},},},
      elite_butt_slam_middle_loop={ events={ { frame=35, name="vfx-elite_butt_slam_middle_ring",},},},
      elite_butt_slam_start={ events={ { frame=23, name="vfx-elite_butt_slam_start_ring",},},},
      punch={ events={ { frame=6, name="vfx-punch_swipe",},},},
    },
  },
  prefab={ { prefab="gourdo",},},
}
