-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_mothball_teen",
  anim_events={
    mothball_teen_bank={
      attack_loop={
        events={ { frame=0, name="vfx-attack_magic",}, { frame=0, name="vfx-attack_loop",},},
      },
      attack_pre={ events={ { frame=10, name="vfx-attack_pre",},},},
      attack_pst={ events={ { frame=0, name="vfx-attack_pst",},},},
      walk_loop={ events={ { frame=0, name="vfx-walk_loop_escape",},},},
    },
  },
  prefab={ { prefab="mothball_teen",},},
}
