-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_npc_mouths",
  anim_events={
    npc_template_mouth={
      happy_mouth_talk={
        events={
          { frame=2, name="sfx-speech_blah",},
          { frame=11, name="sfx-speech_blah",},
          { frame=14, name="sfx-speech_blah",},
          { frame=18, name="sfx-speech_blah",},
          { frame=24, name="sfx-speech_blah",},
          { frame=30, name="sfx-speech_blah",},
        },
      },
      neutral_mouth_talk={
        events={
          { frame=2, name="sfx-speech_blah",},
          { frame=11, name="sfx-speech_blah",},
          { frame=14, name="sfx-speech_blah",},
          { frame=18, name="sfx-speech_blah",},
          { frame=24, name="sfx-speech_blah",},
          { frame=30, name="sfx-speech_blah",},
        },
      },
    },
  },
  prefab={
    { prefab="npc_scout_mouth",},
    { prefab="npc_armorsmith_mouth",},
    { prefab="npc_refiner_mouth",},
    { prefab="npc_apothecary_mouth",},
    { prefab="npc_cook_mouth",},
    { prefab="npc_blacksmith_mouth",},
  },
}
