-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_shotput_projectile",
  anim_events={
    fx_player_projectile_shotput={ land={ events={ { frame=1, name="sfx-shotput_land",},},},},
  },
  prefab={ { prefab="projectile_shotput_land",},},
}
