-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_blarmadillo_hide",
  build="drops_blarmadillo",
  droptype="soft",
  group="drops_blarmadillo",
  loot_id="blarmadillo_hide",
  symbol="blarmadillo_hide",
}
