-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_owlitzer_pelt",
  build="drops_owlitzer",
  droptype="soft",
  group="drops_owlitzer",
  loot_id="owlitzer_pelt",
  motionfacing=true,
  symbol="owlitzer_pelt",
}
