-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_bandicoot_wing",
  build="drops_bandicoot",
  droptype="soft",
  group="drops_bandicoot",
  loot_id="bandicoot_wing",
  pos="back",
  symbol="bandicoot_wing",
}
