-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_forest_sap",
  build="drops_startingforest",
  droptype="jiggle",
  group="drops_startingforest",
  loot_id="forest_sap",
  randomflip=true,
  symbol="forest_sap",
}
