-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_beets_leaf",
  build="drops_beets",
  droptype="soft",
  group="drops_beets",
  loot_id="beets_leaf",
  pos="front",
  symbol="beets_leaf",
}
