-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_thatcher_limb",
  build="drops_thatcher",
  droptype="solid",
  group="drops_thatcher",
  loot_id="thatcher_limb",
  motionfacing=true,
  symbol="thatcher_limb",
}
