-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="bomb_explosion",
  anim="explode",
  autostop=true,
  bank="fx_trap_explosion",
  bloom=50.0,
  build="fx_trap_explosion",
  finaloffset=7,
  glowcolor="8E10B1FF",
  group="bombs_traps",
  soundevent="pinecone_bomb_traps_explode",
}
