-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="cannon_aoe_explosion_med_focus",
  anim="1",
  bank="fx_hit_fire",
  bloom=100.0,
  build="fx_hit_fire",
  glowcolor="0098FFFF",
  group="hits_fx",
  hue=180.0,
  target_tint="FF640000",
}
