-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="coinflip_tails_loop",
  anim="roll_tails",
  bank="fx_coinflip",
  bloom=17.0,
  build="fx_coinflip",
  glowcolor="FFE600FF",
  group="coin",
}
