-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_eyev_elite_grnd",
  addcolor="21212100",
  anim="death_ground_aftersplash",
  bank="fx_monster_death_untex",
  brightness=25.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=44.0,
  layer="bg",
  onground=true,
  randomflip=true,
  saturation=-81.0,
  scalex=1.0,
  scaley=1.0,
  sortorder=2,
}
