-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_impact_grass_medium",
  anim="ground",
  bank="fx_dust",
  bloom=100.0,
  build="fx_dust",
  glowcolor="0074FFFF",
  group="fx_impact",
  layer="bg",
  multcolor="D4D4FF82",
  onground=true,
  scalex=1.0,
  scaley=1.0,
  sortorder=2,
}
