-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_powerup_front",
  anim="powerup_yes_pst_front",
  bank="fx_powerup",
  bloom=100.0,
  build="fx_powerup",
  glowcolor="C500FFFF",
  group="fx_player_powerups",
  sound_max_count=1.0,
  soundevent="power_acquire",
}
