-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_roll_atk_fancy",
  anim="roll_atk",
  bank="fx_player_bank_polearm",
  bloom=40.0,
  build="fx_player_bank_polearm",
  finaloffset=1,
  group="fx_polearm",
  lightoverride=100,
  multcolor="FFFFFFCC",
}
