-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_atk2_fancy",
  anim="atk2",
  bank="fx_player_bank_polearm",
  bloom=50.0,
  build="fx_player_bank_polearm",
  finaloffset=1,
  group="fx_polearm",
  lightoverride=100,
  multcolor="FFFFFFE6",
}
