-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_cannon_atk1_ammo2_basic",
  anim="cannon_atk1_ammo2",
  bank="fx_player_bank_cannon",
  bloom=100.0,
  build="fx_player_bank_cannon",
  finaloffset=1,
  glowcolor="00AFFFFF",
  group="fx_cannon",
  hue=-129.0,
  multcolor="CCCCCCFF",
  scalex=1.0,
  scaley=1.0,
}
