-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_shove_basic",
  addcolor="84000000",
  anim="polearm_shove",
  bank="fx_player_bank_polearm_basic",
  bloom=100.0,
  build="fx_player_bank_polearm_basic",
  finaloffset=1,
  glowcolor="FF9F00FF",
  group="fx_polearm_basic",
  multcolor="FF8280CC",
}
