-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="ground_indicator_beam_p2",
  addcolor="68840000",
  anim="loop",
  bank="fx_item_drop",
  bloom=100.0,
  build="fx_item_pickup_untex",
  finaloffset=-1,
  glowcolor="FFCF62FF",
  group="item_drops",
  looping=true,
  multcolor="FFFFFF1F",
}
