-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hit_rock",
  anim="hit_rock_",
  bank="fx_destructible_hit",
  build="fx_destructible_hit_build",
  group="destructible_hits",
  soundevent="Destructible_rock",
  variations=2,
}
