-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_undies_color_1",
  cosmetic_data={
    color={ 0.083333333333333, 0.01, 0.5,},
    colorgroup="UNDIES_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
