-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="hunterphd",
  cosmetic_data={ title_key="HUNTERPHD",},
  group="PLAYER_TITLE",
  hidden=false,
  locked=true,
  mastery="none",
  purchased=false,
  rarity="LEGENDARY",
}
