-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_orange_hair_color_1",
  cosmetic_data={
    color={ 0.083333333333333, 0.63, 0.97,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
