-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_gold_skin_tone_1",
  cosmetic_data={
    color={ 0.091666666666667, 0.65, 0.85,},
    color_species="mer",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
