-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_pink_ornament_color_1",
  cosmetic_data={
    color={ 0.80555555555556, 0.33, 1.0,},
    colorgroup="ORNAMENT_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
