-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_wing_ears_1",
  cosmetic_data={
    bodypart_group="EARS",
    bodypart_species="mer",
    build="player_ears_mer_wing",
    colorgroup="SKIN_TONE",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
