-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_yellow_ornament_color_1",
  cosmetic_data={
    color={ 0.15277777777778, 0.34, 0.97,},
    colorgroup="ORNAMENT_COLOR",
    color_species="mer",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
