-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_triangle_nose_1",
  cosmetic_data={
    bodypart_group="NOSE",
    bodypart_species="ogre",
    build="player_nose_ogre_triangle",
    colorgroup="NOSE_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
