-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_hair_pigtail_base",
  cosmetic_data={
    bodypart_group="HAIR",
    bodypart_species="ogre",
    build="player_hair_ogre_pigtail_braids",
    colorgroup="HAIR_COLOR",
    symboltags={  },
    uitags={  },
  },
  deprecated=true,
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
