-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_9",
  cosmetic_data={
    color={ 0.39607843756676, 0.42745098471642, 0.3098039329052,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
