-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_spawnplant_forest",
  group="sound_spawn",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "spawner_plant1",},
  stategraphs={
    sg_spawner_battlefield={
      events={
        spawn_creature={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="spawn_plant_forest_spawn",},
          },
        },
        spawn_tell={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="spawn_plant_forest_LP", stopatexitstate=true,},
          },
        },
      },
    },
  },
}
