-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_blarmadillo_bullet",
  group="sound_creature",
  isfinal=true,
  needSoundEmitter=true,
  prefab="blarmadillo_bullet",
  stategraphs={
    blarmadillo_bullet={
      events={
        block_pst={ { eventtype="playsound", frame=19, param={ soundevent="blarmadillo_land",},},},
        hit={ { eventtype="playsound", frame=1, param={ soundevent="blarmadillo_hit",},},},
        idle={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="blarmadillo_shoot_LP", stopatexitstate=true,},
          },
        },
        knockback={ { eventtype="playsound", frame=1, param={ soundevent="blarmadillo_hit",},},},
        knockdown_getup={ { eventtype="playsound", frame=42, param={ soundevent="blarmadillo_land",},},},
        knockdown_pre={
          { eventtype="playsound", frame=10, param={ soundevent="Dirt_bodyfall",},},
          { eventtype="playsound", frame=11, param={ soundevent="footstep_grass_large",},},
        },
        roll={
          { eventtype="playsound", frame=15, param={ soundevent="blarmadillo_bounce",},},
          { eventtype="playsound", frame=5, param={ soundevent="blarmadillo_bounce",},},
          {
            eventtype="playsound",
            frame=4,
            param={ name="blarm_roll_LP", soundevent="blarmadillo_roll_LP", stopatexitstate=true,},
          },
        },
        roll_pst={
          { eventtype="playsound", frame=16, param={ soundevent="blarmadillo_land",},},
          { eventtype="stopsound", frame=1, param={ name="blarm_roll_LP",},},
        },
        shoot={ { eventtype="playsound", frame=8, param={ soundevent="blarmadillo_shoot",},},},
        shoot_hold={
          {
            eventtype="playsound",
            frame=1,
            param={ name="slurp", soundevent="blarmadillo_slurp", stopatexitstate=true,},
          },
        },
        shoot_pre={
          { eventtype="playsound", frame=11, param={ soundevent="blarmadillo_dig",},},
          { eventtype="playsound", frame=1, param={ soundevent="blarmadillo_VO",},},
        },
        sneeze={
          { eventtype="playsound", frame=69, param={ soundevent="blarmadillo_sneeze",},},
          { eventtype="playsound", frame=6, param={ soundevent="Dirt_hand",},},
          { eventtype="playsound", frame=15, param={ soundevent="Dirt_hand",},},
          { eventtype="playsound", frame=28, param={ soundevent="Dirt_hand",},},
          { eventtype="playsound", frame=36, param={ soundevent="Dirt_hand",},},
        },
        spawn_battlefield={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="spawn_whoosh_small", stopatexitstate=true,},
          },
          { eventtype="playsound", frame=14, param={ soundevent="blarmadillo_land",},},
        },
        trumpet={
          { eventtype="playsound", frame=12, param={ soundevent="blarmadillo_trumpet",},},
        },
        walk_loop={
          { eventtype="playsound", frame=1, param={ soundevent="footstep_grass_small",},},
          { eventtype="playsound", frame=10, param={ soundevent="footstep_grass_small",},},
        },
      },
      state_events={ idle={  },},
    },
    sg_blarmadillo_projectile={
      events={
        thrown={
          {
            eventtype="playsound",
            frame=1,
            param={
              autostop=true,
              sound_max_count=5.0,
              soundevent="blarmadillo_shoot_LP",
              stopatexitstate=true,
            },
          },
        },
      },
    },
  },
}
