-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_sporemon",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "sporemon", "sporemon_elite",},
  stategraphs={
    sg_sporemon={
      sg_events={
        {
          eventtype="playsound",
          name="sfx-bite_pre",
          param={ soundevent="sporemon_bite_pre",},
        },
        { eventtype="playsound", name="sfx-bite", param={ soundevent="sporemon_bite",},},
        {
          eventtype="playsound",
          name="sfx-shoot_pre",
          param={ soundevent="sporemon_shoot_pre",},
        },
        { eventtype="playsound", name="sfx-shoot", param={ soundevent="sporemon_shoot",},},
        {
          eventtype="playsound",
          name="sfx-squish",
          param={ soundevent="sporemon_squish",},
        },
        {
          eventtype="playsound",
          name="sfx-spike_pre",
          param={ soundevent="sporemon_spike_pre",},
        },
        { eventtype="playsound", name="sfx-spike", param={ soundevent="sporemon_spike",},},
      },
    },
  },
}
