-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="WIP_fx_death_blarmadillo",
  isfinal=true,
  prefab={ "death_blarmadillo_frnt",},
  stategraphs={
    death_blarmadillo_frnt={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=1,
            param={ fxname="death_blarmadillo_grnd", scalex=0.9, scalez=0.9,},
          },
        },
      },
    },
  },
}
