-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="bomb_explosion_warning",
  anim="blinking",
  bank="fx_trap_explosion",
  bloom=80.0,
  build="fx_trap_explosion",
  clip_at_worldedge=true,
  finaloffset=7,
  glowcolor="8E10B1FF",
  group="bombs_traps",
  looping=true,
  multcolor="FFFFFF80",
  onground=true,
  sortorder=-1,
}
