-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_sporemon_elite_grnd",
  anim="death_ground_aftersplash",
  bank="fx_monster_death_untex",
  brightness=67.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-76.0,
  layer="bg",
  onground=true,
  randomflip=true,
  saturation=-83.0,
  sortorder=2,
}
