-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_blarmadillo_elite_grnd",
  anim="death_ground_splash",
  bank="fx_monster_death_untex",
  brightness=20.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-70.0,
  layer="bg",
  noflip=true,
  onground=true,
  saturation=-94.0,
  scalex=0.89999997615814,
  scaley=0.89999997615814,
  sortorder=2,
}
