-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="electric_chain_identifier_lrg",
  anim="electric_chain_identifier_",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  layer="bg",
  multcolor="FFFFFFE6",
  onground=true,
  randomflip=true,
  scalex=1.1000000238419,
  scaley=1.25,
  sortorder=2,
  target_tint="FF640000",
  variations=3,
}
