-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_charm_ribbon_front",
  anim="ribbon_front",
  bank="fx_healing",
  bloom=49.0,
  brightness=-24.0,
  build="fx_healing",
  finaloffset=-1,
  glowcolor="C1649BFF",
  group="charm",
  hue=-130.0,
  soundevent="Power_Charm_FX",
}
