-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_dust_up1",
  anim="up4",
  bank="fx_dust",
  build="fx_dust",
  group="fx_dust",
  multcolor="FFC78780",
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
}
