-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_ground_target_jamball_p2",
  additive=true,
  anim="idle_ground_target_jamball",
  bank="fx_ground_target",
  bloom=50.0,
  build="fx_ground_target",
  clip_at_worldedge=true,
  finaloffset=-1,
  glowcolor="FFE577FF",
  group="fx_warning",
  looping=true,
  multcolor="4A4F00CC",
  onground=true,
  randomstartframe=true,
}
