-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="ground_indicator_ring_p1",
  additive=true,
  anim="indicator_ring",
  bank="aim_pointer_ground_indicator",
  bloom=50.0,
  build="aim_pointer_ground_indicator",
  finaloffset=-1,
  glowcolor="0074FFFF",
  looping=true,
  multcolor="2B36FFF2",
  onground=true,
  randomstartframe=true,
}
