-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_electric_sml",
  anim="hit_electric_sml",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="hits_fx",
  randomflip=true,
  soundevent="Power_Electric_Hit",
  target_tint="FF640000",
}
