-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="projectile_cannonball_hit",
  anim="shot_",
  autostop=true,
  bank="fx_hits_cannon",
  bloom=100.0,
  build="fx_hits_cannon",
  glowcolor="FF6A00FF",
  group="projectiles",
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
  soundevent="Hit_cannon",
  variations=3,
  window_frames=1.0,
}
