-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="yammo_elite_heavy_slam",
  anim="elite_heavy_slam",
  bank="fx_yammo",
  bloom=100.0,
  build="fx_yammo",
  finaloffset=1,
  glowcolor="FA9700FF",
  group="fx_yammo",
}
