-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="armorer_1",
  clickable=true,
  gridsize={ { expand={ bottom=2,}, h=3, w=3,},},
  group="town_buildings",
  nonpersist=true,
  parallax={
    { anim="front", dist=-0.8, shadow=true,},
    { anim="frontleg", dist=-0.72,},
    { anim="cloth", dist=-0.12,},
    { anim="mirror", shadow=true,},
    { anim="back", dist=0.4, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="dec",
  script="buildings",
  script_args={
    skins={ groups={  }, sets={  }, symbols={  },},
    upgrades={ has_upgrade=true, prefab="armorer",},
  },
  sound=true,
}
