-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_fg_canopybug",
  bank="bandiforest_up_canopy",
  build="bandiforest_up_canopy",
  fade={ bottom=19.14, top=16.28,},
  group="swamp_props",
  parallax={ { anim="fgcanopybug",},},
  proptype=1.0,
  variations=4,
}
