-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_zucco_skin",
  build="drops_zucco",
  droptype="solid",
  group="drops_zucco",
  loot_id="zucco_skin",
  symbol="zucco_skin",
}
