-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_floracrane_feet",
  build="drops_floracrane",
  droptype="curve",
  group="drops_floracrane",
  loot_id="floracrane_feet",
  randomflip=true,
  symbol="floracrane_feet",
}
