-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_forest_twigs",
  build="drops_startingforest",
  droptype="twigfall",
  group="drops_startingforest",
  loot_id="forest_twigs",
  randomflip=true,
  symbol="forest_twigs",
}
