-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_mossquito_tooth",
  build="drops_mossquito",
  droptype="curve",
  group="drops_mossquito",
  loot_id="mossquito_tooth",
  randomflip=true,
  symbol="mossquito_tooth",
}
