-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_bonejaw_claw",
  build="drops_bonejaw",
  droptype="curve",
  group="drops_bonejaw",
  loot_id="bonejaw_claw",
  motionfacing=true,
  symbol="bonejaw_claw",
}
