-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_gourdo_finger",
  build="drops_gourdo",
  droptype="curve",
  group="drops_gourdo",
  loot_id="gourdo_finger",
  symbol="gourdo_finger",
}
