-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_zucco_claw",
  build="drops_zucco",
  droptype="curve",
  group="drops_zucco",
  loot_id="zucco_claw",
  symbol="zucco_claw",
}
