-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_treemon_arm",
  build="drops_treemon",
  droptype="solid",
  group="drops_treemon",
  loot_id="treemon_arm",
  symbol="treemon_arm",
}
