-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_arak_shell",
  build="drops_arak",
  droptype="curve",
  group="drops_arak",
  loot_id="arak_shell",
  symbol="arak_shell",
}
