-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_thatcher_shell",
  build="drops_thatcher",
  droptype="curve",
  group="drops_thatcher",
  loot_id="thatcher_shell",
  randomflip=true,
  symbol="thatcher_shell",
}
