-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_yammo_skin",
  build="drops_yammo",
  droptype="curve",
  group="drops_yammo",
  loot_id="yammo_skin",
  symbol="yammo_skin",
}
