-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_battoad_wing",
  build="drops_battoad",
  droptype="soft",
  group="drops_battoad",
  loot_id="battoad_wing",
  randomflip=true,
  symbol="battoad_wing",
}
