-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_slowpoke_tail",
  build="drops_slowpoke",
  droptype="soft",
  group="drops_slowpoke",
  loot_id="slowpoke_tail",
  randomflip=true,
  symbol="slowpoke_tail",
}
