-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_cabbageroll_skin",
  build="drops_cabbageroll",
  droptype="soft",
  group="drops_cabbageroll",
  loot_id="cabbageroll_skin",
  randomflip=true,
  symbol="cabbageroll_skin",
}
