-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_floracrane_feather",
  build="drops_floracrane",
  droptype="soft",
  group="drops_floracrane",
  loot_id="floracrane_feather",
  randomflip=true,
  symbol="floracrane_feather",
}
