-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_cabbageroll_baby",
  build="drops_cabbageroll",
  droptype="soft",
  group="drops_cabbageroll",
  loot_id="cabbageroll_baby",
  randomflip=true,
  symbol="cabbageroll_baby",
}
