-- Generated by DropEditor and loaded by drops_autogen.lua
return {
  __displayName="drop_eyev_eyelashes",
  build="drops_eyev",
  droptype="jiggle",
  group="drops_eyev",
  loot_id="eyev_eyelashes",
  randomflip=true,
  symbol="eyev_eyelashes",
}
