return {
  room_loot={ { x=-0.5, z=-4.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.84, z=-2.98,},
    { script_args={ creature_spawner_type="perimeter",}, x=9.59, z=10.58,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.97, z=12.81,},
    { script_args={ creature_spawner_type="perimeter",}, x=-7.7, z=12.74,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.46, z=6.39,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.0, z=2.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.0, z=-10.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-11.01, z=5.37,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.0, z=4.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.0, z=-12.0,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.09, z=4.54,},
  },
  spawner_propdestructible={
    { x=-16.0, z=-4.0,},
    { x=-18.0, z=6.0,},
    { x=-6.0, z=-14.0,},
    { x=6.0, z=-14.0,},
    { x=12.0, z=6.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, x=3.0, z=2.0,},
    { script_args={  }, x=2.0, z=-14.0,},
    { script_args={  }, x=-7.0, z=3.0,},
    { script_args={  }, x=16.0, z=-2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_acid",},}, x=-6.5, z=-3.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=-1.5, z=-5.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=-11.5, z=-0.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=8.5, z=-5.5,},
    { script_args={ trap_types={ "trap_acid",},}, x=3.5, z=-5.5,},
  },
}