return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-10.72, z=-4.19,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.16, z=-10.19,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=4.97, z=-6.79,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=12.32, z=-6.38,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=17.22, z=-12.02,},
  },
  room_loot={ { x=10.5, z=-5.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=24.62, z=3.85,},
    { script_args={ creature_spawner_type="perimeter",}, x=2.53, z=7.84,},
    { script_args={ creature_spawner_type="perimeter",}, x=-9.91, z=4.28,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.8, z=-13.76,},
    { script_args={ creature_spawner_type="battlefield",}, x=1.75, z=-9.85,},
    { script_args={ creature_spawner_type="battlefield",}, x=4.31, z=-5.11,},
    { script_args={ creature_spawner_type="battlefield",}, x=3.3, z=-2.47,},
    { script_args={ creature_spawner_type="battlefield",}, x=-6.9, z=-5.86,},
    { script_args={ creature_spawner_type="battlefield",}, x=-12.96, z=-4.28,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.62, z=-4.74,},
  },
  spawner_propdestructible={
    { x=24.0, z=-3.0,},
    { x=-10.0, z=-5.0,},
    { x=-4.0, z=-5.0,},
    { x=-19.0, z=-10.0,},
    { x=10.0, z=-15.0,},
    { x=20.0, z=-12.0,},
    { x=-20.0, z=-3.0,},
    { z=-3.0,},
    { x=4.0, z=2.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=7.0, z=1.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=-3.0, z=-1.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, x=3.0, z=-17.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=14.0, z=-16.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=20.0, z=-5.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=9.0, z=-5.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=-9.0, z=-14.0,},
  },
  spawner_trap={
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-14.5,
      z=4.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-6.5, z=-16.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-3.5, z=-16.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-9.5, z=-16.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 3,}, trap_types={ "trap_windtotem",},},
      x=-5.5,
      z=4.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=8.0, z=-10.0,},
    { script_args={ trap_types={ "trap_spike",},}, x=14.0, z=-3.0,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-12.5, z=-16.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-16.0, z=-5.0,},
    { script_args={ trap_types={ "trap_spike",},}, x=-2.0, z=-10.0,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-15.5, z=-16.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-18.5, z=-16.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 1,}, trap_types={ "trap_windtotem",},},
      x=-18.5,
      z=-20.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-0.5, z=4.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-14.5,
      z=0.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-20.5,
      z=0.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=20.5,
      z=4.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=24.5,
      z=-16.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-17.5,
      z=0.5,
    },
  },
}