return {
  lightspot_circle={
    { script_args={ light_color="4D453FFF",}, variation=1, x=-6.57, z=-22.56,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-20.27, z=-16.75,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=6.7839999198914,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=2,
      x=-18.37,
      z=-37.88,
    },
    { script_args={ light_color="4D453FFF",}, variation=1, x=-3.65, z=-15.1,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-24.15, z=-35.32,},
    { script_args={ light_color="4D453FFF",}, variation=1, x=-16.1, z=-38.35,},
    {
      script_args={
        animate=false,
        intensity=0.75400000810623,
        light_color="4D453FFF",
        max_rotation=20,
        max_translation=0.5,
        rot_speed=0.66666666666667,
        rotation=0,
        scale=5.1970000267029,
        shimmer=false,
        shimmer_speed=3,
        shimmer_strength=0.5,
        trans_speed=0.5,
      },
      variation=1,
      x=-3.17,
      z=16.2,
    },
    { script_args={ light_color="4D453FFF",}, variation=2, x=5.35, z=4.85,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=-2.36, z=-17.67,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=3.99, z=13.88,},
    { script_args={ light_color="4D453FFF",}, variation=2, x=17.53, z=7.47,},
  },
  room_loot={ { x=11.5, z=5.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-17.97, z=-8.15,},
    { script_args={ creature_spawner_type="perimeter",}, x=7.06, z=15.83,},
    { script_args={ creature_spawner_type="perimeter",}, x=1.11, z=15.9,},
    { script_args={ creature_spawner_type="perimeter",}, x=-22.87, z=-8.1,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.08, z=8.69,},
    { script_args={ creature_spawner_type="battlefield",}, x=-16.58, z=-13.06,},
    { script_args={ creature_spawner_type="battlefield",}, x=13.24, z=7.13,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.43, z=-15.49,},
    { script_args={ creature_spawner_type="battlefield",}, x=-16.22, z=-20.73,},
    { script_args={ creature_spawner_type="battlefield",}, x=-20.99, z=-27.96,},
    { script_args={ creature_spawner_type="battlefield",}, x=-17.21, z=-19.1,},
    { script_args={ creature_spawner_type="perimeter",}, x=9.21, z=-22.07,},
    { script_args={ creature_spawner_type="perimeter",}, x=9.46, z=-15.35,},
  },
  spawner_propdestructible={
    { x=-4.0,},
    { x=-16.0, z=-27.0,},
    { x=12.0,},
    { x=-21.0, z=-20.0,},
    { x=2.0, z=-17.0,},
    { x=-9.0, z=-9.0,},
    { x=11.0, z=11.0,},
  },
  spawner_stationaryenemy={
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=3.0, z=-4.0,},
    { script_args={ spawn_areas={ "bottom", "perimeter",},}, x=-10.0, z=-26.0,},
    { script_args={ spawn_areas={ "perimeter", "bottom",},}, z=-22.0,},
    { script_args={ spawn_areas={ "right", "perimeter",},}, x=3.0, z=-12.0,},
    { script_args={ spawn_areas={ "top", "battlefield",},}, x=-1.0, z=7.0,},
    { script_args={ spawn_areas={ "center", "battlefield",},}, x=-13.0, z=-11.0,},
  },
  spawner_trap={
    {
      place_anywhere=true,
      script_args={ trap_directions={ 2,}, trap_types={ "trap_windtotem",},},
      x=29.5,
      z=10.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-5.5, z=-28.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-8.5, z=-28.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-2.5, z=-28.5,},
    {
      place_anywhere=true,
      script_args={ trap_directions={ 0,}, trap_types={ "trap_windtotem",},},
      x=-13.5,
      z=2.5,
    },
    { script_args={ trap_types={ "trap_spike",},}, x=-2.5, z=-10.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-1.5, z=-5.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=0.5, z=3.5,},
    { script_args={ trap_types={ "trap_spike",},}, x=-9.5, z=-17.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-0.5, z=12.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-4.5, z=8.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-8.5, z=0.5,},
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=24.5,
      z=2.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=24.5,
      z=8.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=-8.5,
      z=3.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=24.5,
      z=-0.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=4.5,
      z=-24.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=0.5,
      z=-28.5,
    },
    {
      place_anywhere=true,
      script_args={ trap_types={ "trap_thorns",},},
      x=24.5,
      z=5.5,
    },
    { script_args={ trap_types={ "trap_thorns",},}, x=-25.5, z=-11.5,},
    { script_args={ trap_types={ "trap_thorns",},}, x=-28.5, z=-11.5,},
  },
}