return {
  room_loot={ { x=-2.5, z=-2.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-16.91, z=10.91,},
    { script_args={ creature_spawner_type="perimeter",}, x=10.15, z=13.31,},
    { script_args={ creature_spawner_type="perimeter",}, x=13.39, z=-11.52,},
    { script_args={ creature_spawner_type="perimeter",}, x=17.38, z=6.25,},
    { script_args={ creature_spawner_type="battlefield",}, x=-8.36, z=7.73,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.15, z=-12.26,},
    { script_args={ creature_spawner_type="battlefield",}, x=5.94, z=-10.31,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.42, z=-10.66,},
    { script_args={ creature_spawner_type="battlefield",}, x=-7.02, z=9.88,},
    { script_args={ creature_spawner_type="battlefield",}, x=8.64, z=6.73,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.51, z=8.73,},
    { script_args={ creature_spawner_type="battlefield",}, x=-8.21, z=-8.68,},
  },
  spawner_propdestructible={
    { x=4.0, z=-16.0,},
    { x=-17.0, z=4.0,},
    { x=3.0, z=-1.0,},
    { x=8.0, z=-7.0,},
    { x=-12.0, z=8.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, z=-2.0,},
    { script_args={  }, z=9.0,},
    { script_args={  }, x=-7.0, z=-13.0,},
    { script_args={  }, x=13.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-9.5, z=2.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-2.5, z=-11.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=2.5, z=-7.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=6.5, z=-1.5,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=-2.5, z=-0.5,},
  },
}