return {
  room_loot={ { x=0.5, z=-4.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=-17.16, z=1.6,},
    { script_args={ creature_spawner_type="perimeter",}, x=5.97, z=9.13,},
    { script_args={ creature_spawner_type="perimeter",}, x=21.34, z=-16.25,},
    { script_args={ creature_spawner_type="battlefield",}, x=-5.95, z=4.14,},
    { script_args={ creature_spawner_type="battlefield",}, x=11.02, z=-19.13,},
    { script_args={ creature_spawner_type="battlefield",}, x=12.83, z=-17.1,},
    { script_args={ creature_spawner_type="battlefield",}, x=-16.14, z=-17.85,},
    { script_args={ creature_spawner_type="battlefield",}, x=-8.0, z=5.69,},
    { script_args={ creature_spawner_type="battlefield",}, x=9.43, z=-0.82,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.55, z=1.21,},
    { script_args={ creature_spawner_type="battlefield",}, x=-14.12, z=-19.09,},
    { script_args={ creature_spawner_type="perimeter",}, x=-13.3, z=4.03,},
    { script_args={ creature_spawner_type="perimeter",}, x=-25.41, z=-15.71,},
  },
  spawner_propdestructible={
    { x=-11.0, z=-15.0,},
    { x=-5.0, z=-2.0,},
    { x=8.0, z=-18.0,},
    { x=16.0, z=-18.0,},
    { x=8.0, z=-5.0,},
  },
  spawner_stationaryenemy={
    { script_args={  }, z=-6.0,},
    { script_args={  }, x=1.0, z=6.0,},
    { script_args={  }, x=-7.0, z=-17.0,},
    { script_args={  }, x=13.0, z=-2.0,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-10.5, z=-0.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=-19.5, z=-18.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=2.5, z=-12.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=13.5, z=-8.5,},
    { script_args={ trap_types={ "trap_spores", "trap_acid",},}, x=3.5, z=1.5,},
    { script_args={ trap_types={ "trap_stalactite",},}, x=-2.5, z=-8.5,},
  },
}