-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_player_impacts",
  anim_events={
    player_bank_hammer={
      hammer_atk4={ events={ { frame=5, name="vfx-impact_ground",},},},
      hammer_smash_air={ events={ { frame=4, name="vfx-impact_ground",},},},
      hammer_smash_air_alt={ events={ { frame=18, name="vfx-impact_ground",},},},
    },
    player_bank_hammer_basic={ hammer_knockdown={ events={ { frame=12, name="vfx-impact_ground",},},},},
    player_bank_polearm={ polearm_skill_vault_pre={ events={ { frame=7, name="vfx-impact",},},},},
  },
  prefab={ { prefab="player_side",},},
}
