-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_player_cannon",
  anim_events={
    player_bank_cannon={
      cannon_H_atk={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_H_to_H_atk={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_H_to_L_atk={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_H_to_plant={ events={ { frame=6, name="vfx-impact",},},},
      cannon_atk1={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_atk2_shoot={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_backfire_heavy_atk={ events={ { frame=1, name="vfx-cannon_backfire_heavy_atk",},},},
      cannon_backfire_med_atk={ events={ { frame=1, name="vfx-cannon_backfire_med_atk",},},},
      cannon_backfire_pst={ events={ { frame=1, name="vfx-cannon_backfire_pst",},},},
      cannon_backfire_shoot={ events={ { frame=1, name="vfx-cannon_backfire_shoot",},},},
      cannon_empty={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_getup_dodge={ events={ { frame=0, name="vfx-muzzleflash",},},},
      cannon_mortar_early={ events={ { frame=12, name="vfx-impact",},},},
      cannon_mortar_heavy_atk={ events={ { frame=2, name="vfx-muzzleflash",},},},
      cannon_mortar_med_atk={ events={ { frame=1, name="vfx-muzzleflash",},},},
      cannon_shockwave_heavy_atk={ events={ { frame=1, name="vfx-cannon_shockwave_heavy_atk",},},},
      cannon_shockwave_med_atk={ events={ { frame=1, name="vfx-cannon_shockwave_med_atk",},},},
      cannon_shockwave_shoot={ events={ { frame=1, name="vfx-cannon_shockwave_shoot",},},},
    },
  },
  prefab={ { prefab="player_side",},},
}
