-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_street_lamp",
  anim_events={
    street_lamp={ idle={ events={ { frame=0, name="vfx-idle_glow", postfix="_2",},},},},
  },
  prefab={ { baseanim="2", prefab="street_lamp",},},
}
