-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="power_drop_konjur",
  anim_events={
    power_drop_konjur_liquid={
      shatter={ events={ { frame=0, name="sfx-pop", postfix="_1",},},},
      spawn={
        events={
          { frame=0, name="sfx-spawn", postfix="_1",},
          { frame=33, name="sfx-burble", postfix="_1",},
        },
      },
    },
  },
  prefab={ { baseanim="1", prefab="power_drop_konjur",},},
}
