-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_mothball",
  anim_events={
    mothball_bank={
      claw={ events={ { frame=9, name="sfx-claw",},},},
      claw_loop={ events={ { frame=0, name="sfx-claw_loop",},},},
      flinch_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_back_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_pst={ events={ { frame=0, name="sfx-hit",},},},
      knockdown_hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      knockdown_pre={ events={ { frame=12, name="sfx-spawn",}, { frame=1, name="sfx-hit",},},},
      pierce={ events={ { frame=6, name="sfx-pierce",},},},
      pierce_pre_hold={ events={ { frame=0, name="sfx-pierce_pre_hold",},},},
      spawn={
        events={
          { frame=18, name="sfx-spawn",},
          { frame=4, name="sfx-whoosh",},
          { frame=8, name="sfx-whoosh",},
          { frame=12, name="sfx-whoosh",},
          { frame=16, name="sfx-whoosh",},
        },
      },
      taunt={ events={ { frame=7, name="sfx-taunt",},},},
    },
  },
  prefab={ { prefab="mothball",},},
}
