-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_floracrane",
  anim_events={
    floracrane_bank={
      behavior1={
        events={
          { frame=14, name="sfx-wings",},
          { frame=29, name="sfx-wings",},
          { frame=10, name="sfx-vo2",},
          { frame=25, name="sfx-vo2",},
          { frame=46, name="sfx-foley",},
          { frame=7, name="sfx-foley",},
          { frame=15, name="sfx-foley",},
          { frame=30, name="sfx-foley",},
        },
      },
      dive={
        events={
          { frame=39, name="sfx-footstep",},
          { frame=96, name="sfx-footstep",},
          { frame=104, name="sfx-footstep",},
          { frame=3, name="sfx-wings",},
          { frame=25, name="sfx-wings",},
          { frame=37, name="sfx-wings",},
          { frame=99, name="sfx-wings",},
          { frame=1, name="sfx-dive",},
          { frame=30, name="sfx-dive_hit",},
          { frame=93, name="sfx-wings",},
          { frame=41, name="sfx-foley",},
          { frame=40, name="sfx-footstep",},
          { frame=75, name="sfx-upstretch",},
          { frame=51, name="sfx-upstretch",},
        },
      },
      dive2_hold={ events={ { frame=8, name="sfx-wings",}, { frame=26, name="sfx-wings",},},},
      dive2_pre={ events={ { frame=1, name="sfx-foley",}, { frame=2, name="sfx-upstretch",},},},
      flinch_pst={
        events={
          { frame=2, name="sfx-footstep",},
          { frame=9, name="sfx-footstep",},
          { frame=4, name="sfx-wings",},
        },
      },
      flurry={
        events={
          { frame=37, name="sfx-footstep",},
          { frame=9, name="sfx-wings",},
          { frame=10, name="sfx-flurry",},
          { frame=11, name="sfx-vo2",},
        },
      },
      flurry_loop={ events={ { frame=9, name="sfx-footstep",}, { frame=4, name="sfx-scrape",},},},
      flurry_pre={ events={ { frame=1, name="sfx-foley",}, { frame=2, name="sfx-upstretch",},},},
      hit_back_pst={ events={ { frame=0, name="sfx-hit",},},},
      hit_pst={ events={ { frame=0, name="sfx-hit",},},},
      hop_above={
        events={
          { frame=4, name="sfx-wings",},
          { frame=15, name="sfx-wings",},
          { frame=17, name="sfx-footstep",},
          { frame=19, name="sfx-footstep",},
          { frame=6, name="sfx-vo_short",},
        },
      },
      hop_below={
        events={
          { frame=8, name="sfx-vo_short",},
          { frame=5, name="sfx-wings",},
          { frame=15, name="sfx-wings",},
        },
      },
      hop_forward={
        events={
          { frame=5, name="sfx-wings",},
          { frame=17, name="sfx-wings",},
          { frame=19, name="sfx-footstep",},
          { frame=20, name="sfx-footstep",},
        },
      },
      kick={
        events={
          { frame=2, name="sfx-footstep",},
          { frame=17, name="sfx-wings",},
          { frame=1, name="sfx-foley",},
          { frame=6, name="sfx-upstretch",},
          { frame=16, name="sfx-kick",},
        },
      },
      kick_pre={
        events={
          { frame=15, name="sfx-vo2",},
          { frame=1, name="sfx-foley",},
          { frame=5, name="sfx-upstretch",},
        },
      },
      kick_pst_hit={ events={ { frame=1, name="sfx-foley",}, { frame=1, name="sfx-upstretch",},},},
      kick_pst_miss={
        events={
          { frame=14, name="sfx-footstep",},
          { frame=11, name="sfx-wings",},
          { frame=4, name="sfx-foley",},
          { frame=9, name="sfx-upstretch",},
        },
      },
      knockdown_getup={
        events={
          { frame=12, name="sfx-footstep",},
          { frame=10, name="sfx-footstep",},
          { frame=38, name="sfx-wings",},
          { frame=20, name="sfx-foley",},
          { frame=30, name="sfx-upstretch",},
        },
      },
      knockdown_idle={
        events={ { frame=16, name="sfx-vo_short_q",}, { frame=50, name="sfx-vo_short_q",},},
      },
      knockdown_pre={
        events={
          { frame=1, name="sfx-knockdown",},
          { frame=14, name="sfx-footstep",},
          { frame=18, name="sfx-footstep",},
          { frame=1, name="sfx-knockdown_vo",},
          { frame=2, name="sfx-foley",},
        },
      },
      spawn={
        events={
          { frame=26, name="sfx-footstep",},
          { frame=28, name="sfx-footstep",},
          { frame=9, name="sfx-wings",},
          { frame=21, name="sfx-wings",},
        },
      },
      spear={
        events={
          { frame=39, name="sfx-footstep",},
          { frame=12, name="sfx-wings",},
          { frame=1, name="sfx-spear",},
          { frame=12, name="sfx-foley",},
          { frame=13, name="sfx-upstretch",},
          { frame=29, name="sfx-upstretch",},
        },
      },
      spear_hold={ events={ { frame=6, name="sfx-vo_short",}, { frame=18, name="sfx-vo_short",},},},
      spinning_bird_kick_pre={
        events={
          { frame=1, name="sfx-spinning_pre",},
          { frame=5, name="sfx-vo_short",},
          { frame=1, name="sfx-foley",},
        },
      },
      spinning_bird_kick_pre_loop={ events={ { frame=1, name="sfx-spinning",},},},
      spinning_bird_kick_pst={
        events={
          { frame=6, name="sfx-footstep",},
          { frame=8, name="sfx-wings",},
          { frame=9, name="sfx-foley",},
          { frame=13, name="sfx-footstep",},
          { frame=15, name="sfx-foley",},
          { frame=1, name="sfx-spinning_pst",},
        },
      },
      turn_pst_walk_pre={ events={ { frame=2, name="sfx-footstep",},},},
      walk_loop={
        events={ { frame=16, name="sfx-footstep",}, { frame=50, name="sfx-footstep",},},
      },
      walk_pre={ events={ { frame=2, name="sfx-footstep",},},},
    },
  },
  prefab={ { prefab="floracrane",}, { prefab="floracrane_elite",},},
}
