-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_cabbageroll",
  anim_events={
    cabbageroll_single_bank={
      behavior={ done=true, events={ { frame=5, name="sfx-vo_pitched",},},},
      behavior2={ done=true, events={ { frame=1, name="sfx-behaviour2",},},},
      behavior3={ done=true, events={ { frame=1, name="sfx-whistle",},},},
      bite={
        done=true,
        events={ { frame=2, name="sfx-whoosh",}, { frame=1, name="sfx-bite",},},
      },
      bite_pre={ done=true, events={ { frame=8, name="sfx-vo",},},},
      bite_pre_hold={ done=true,},
      bodyslam_btm={
        done=true,
        events={
          { frame=1, name="sfx-bodyfall",},
          { frame=3, name="sfx-whoosh",},
          { frame=8, name="sfx-whoosh",},
        },
      },
      bodyslam_btm_flip_pst={
        done=true,
        events={ { frame=2, name="sfx-bodyfall",}, { frame=10, name="sfx-footstep",},},
      },
      bodyslam_mid={
        done=true,
        events={
          { frame=4, name="sfx-whoosh",},
          { frame=12, name="sfx-whoosh",},
          { frame=19, name="sfx-slap",},
          { frame=20, name="sfx-footstep",},
        },
      },
      bodyslam_top={
        done=true,
        events={
          { frame=1, name="sfx-bodyfall",},
          { frame=8, name="sfx-whoosh",},
          { frame=11, name="sfx-bodyfall",},
          { frame=18, name="sfx-footstep",},
        },
      },
      catapult={
        done=true,
        events={
          { frame=1, name="sfx-twirl",},
          { frame=3, name="sfx-slap",},
          { frame=4, name="sfx-ground_hit",},
        },
      },
      combine={ done=true, events={ { frame=4, name="sfx-whoosh_q",},},},
      combine3={ done=true, events={ { frame=4, name="sfx-whoosh_q",},},},
      combine3_miss={ done=true,},
      combine_miss={ done=true, events={ { frame=3, name="sfx-footstep",},},},
      elite_roll_hit_pst={ events={ { frame=1, name="sfx-twirl",},},},
      elite_roll_loop={ events={ { frame=1, name="sfx-spin_launch",},},},
      elite_roll_pre={ events={ { frame=11, name="sfx-slap",}, { frame=1, name="sfx-roll_vo",},},},
      elite_roll_pst={
        events={
          { frame=17, name="sfx-footstep",},
          { frame=7, name="sfx-roll_hit",},
          { frame=15, name="sfx-roll_hit",},
        },
      },
      gather={ events={ { frame=1, name="sfx-gather",},},},
      hit_hold={ events={ { frame=0, name="sfx-hit_hitstop_start",},},},
      knockdown_btm_pre={ events={ { frame=4, name="sfx-bodyfall",},},},
      knockdown_btm_pst={ events={ { frame=0, name="sfx-bodyfall",}, { frame=4, name="sfx-hit",},},},
      knockdown_getup={
        events={
          { frame=4, name="sfx-whoosh",},
          { frame=6, name="sfx-vo",},
          { frame=14, name="sfx-roll_hit",},
        },
      },
      knockdown_hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      knockdown_mid_pst={ events={ { frame=1, name="sfx-ground_hit",},},},
      knockdown_pre={
        events={
          { frame=18, name="sfx-bodyfall",},
          { frame=25, name="sfx-vo",},
          { frame=6, name="sfx-whoosh_q",},
          { frame=14, name="sfx-whoosh_q",},
          { frame=1, name="sfx-vo_knockdown",},
          { frame=18, name="sfx-knockdown",},
        },
      },
      knockdown_top_pre={
        events={
          { frame=4, name="sfx-whoosh_q",},
          { frame=8, name="sfx-whoosh_q",},
          { frame=16, name="sfx-whoosh_q",},
        },
      },
      knockdown_top_pst={ events={ { frame=1, name="sfx-ground_hit",}, { frame=5, name="sfx-vo",},},},
      roll_loop={ events={ { frame=0, name="sfx-roll",}, { frame=7, name="sfx-roll_hit",},},},
      roll_pre_hold={ events={ { frame=1, name="sfx-roll_vo",},},},
      roll_pst={ events={ { frame=2, name="sfx-roll_hit",},},},
      spawn={
        events={
          { frame=2, name="sfx-whoosh_q",},
          { frame=3, name="sfx-vo",},
          { frame=10, name="sfx-whoosh_q",},
          { frame=16, name="sfx-roll_hit",},
        },
      },
      throw_pst={
        events={
          { frame=5, name="sfx-roll_hit",},
          { frame=10, name="sfx-whoosh_q",},
          { frame=21, name="sfx-roll_hit",},
        },
      },
      thrown={
        events={
          { frame=4, name="sfx-ground_hit",},
          { frame=7, name="sfx-whoosh_q",},
          { frame=9, name="sfx-whoosh_q",},
          { frame=14, name="sfx-roll_hit",},
          { frame=22, name="sfx-roll_hit",},
          { frame=1, name="sfx-twirl",},
        },
      },
      walk_loop={ events={ { frame=4, name="sfx-footstep",}, { frame=12, name="sfx-footstep",},},},
    },
  },
  prefab={ { prefab="cabbageroll",},},
}
