-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="aim_pointer_p2",
  additive=true,
  anim="pointer",
  bank="aim_pointer_ground_indicator",
  bloom=50.0,
  build="aim_pointer_ground_indicator",
  finaloffset=-1,
  glowcolor="FFE577FF",
  looping=true,
  multcolor="4A4F00CC",
  onground=true,
}
