-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="cannon_mortar_explosion_groundring_focus",
  anim="mortar_ground",
  bank="fx_hits_cannon",
  bloom=100.0,
  build="fx_hits_cannon",
  glowcolor="009BC1FF",
  group="hits_fx",
  hue=180.0,
  onground=true,
  randomflip=true,
  scalex=1.1000000238419,
  scaley=1.1000000238419,
  sortorder=-1,
}
