-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_floracrane_elite_grnd",
  anim="death_ground_aftersplash",
  bank="fx_monster_death_untex",
  brightness=50.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-40.0,
  layer="bg",
  onground=true,
  randomflip=true,
  saturation=-80.0,
  scalex=1.1000000238419,
  scaley=1.0,
  sortorder=2,
  soundevent="floracrane_elite_death",
}
