-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_battoad_elite_frnt",
  anim="death_splat_sml",
  bank="fx_monster_death_untex",
  brightness=50.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=40.0,
  randomflip=true,
  saturation=-80.0,
  scalex=1.3999999761581,
  scaley=1.3999999761581,
  shadow=true,
  soundevent="battoad_death",
}
