-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_groak_frnt",
  anim="death_splat_med",
  bank="fx_monster_death_untex",
  brightness=76.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-148.0,
  randomflip=true,
  saturation=-90.0,
  scalex=1.3999999761581,
  scaley=1.3999999761581,
  shadow=true,
}
