-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_beets_elite_frnt",
  anim="death_splat_sml",
  bank="fx_monster_death_untex",
  brightness=70.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-17.0,
  randomflip=true,
  saturation=-77.0,
  shadow=true,
  sound_max_count=3.0,
  soundevent="beets_death",
}
