-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_gourdo_elite_grnd",
  anim="death_ground_aftersplash",
  bank="fx_monster_death_untex",
  brightness=25.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  layer="bg",
  onground=true,
  randomflip=true,
  saturation=-55.0,
  scalex=1.2999999523163,
  scaley=1.2999999523163,
  sortorder=2,
  soundevent="gourdo_death",
}
