-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_battoad_upperwings",
  anim="upperwings",
  bank="fx_battoad",
  bloom=100.0,
  build="fx_battoad",
  glowcolor="B9FF00FF",
  group="fx_battoad",
  multcolor="80FF80FF",
  scalex=1.0,
  scaley=1.0,
}
