-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_overhead_swipe_full",
  anim="fx_hammer_atk4_full",
  bank="fx_hammer_charge_glint",
  bloom=100.0,
  build="fx_hammer_charge_glint",
  glowcolor="00C1FFFF",
  group="hammer_charge",
}
