-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_big_atk1_back_fancy",
  anim="hammer_big_atk1_back",
  bank="player_fx_hammer",
  bloom=50.0,
  build="fx_player_bank_hammer_swipe",
  finaloffset=1,
  group="fx_hammer_fancy",
  layer="bg",
  sortorder=2,
}
