-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_big_atk1_back_electric",
  anim="hammer_big_atk1_back",
  bank="fx_player_bank_hammer_electric",
  bloom=40.0,
  build="fx_player_bank_hammer_electric",
  glowcolor="FFFE00FF",
  group="fx_hammer_electric",
  multcolor="FFFFFFB3",
}
