-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_hammer_spin_air_gray",
  anim="spin_air",
  bank="fx_player_bank_hammer_gray",
  bloom=100.0,
  build="fx_player_bank_hammer_gray",
  finaloffset=1,
  group="fx_hammer_gray",
  multcolor="808080CC",
}
