-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_outfit_buy",
  addcolor="0000FF00",
  anim="2",
  bank="fx_dodge",
  bloom=100.0,
  build="fx_dodge",
  finaloffset=7,
  glowcolor="0071FFFF",
  group="dodge",
  multcolor="C7C7FFFF",
  noflip=true,
  sortorder=1,
  soundevent="Player_safe_dodge",
}
