-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_cannon_atk1_electric",
  anim="cannon_atk1",
  bank="fx_player_bank_cannon_electric",
  bloom=100.0,
  build="fx_player_bank_cannon_electric",
  finaloffset=1,
  glowcolor="FCA900FF",
  group="fx_cannon_electric",
  multcolor="CCCCCCFF",
  scalex=1.0,
  scaley=1.0,
}
