-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_projectile_trail_shotput_air_fast",
  anim="air_fast",
  bank="fx_player_projectile_trail_shotput",
  bloom=50.0,
  build="fx_player_projectile_trail_shotput",
  group="trails",
  looping=true,
  multcolor="FFFFFF80",
  randomstartframe=true,
}
