-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_spores_confused_all",
  anim="ground2",
  bank="fx_dust",
  bloom=100.0,
  build="fx_dust",
  clip_at_worldedge=true,
  glowcolor="4A0545FF",
  group="fx_spores",
  multcolor="8080FFBF",
  onground=true,
  scalex=1.0,
  scaley=1.0,
  soundevent="spore_cloud_confused",
}
