-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="groak_slam_groundring",
  anim="groundring",
  bank="fx_hits_groundring",
  bloom=50.0,
  build="fx_hits_groundring",
  glowcolor="8E8F43FF",
  group="hits_fx",
  onground=true,
  randomflip=true,
  scalex=1.0,
  scaley=1.0,
  sortorder=-1,
}
