-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="healseed_arc_sml",
  addcolor="00802900",
  anim="electric_chain_arc_small_",
  bank="fx_hit_electric",
  bloom=100.0,
  build="fx_hit_electric",
  group="electricity",
  multcolor="FFFFFF57",
  noflip=true,
  onground=true,
  scalex=2.0,
  scaley=2.0,
  sortorder=-2,
  target_tint="FF640000",
  variations=2,
}
