-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="shield_acquire_groundring_frnt",
  anim="4_front",
  bank="fx_shields",
  bloom=100.0,
  build="fx_shield",
  finaloffset=7,
  glowcolor="0086FFFF",
  group="shields",
  multcolor="A6A6FFBF",
  sound_max_count=5.0,
  soundevent="Shield_Acquire",
}
