-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="yammo_spawn_jump_pst",
  anim="spawn_jump_pst",
  bank="fx_yammo",
  build="fx_yammo",
  finaloffset=1,
  group="fx_yammo",
}
