-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_ear_color_9",
  cosmetic_data={
    color={ 0.27799227833748, 0.20463320612907, 0.79922783374786,},
    color_species="canine",
    colorgroup="EAR_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
