-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_green_eye_color_1",
  cosmetic_data={
    color={ 0.21944444444444, 0.41, 1.0,},
    colorgroup="EYE_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
  
}
