-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_over_here",
  cosmetic_data={
    anim="emote_over_here",
    emote_species="none",
    icon_path="images/icons_ftf/item_temp.tex",
    name_key="emote_dejected",
  },
  group="PLAYER_EMOTE",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
