-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_ornament_color_2",
  cosmetic_data={
    color={ 0.36111111111111, 0.6, 0.9,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
