-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ponytail_wild_hair_front",
  cosmetic_data={
    bodypart_group="HAIR_FRONT",
    bodypart_species="ogre",
    build="player_hair_ogre_ponytail_wild",
    colorgroup="HAIR_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
