-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_dipdown_ears",
  cosmetic_data={
    bodypart_group="EARS",
    bodypart_species="ogre",
    build="player_ears_ogre_dipdown",
    colorgroup="EAR_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  hidden=false,
  locked=false,
  mastery="NONE",
  purchased=true,
  rarity="COMMON",
}
