-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_darkgrey_skin_tone_1",
  cosmetic_data={
    color={ 0.73333333333333, 0.03, 0.45,},
    color_species="ogre",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  hidden=true,
  locked=true,
  mastery="NONE",
  purchased=false,
  rarity="COMMON",
}
